#!/usr/bin/env python3
"""Generate `docs/machine/THEOREM_REGISTRY.jsonl` for the intermediate release.

The metadata (identifiers, roles, claim links, scope notes) is maintained in the table
below; the `statement_text` field is **extracted from the Lean source** by
`audit/lean_statement.py`, so that it cannot drift away from the repository.

Since Task 40 every entry also carries a `declaration_kind` field, read from the source text
(`theorem`, `lemma`, `definition`, `structure`, `abbreviation`, `instance`).  A few registry
entries are *definitions* rather than theorems; they are labelled as such, and the validator
requires every PROVED-like claim to be supported by at least one entry of kind `theorem` or
`lemma`.

`observed_axioms` is filled from `docs/machine/AXIOM_AUDIT.json`, which is generated from the
build output of `RequestProject/Spine/Closure/AxiomAudit.lean`.

Run from the repository root:

    python3 audit/build_theorem_registry.py
"""

from __future__ import annotations

import json
from pathlib import Path

from lean_statement import declaration_kind, extract_statement, extraction_status

ROOT = Path(__file__).resolve().parent.parent
SRC = "RequestProject/Spine/"

# theorem_id, lean_name, relative source path (under RequestProject/Spine/),
# category, mathematical_role, direct_dependencies, supports_claim_ids, task,
# scope_notes, overclaim_guard
TABLE = [
    ("THM-L001", "SpinCore.lorentz_quadratic_form", "E1/Core.lean", "local_lorentz",
     "The intrinsic quadratic form of the carrier is the Minkowski form of signature (1,3) in the intrinsic frame.",
     [], ["CLAIM-L002"], "T1-T9",
     "A computation inside the carrier; no metric on any manifold is involved.",
     "Does not say that any tangent space carries this form; that needs a regular solder."),
    ("THM-L002", "SpinCore.clifford_generator_square", "E1/Core.lean", "clifford",
     "The Clifford generators of the positive Euclidean three-form square to +1.",
     [], ["CLAIM-L003"], "T1-T9",
     "Statement about the generators of Cl3 = CliffordAlgebra q3.",
     "Not a statement about a Lorentzian Clifford algebra: the algebra is built on the positive Euclidean 3-form."),
    ("THM-L003", "SpinCore.paravector_norm", "E1/Core.lean", "clifford",
     "The paravector embedding of the carrier realises the intrinsic quadratic form through the Clifford conjugation.",
     ["THM-L002"], ["CLAIM-L004"], "T1-T9",
     "This is the bridge that makes Cl3 a carrier of Lorentz signature without postulating one.",
     "Does not assert an isomorphism with any standard Lorentzian Clifford algebra."),
    ("THM-L004", "SpinCore.clifford_jordan", "E1/Clifford.lean", "clifford",
     "The symmetrized Clifford product of two embedded carrier elements is the spin-factor Jordan product.",
     ["THM-L003"], ["CLAIM-L005"], "T1-T9",
     "Compatibility of the Clifford layer with the spin-factor (Jordan) layer of the carrier.",
     "Not a classification of Jordan algebras and not a uniqueness statement."),
    ("THM-L005", "SpinCore.adjoin_spinToCl_eq_top", "E1/Clifford.lean", "clifford",
     "The image of the carrier generates the Clifford algebra as a real algebra.",
     ["THM-L003"], ["CLAIM-L006"], "T1-T9",
     "Minimality of the Clifford layer over the carrier.",
     "Does not claim that the carrier is the unique generating subspace."),
    ("THM-L006", "SpinCore.spin_double_cover_of_lorentz", "E1/Core.lean", "spin",
     "The intrinsic Spin elements act on the carrier by the twisted Clifford action, the action lands in the intrinsic Lorentz group, every element of that group arises this way, and exactly the elements +/-1 act trivially.",
     ["THM-L003"], ["CLAIM-L007"], "T1-T9",
     "Unbundled form of the intrinsic double cover.",
     "The Lorentz group here is the project's own GLor, defined intrinsically from the carrier; it is not imported from Mathlib."),
    ("THM-L007", "SpinCore.spin_double_cover_bundled", "E1/Core.lean", "spin",
     "spinCover is a surjective group homomorphism SpinGroup -> GLor whose kernel is central of cardinality two.",
     ["THM-L006"], ["CLAIM-L007"], "T1-T9",
     "Bundled group-theoretic form; proved without SL(2,C).",
     "Does not assert that SpinGroup is a Lie group or that spinCover is a smooth covering map."),
    ("THM-L008", "SpinCore.spin_double_cover_topological_endpoint", "E1/Core.lean", "spin",
     "Both groups are Hausdorff topological groups, the cover is continuous and surjective, and its kernel is central and discrete.",
     ["THM-L007"], ["CLAIM-L008", "CLAIM-B001"], "T1-T9",
     "This is the exact regularity available for the Spin side of the project.",
     "Topological only: no smooth or Lie-group structure on SpinGroup is constructed anywhere."),
    ("THM-L009", "SpinCore.spin_double_cover_local_section_endpoint", "E1/Core.lean", "spin",
     "The intrinsic cover admits a continuous local section around every element of the intrinsic Lorentz group.",
     ["THM-L008"], ["CLAIM-L009"], "T1-T9",
     "Constructed by explicit algebraic inversion of the twisted action; no covering-space theory is quoted.",
     "Continuous sections only; no smooth sections are claimed."),
    ("THM-L012", "SpinCore.finrank_gB", "E1/LieAlgebra.lean", "local_lorentz",
     "The intrinsic Lorentz-skew Lie algebra gB of the carrier is six-dimensional.",
     ["THM-L014"], ["CLAIM-L011"], "T10",
     "Obtained from the linear equivalence with the exterior square of the carrier.",
     "A statement about the Lorentz-side skew algebra only; it says nothing about the intrinsic SpinGroup and does not identify gB with Lie(SpinGroup)."),
    ("THM-L013", "SpinCore.gBLie_bracket", "E1/LieAlgebra.lean", "local_lorentz",
     "On the Lie subalgebra gBLie the Lie bracket is the commutator of endomorphisms.",
     ["THM-L015"], ["CLAIM-L011"], "T10",
     "Identifies the abstract bracket of the LieSubalgebra with the concrete commutator.",
     "Not a statement about any Spin-side infinitesimal structure."),
    ("THM-L014", "SpinCore.bivectorEquivSkew_wedge", "E1/LieAlgebra.lean", "local_lorentz",
     "The intrinsic linear equivalence from bivectors of the carrier to skew endomorphisms sends a decomposable bivector to the explicit skew endomorphism Kend.",
     ["THM-L015"], ["CLAIM-L011"], "T10",
     "Characterises bivectorEquivSkew on decomposables, which is what fixes it.",
     "A linear equivalence, not a Lie-algebra isomorphism claim and not a representation of a group."),
    ("THM-L015", "SpinCore.gB_bracket_mem", "E1/Bivector.lean", "local_lorentz",
     "The commutator of two BS-skew endomorphisms of the carrier is BS-skew; this is what makes gB a Lie subalgebra.",
     [], ["CLAIM-L011"], "T10",
     "Uses the intrinsic polarized form BS only.",
     "Closure under the bracket; no exponential map and no group is involved."),
    ("THM-L010", "Task37.Deformation.transportState_add", "Deformation/SharedTransport.lean", "spin",
     "The shared native Spin transport state is a one-parameter subgroup of the intrinsic Spin group.",
     ["THM-L007"], ["CLAIM-L010"], "T37",
     "The single Spin-side source of the Task-37/38 deformation.",
     "A one-parameter subgroup of the group, not a connection, a transport form or an exponential of a curvature."),
    ("THM-L011", "Task37.Deformation.projectedTransportState_apply", "Deformation/ProjectedParaAction.lean", "spin",
     "The native projection of the shared transport state acts on the local model exactly as the explicit closed form paraMap.",
     ["THM-L010", "THM-L006"], ["CLAIM-L010"], "T38",
     "Computed inside the project's own Clifford algebra; this is what makes the solder equation solvable in closed form.",
     "paraMap is the value of the already certified projection, not an independently chosen Lorentz-side object."),

    ("THM-G001", "EmergentBase.base_not_determined_by_local_pieces", "Emergent/NonDerivability.lean", "gluing",
     "The same local pieces admit different emergent bases: the base gluing datum is genuinely additional information.",
     [], ["CLAIM-G001"], "T32",
     "Non-derivability of the global datum from the local core.",
     "Does not classify the possible gluings; it exhibits an inequivalence."),
    ("THM-G002", "EmergentBase.BaseGluingData.isManifold_of_smoothGluing", "Emergent/SmoothStructure.lean", "manifold",
     "A smooth base-gluing datum makes the reconstructed charted space a C-infinity manifold over the four-dimensional local model.",
     ["THM-G001"], ["CLAIM-G003"], "T33",
     "The smooth gate: smoothness of the primitive is an additional hypothesis, not a consequence.",
     "Does not claim that every base gluing is smooth; the negative control of the same module shows it is not."),
    ("THM-G003", "EmergentBase.BaseGluingData.smoothEmergentManifoldCertificate", "Emergent/SmoothStructure.lean", "manifold",
     "Under a closed gluing graph and a countable index type, the emergent base is Hausdorff, second countable, charted, a C-infinity manifold, and modelled on a four-dimensional real space.",
     ["THM-G002"], ["CLAIM-G004"], "T33",
     "The emergent smooth four-manifold endpoint.",
     "Four-dimensionality is that of the local model; no claim about diffeomorphism type, compactness or homotopy type."),
    ("THM-G004", "EmergentBase.BaseGluingData.tangentTransition_eq_derivative_baseTransition", "Emergent/TangentTransition.lean", "tangent",
     "The coordinate changes of Mathlib's genuine tangent bundle of the emergent manifold are the derivatives D(phi_ij) of the base-gluing identifications.",
     ["THM-G002"], ["CLAIM-G005"], "T34",
     "Connects the emergent atlas with the actual tangent bundle; no tangent space is postulated to be the local model.",
     "Does not identify TM with a trivial bundle."),
    ("THM-G005", "SpinNative.tangent_spin_base_data_do_not_force_transition_identification", "Solder/Independence.lean", "solder",
     "Base gluing plus native Spin transition data do not force any identification of the internal Lorentz transitions with the tangent transitions: the solder is an additional datum.",
     ["THM-G004"], ["CLAIM-G006"], "T34",
     "Isolates the solder as a genuine coupling primitive.",
     "Does not say a solder never exists; it says it is not implied."),
    ("THM-G006", "SpinNative.TangentSolderData.tangentMetric_wellDefined", "Solder/Solder.lean", "solder",
     "The solder-transported bilinear form computed in any solder frame containing the point is the same: the overlap law makes the frames differ by an element of GLor, which preserves the intrinsic form.",
     ["THM-G005"], ["CLAIM-G010"], "T34",
     "Chart independence of the transported tangent form.",
     "Weak (fibrewise) solder level; no regularity is claimed here."),
    ("THM-G007", "SpinNative.weak_solder_not_regular", "Solder/WeakInsufficiency.lean", "solder",
     "There is a weak solder datum whose local representative, and whose induced metric, are not continuous: weak solder data are strictly weaker than regular ones.",
     ["THM-G006"], ["CLAIM-G007", "CLAIM-N001", "CLAIM-N002"], "T35",
     "Adversarial control for the regularity gate.",
     "A single explicit counterexample; it does not measure how large the gap is."),
    ("THM-G008", "SpinNative.smooth_solder_iff_regular_bundle_equivalence", "Solder/BundleEquivalence.lean", "solder",
     "A regular solder exists exactly when the internal Lorentz bundle of the native Spin datum is equivalent, at the stated regularity, to the tangent bundle of the emergent manifold.",
     ["THM-G004", "THM-G005"], ["CLAIM-G008"], "T35",
     "Identifies the coupling primitive with a bundle-level equivalence; the regularity level is stated exactly (continuous total-space maps, C-infinity local representatives).",
     "Not a *smooth* bundle equivalence in the strong sense; the stronger total-space smooth packaging is an infrastructure/packaging limitation (no vector-bundle equivalence type in the pinned Mathlib), NOT a consequence of the native Spin transitions being continuous: a regular smooth solder already gives smooth projected Lorentz transition representatives (Task 36 correction). Smooth projected Lorentz data is not a packaged smooth intrinsic Spin Lie-group bundle theory."),
    ("THM-G009", "SpinNative.SmoothTangentSolderData.smooth_tangent_lorentz_metric", "Solder/SmoothMetric.lean", "solder",
     "For a regular solder the induced metric coefficients are C-infinity on every chart domain, symmetric, nondegenerate, transform as a (0,2)-tensor under the genuine tangent transitions, and have signature (1,3) in every solder frame.",
     ["THM-G008", "THM-G006"], ["CLAIM-G009"], "T35",
     "The smooth Lorentzian tangent geometry of the regular-solder sector.",
     "Conditional on a regular solder being given; no existence statement, and no Levi-Civita connection or curvature."),
    ("THM-G010", "Task36.smooth_solder_implies_orientation_compatible", "Task36/OrientationGate.lean", "topology_control",
     "A regular solder forces the existence of a nowhere-zero continuous chartwise function whose transformation law makes all tangent transition determinants positive: the emergent atlas is orientation compatible.",
     ["THM-G009"], ["CLAIM-G011"], "T36",
     "Project-native orientation gate; no orientation datum was assumed anywhere in the construction.",
     "This is a project-native compatibility statement, not the standard vanishing of w1(TM)."),
    ("THM-G011", "Task36.orientation_obstruction_nonzero_implies_no_solder", "Task36/OrientationGate.lean", "topology_control",
     "If no such orientation datum exists then no native Spin transition datum admits a regular solder.",
     ["THM-G010"], ["CLAIM-G012"], "T36",
     "Contrapositive gate, used by the Moebius-type control.",
     "Does not compute any characteristic class."),
    ("THM-G012", "Task36.smooth_solder_implies_spin_obstruction_trivial", "Task36/SpinObstruction.lean", "topology_control",
     "A regular solder forces the project-native Spin-lifting obstruction class of the projected Lorentz cocycle to be trivial.",
     ["THM-G009"], ["CLAIM-G013"], "T36",
     "Project-native Spin gate: the obstruction is the fixed-cover kernel-valued class of the project's own Cech layer.",
     "Not the statement w2(TM)=0: no Stiefel-Whitney class exists in this project."),
    ("THM-G013", "Task36.spin_obstruction_nonzero_implies_no_solder", "Task36/SpinObstruction.lean", "topology_control",
     "A nontrivial project-native obstruction class rules out every native Spin datum projecting to the given Lorentz cocycle together with a regular solder.",
     ["THM-G012"], ["CLAIM-G014"], "T36",
     "Contrapositive Spin gate.",
     "Same scope restriction as THM-G012."),
    ("THM-G014", "Task36.classical_reconvergence", "Task36/SpinObstruction.lean", "topology_control",
     "A regular solder simultaneously forces orientation compatibility, identifies the solder's internal Lorentz representative with the projected transition, and trivialises the project-native Spin obstruction.",
     ["THM-G010", "THM-G012"], ["CLAIM-G011", "CLAIM-G013"], "T36",
     "The reconvergence statement: global closure conditions re-emerge from a bottom-up construction that never assumed them.",
     "Both gates are project-native; neither is identified with a standard characteristic class."),
    ("THM-G015", "Task36.nonempty_regularBundleCertificate_iff", "Task36/SmoothBundlePackaging.lean", "solder",
     "A regular solder exists exactly when the six-item regular bundle-equivalence certificate exists.",
     ["THM-G008"], ["CLAIM-G008"], "T36",
     "Packaging form of the bundle equivalence.",
     "Regularity level as in THM-G008."),
    ("THM-G016", "Task36.nonempty_timeOrientationReduction_of_solder", "Task36/TimeOrientation.lean", "topology_control",
     "A regular solder yields a coherent chartwise future-cone reduction of the internal Lorentz data.",
     ["THM-G009"], ["CLAIM-G015"], "T36",
     "Time-orientation datum in the project's own sense.",
     "The reduction is a chartwise cone choice; it is not proved equivalent to general time-orientability of the manifold."),
    ("THM-G017", "Task36.loop_timeOrientationReduction_isGlued", "Task36/LoopTimeOrientation.lean", "topology_control",
     "On the periodic control the future-cone reduction is glued across the overlaps, i.e. the distinguished time field is consistent there.",
     ["THM-G016"], ["CLAIM-G015"], "T36",
     "Concrete instance of the reduction on the control base.",
     "A statement about this control model only."),
    ("THM-G018", "Task36.regular_solder_is_gauge_torsor", "Task36/GaugeGroup.lean", "solder",
     "The regular tangent gauge fields form a group acting freely and transitively on the regular solder data of a fixed base and Spin seed.",
     ["THM-G009"], ["CLAIM-G016"], "T36",
     "Exact residual freedom of the solder.",
     "Freeness and transitivity for a fixed base and fixed native Spin datum only."),
    ("THM-G019", "SpinNative.SmoothTangentSolderData.regular_solder_torsor", "Solder/RegularGauge.lean", "solder",
     "Any two regular solder data for the same base and Spin datum differ by a unique regular gauge field.",
     ["THM-G018"], ["CLAIM-G016"], "T35",
     "Uniqueness half of the gauge freedom.",
     "Same fixed-data scope as THM-G018."),
    ("THM-G020", "Task36.one_loop_has_kernel_sign_freedom", "Task36/LoopSpinFreedom.lean", "topology_control",
     "Over the one-loop control there are two native Spin transition data with the same projected Lorentz transitions, both admitting a regular solder, that are not related by the project's kernel-valued fixed-cover gauge equivalence.",
     ["THM-G009"], ["CLAIM-G018", "CLAIM-N005"], "T36",
     "The discrete lift freedom survives the bottom-up construction.",
     "Fixed-cover freedom; it is not identified with H^1(M;Z/2)."),
    ("THM-G021", "Task36.two_loop_spin_choice_family", "Task36/LoopSpinFreedom.lean", "topology_control",
     "With two independent loops there are four pairwise gauge-inequivalent native Spin data, all admitting regular solders.",
     ["THM-G020"], ["CLAIM-G019", "CLAIM-N005"], "T36",
     "Multiplicity 2^N instantiated at N = 2.",
     "Fixed-cover multiplicity; not a computation of a cohomology group of the emergent manifold."),
    ("THM-G022", "Task36.orientation_reversing_gluing_no_solder", "Task36/OrientationReversing.lean", "topology_control",
     "Over the Moebius-type orientation-reversing gluing no native Spin transition datum admits a regular solder.",
     ["THM-G011"], ["CLAIM-G017", "CLAIM-N003"], "T36",
     "The decisive negative control: the regular solder is a gate, not a universally available structure.",
     "A statement about this explicit model; it does not classify which gluings admit solders."),
    ("THM-G023", "Task36.spin_does_not_imply_lorentz_moebius", "Task36/SpinNotLorentz.lean", "topology_control",
     "Over the same Moebius-type gluing native Spin transition data do exist while no regular solder does.",
     ["THM-G022"], ["CLAIM-N009"], "T36",
     "Project-native separation of 'Spin-type data exist' from 'tangent Lorentz coupling exists'.",
     "This is not the classical S^4 separation theorem; no characteristic class is computed."),
    ("THM-G024", "Task36.spin_foam_labels_do_not_determine_solder", "Task36/SpinFoamControl.lean", "topology_control",
     "Abstract combinatorial Spin-foam-style labels carry no information forcing a regular solder.",
     [], ["CLAIM-N008"], "T36",
     "Rules out a combinatorial shortcut to the coupling.",
     "A statement about the project's own label structure, not about any published spin-foam model."),
    ("THM-G025", "Task36.oneChart_positive_control", "Task36/TrivialControl.lean", "topology_control",
     "On the one-chart base a regular solder exists, there is no overlap obstruction, and no artificial sign family appears.",
     ["THM-G009"], ["CLAIM-G022"], "T36",
     "Positive control, showing the gates are not vacuously closed.",
     "Trivial topology; nothing global is tested by it."),
    ("THM-G026", "Task36.adversarial_global_topology_certificate", "Task36/Certificate.lean", "topology_control",
     "The bundled Task-36 result: reconvergence, the two contrapositive gates, the smooth bundle packaging, the time-orientation reduction, and the four concrete control models.",
     ["THM-G014", "THM-G015", "THM-G016", "THM-G020", "THM-G021", "THM-G022", "THM-G023", "THM-G025"],
     ["CLAIM-G021"], "T36",
     "Aggregate certificate; blocked or external cases are deliberately absent from it.",
     "Every field is exactly the theorem it aggregates; nothing is strengthened by aggregation."),

    ("THM-S001", "Task37.Deformation.not_forall_regularClosureAdmissible", "Deformation/ClosureAdmissibility.lean", "deformation",
     "There is no universal existence theorem for regular closure solutions: some families are not admissible at some parameter values.",
     ["THM-G022"], ["CLAIM-B007", "CLAIM-N006"], "T37",
     "Anti-vacuity of the closure predicate used by the smoke test.",
     "Shows the predicate has content; it does not classify the admissible families."),
    ("THM-S002", "Task37.Deformation.selective_family_not_admissible_of_ne", "Deformation/ClosureAdmissibility.lean", "deformation",
     "An explicitly constructed co-varying family is admissible exactly at the neutral parameter value.",
     ["THM-S001"], ["CLAIM-N006"], "T37",
     "Shows the closure observable can select a parameter value, so a negative smoke-test result is informative.",
     "Concerns a constructed selective family, not the Task-38 fixed-base family."),
    ("THM-S003", "Task37.Deformation.controlA_interface_certificate", "Deformation/SmokeTestCertificate.lean", "smoketest",
     "Interface certificate of the experiment: the base gluing is the same at every parameter value, the Lorentz transition is by definition the projection of the Spin state, the neutral value reproduces the frozen Task-36 seed, and the deformation is visible after projection.",
     ["THM-L011"], ["CLAIM-S011"], "T38",
     "Records what is varied, derived, held fixed and solved for.",
     "Absence of transport forms, loop functionals, field strengths and field equations is part of the record."),
    ("THM-S004", "Task37.Deformation.controlAAdmissible_zero", "Deformation/FixedBaseSmokeTest.lean", "smoketest",
     "The neutral parameter value is admissible, by the exact frozen Task-36 regular solution.",
     ["THM-G009"], ["CLAIM-S001"], "T38",
     "Neutral regression of the smoke test.",
     "Control-specific."),
    ("THM-S005", "Task37.Deformation.controlAAdmissible_all", "Deformation/FixedBaseSmokeTest.lean", "smoketest",
     "Every finite parameter value of the fixed-base family is admissible, with an explicitly constructed compensating regular solder.",
     ["THM-S004", "THM-L011"], ["CLAIM-S001", "CLAIM-S007"], "T38",
     "Solved exactly, not sampled; the witness is constructed, not obtained from a choice principle.",
     "Statement about the frozen periodic control base and the Task-37 family only."),
    ("THM-S006", "Task37.Deformation.regularRegion_loopTransportFamily", "Deformation/FixedBaseSmokeTest.lean", "smoketest",
     "The admissibility locus of the fixed-base family is all of the real line.",
     ["THM-S005"], ["CLAIM-S002"], "T38",
     "Locus form of THM-S005.",
     "Control-specific."),
    ("THM-S007", "Task37.Deformation.controlAAdmissible_neg_iff", "Deformation/FixedBaseSmokeTest.lean", "smoketest",
     "Admissibility of the fixed control is symmetric under negation of the parameter.",
     ["THM-S005"], ["CLAIM-S003"], "T38",
     "Corollary of the universal statement.",
     "Nothing geometric is read into the sign: -l is the opposite direction along the Spin one-parameter subgroup."),
    ("THM-S008", "Task37.Deformation.spinCocycle_gaugeEquiv", "Deformation/CocycleGaugeOrbit.lean", "smoketest",
     "Any two parameter values of the fixed-base family give native Spin cocycles related by a continuous chartwise full-group gauge transformation.",
     ["THM-S005"], ["CLAIM-S004"], "T38",
     "The decisive gauge statement of the smoke test: the whole family lies in one orbit.",
     "Continuity, not smoothness, of the Spin-side gauge; and the tested family on this control only."),
    ("THM-S009", "Task37.Deformation.projectedCocycle_gaugeEquiv", "Deformation/CocycleGaugeOrbit.lean", "smoketest",
     "Pushing the same Spin-side gauge through the native projection shows the projected Lorentz cocycles are gauge equivalent too.",
     ["THM-S008"], ["CLAIM-S005"], "T38",
     "Derived, not independently chosen: no Lorentz-side relabelling is introduced.",
     "Same scope as THM-S008."),
    ("THM-S010", "Task37.Deformation.not_kernelGaugeEquiv_of_ne_zero", "Deformation/CocycleGaugeOrbit.lean", "smoketest",
     "At the project's narrower kernel-valued fixed-cover equivalence the deformed datum is not equivalent to the neutral one for a nonzero parameter.",
     ["THM-S008"], ["CLAIM-S006", "CLAIM-N007"], "T38",
     "Records that a nonzero deformation moves the projection, so it is not a plus/minus-one relabelling.",
     "Not a geometric distinction and not in contradiction with THM-S008: the two relations are different."),
    ("THM-S011", "Task37.Deformation.loopParaSolder_A_comparison", "Deformation/TangentMetricComparison.lean", "smoketest",
     "The explicit solder witnesses at two parameter values differ chartwise by the projected transport state, an element of the intrinsic Lorentz group.",
     ["THM-S005"], ["CLAIM-S008"], "T38",
     "Mechanism behind the metric equality.",
     "About the explicit witnesses."),
    ("THM-S012", "Task37.Deformation.tangentMetric_loopParaSolder_eq", "Deformation/TangentMetricComparison.lean", "smoketest",
     "The induced tangent Lorentz metrics of the explicit witnesses are literally equal at every point and on every pair of tangent vectors, for all parameter values.",
     ["THM-S011", "THM-G006"], ["CLAIM-S008"], "T38",
     "The invariant question of the smoke test, answered negatively.",
     "Along the explicit certified branch; the general solution-space form is THM-S016."),
    ("THM-S013", "Task37.Deformation.native_transport_knob_smoketest_certificate", "Deformation/SmokeTestCertificate.lean", "smoketest",
     "Bundled Task-38 result: neutral admissibility, universal admissibility, the locus, the sign symmetry, the Spin and projected-Lorentz gauge classification, the solder comparison and the metric equality.",
     ["THM-S004", "THM-S005", "THM-S006", "THM-S007", "THM-S008", "THM-S009", "THM-S011", "THM-S012"],
     ["CLAIM-S001", "CLAIM-S004", "CLAIM-S008"], "T38",
     "Aggregate certificate of the smoke test.",
     "Contains nothing about transport forms, loop transport, curvature or field equations."),
    ("THM-S014", "Task37.Deformation.smoketest_negative_records", "Deformation/SmokeTestCertificate.lean", "smoketest",
     "The accompanying negative records: kernel-valued inequivalence for nonzero parameter, non-constancy of the projected family, and its first-order non-degeneracy at the neutral value.",
     ["THM-S010"], ["CLAIM-S006"], "T38",
     "Kept separate from the principal certificate because it says something different.",
     "A parameter-space statement about an explicit curve of linear maps; not a transport form."),
    ("THM-S015", "Task37.Deformation.loopProjectedGauge_eq", "Deformation/SmoothProjectedGauge.lean", "smoketest",
     "The projected gauge used by the smoke test is the native projection of the Task-38 Spin gauge, evaluated at the chart coordinate of the point.",
     ["THM-L011", "THM-S008"], ["CLAIM-S009"], "T39",
     "Guarantees that the smooth object of THM-S017 is not a second, independently chosen Lorentz-side relabelling.",
     "Control-specific."),
    ("THM-S016", "Task37.Deformation.contDiffOn_loopProjectedGauge", "Deformation/SmoothProjectedGauge.lean", "smoketest",
     "On the chart domain of every patch the projected Lorentz gauge transformation of the smoke test is C-infinity.",
     ["THM-S015"], ["CLAIM-S009", "CLAIM-B001"], "T39",
     "The exact extra regularity available on the projected side.",
     "Projected (Lorentz) side only: the Spin-side gauge remains certified as continuous, since the intrinsic SpinGroup carries no smooth structure."),
    ("THM-S017", "Task37.Deformation.loopSolderTransport", "Deformation/SolderTransport.lean", "smoketest",
     "DEFINITION (not a theorem): the transport map itself. Precomposing an arbitrary regular solder for the parameter l1 with the projected gauge produces a regular solder for the parameter l2.",
     ["THM-S016"], ["CLAIM-S010"], "T39",
     "A construction; its declaration_kind is 'definition'. The proved content about it is THM-S019, THM-S020 and THM-S021; smoothness of the transported comparison uses THM-S016.",
     "Defined for the frozen periodic control base and the Task-37 family only; a definition proves nothing by itself."),
    ("THM-S018", "Task37.Deformation.loopSolderEquiv", "Deformation/SolderTransport.lean", "smoketest",
     "DEFINITION (not a theorem): the explicit bijection (Equiv) between the regular solder solution spaces at two parameter values.",
     ["THM-S017"], ["CLAIM-S010"], "T39",
     "A construction; its declaration_kind is 'definition'. Its involutivity is the theorem THM-S021, and the metric invariance is THM-S019/THM-S020. It upgrades the Task-38 comparison from one explicit branch to the whole regular solution space of this control.",
     "Control-specific; no statement about other bases or other deformations; a definition proves nothing by itself."),
    ("THM-S019", "Task37.Deformation.tangentMetric_loopSolderTransport", "Deformation/SolderTransport.lean", "smoketest",
     "Every regular solder solution and its transport induce literally the same tangent Lorentz metric.",
     ["THM-S018", "THM-G006"], ["CLAIM-S010"], "T39",
     "The invariant statement at solution-space level.",
     "Control-specific."),
    ("THM-S020", "Task37.Deformation.loopSolderSolutionSpace_correspondence", "Deformation/SolderTransport.lean", "smoketest",
     "Bundled solution-space form: a bijection of the regular solution spaces under which the induced tangent Lorentz metric is preserved.",
     ["THM-S018", "THM-S019"], ["CLAIM-S010"], "T39",
     "The strongest metric-comparison statement the project has.",
     "Frozen periodic control base and the Task-37 family only."),

    ("THM-S021", "Task37.Deformation.loopSolderTransport_involutive", "Deformation/SolderTransport.lean", "smoketest",
     "The explicit transport of regular solder solutions between two parameter values is involutive, which is the theorem-level content behind the bijection of solution spaces.",
     [], ["CLAIM-S010"], "T39",
     "The frozen periodic control base and the Task-37 family only.",
     "Not a general transport theorem for arbitrary bases, deformations or gauges."),
    ("THM-C001", "Closure.local_core_certificate", "Closure/IntermediateMilestone.lean", "closure",
     "Aggregation of the certified intrinsic local core.",
     ["THM-L001", "THM-L004", "THM-L007", "THM-L008", "THM-L009"],
     ["CLAIM-L002", "CLAIM-L005", "CLAIM-L007", "CLAIM-L008", "CLAIM-L009"], "T39",
     "Aggregation only.", "No conjunct is stronger than the theorem discharging it."),
    ("THM-C002", "Closure.global_layer_certificate", "Closure/IntermediateMilestone.lean", "closure",
     "Aggregation of the certified global layer for an arbitrary smooth base gluing and native Spin datum, with all solder-dependent items stated conditionally.",
     ["THM-G003", "THM-G009", "THM-G014", "THM-G015", "THM-G016"],
     ["CLAIM-G004", "CLAIM-G008", "CLAIM-G009", "CLAIM-G011", "CLAIM-G013", "CLAIM-G015"], "T39",
     "Aggregation only.",
     "Every solder-dependent conjunct is an implication with hypothesis 'a regular solder exists'."),
    ("THM-C003", "Closure.fixed_cover_lift_freedom_certificate", "Closure/IntermediateMilestone.lean", "closure",
     "Aggregation of the surviving discrete fixed-cover Spin-lift freedom.",
     ["THM-G020"], ["CLAIM-G018"], "T39",
     "Aggregation only.", "Fixed-cover freedom, not a cohomology computation."),
    ("THM-C004", "Closure.smoketest_certificate", "Closure/IntermediateMilestone.lean", "closure",
     "Aggregation of the smoke test at exactly its proved scope, including the two Task-39 strengthenings.",
     ["THM-S005", "THM-S006", "THM-S008", "THM-S009", "THM-S016", "THM-S020", "THM-S012"],
     ["CLAIM-S001", "CLAIM-S002", "CLAIM-S004", "CLAIM-S005", "CLAIM-S009", "CLAIM-S010"], "T39",
     "Aggregation only.",
     "Every conjunct is about the frozen periodic control base and the Task-37 family."),
    ("THM-C005", "Closure.intermediate_milestone_certificate", "Closure/IntermediateMilestone.lean", "closure",
     "The single aggregate statement of the frozen intermediate release.",
     ["THM-C001", "THM-C002", "THM-C003", "THM-C004"],
     ["CLAIM-G004", "CLAIM-G008", "CLAIM-G011", "CLAIM-G013", "CLAIM-L007", "CLAIM-S001", "CLAIM-S004", "CLAIM-S009", "CLAIM-S010"],
     "T39",
     "The principal certificate module of the closure branch.",
     "Contains no conjunct about a connection, parallel transport, holonomy, curvature or field equation."),
]

CATEGORY_VALUES = {
    "local_lorentz", "clifford", "spin", "gluing", "manifold", "tangent", "solder",
    "topology_control", "deformation", "smoketest", "closure",
}


def main() -> None:
    axioms = json.loads((ROOT / "docs/machine/AXIOM_AUDIT.json").read_text(encoding="utf-8"))
    observed = {e["lean_name"]: e["observed_axioms"] for e in axioms["endpoints"]}
    out = []
    for (tid, name, rel, category, role, deps, claims, task, scope, guard) in TABLE:
        assert category in CATEGORY_VALUES, category
        path = SRC + rel
        short = name.split(".")[-1]
        statement = extract_statement(ROOT / path, short)
        kind = declaration_kind(ROOT / path, short)
        module = "RequestProject.Spine." + rel[:-len(".lean")].replace("/", ".")
        entry = {
            "theorem_id": tid,
            "lean_name": name,
            "module": module,
            "source_path": path,
            "category": category,
            "declaration_kind": kind,
            "statement_text": statement,
            "statement_extraction_status": extraction_status(ROOT / path, short, statement),
            "hypotheses": "see statement_text; hypotheses are exactly the binders shown there",
            "conclusion": role,
            "mathematical_role": role,
            "direct_dependencies": deps,
            "supports_claim_ids": claims,
            "task_origin": task,
            "proof_status": "PROVED" if kind in ("theorem", "lemma") else "CONSTRUCTED",
            "axiom_audit_status": "PASS" if name in observed else "NOT_AUDITED",
            "observed_axioms": observed.get(name, []),
            "scope_notes": scope,
            "overclaim_guard": guard,
        }
        out.append(entry)
    dest = ROOT / "docs/machine/THEOREM_REGISTRY.jsonl"
    with dest.open("w", encoding="utf-8") as fh:
        for e in out:
            fh.write(json.dumps(e, ensure_ascii=False) + "\n")
    print(f"wrote {len(out)} entries to {dest}")


if __name__ == "__main__":
    main()
