import RequestProject.Experiment2.NullSectorTask09.RealScalarNoGo

/-!
# Task 09, Layer 2: the internal central two-plane

Phase A failed.  By the hard firewall of §10 of the task the associative
carrier `W` reconstructed in Task 08 stays **fixed**: no generator is added and
no new product carrier is introduced.  Only the *codomain* of the quadratic map
may be enlarged, and the only candidate allowed is the two-dimensional
subspace of `W` generated by the unit and the internally derived central
element `S`.

Everything in this module is derived from three inherited Task-08 facts alone:

* `w1` is a two-sided unit;
* `wS` is central in `W`;
* `wS ⋆ wS = - w1`.

`Z` is **not** called a complex number system and no complex-number
implementation is imported.
-/

namespace NullSectorTask09

open NullSectorTask01 NullSectorTask08

/-- **DERIVED.**  The internal central two-plane `Z = spanℝ {1, S}`. -/
def CentralPlane : Submodule ℝ W := Submodule.span ℝ {w1, wS}

@[inherit_doc] scoped notation "Z" => CentralPlane

theorem w1_mem_Z : w1 ∈ Z := Submodule.subset_span (by simp)

theorem wS_mem_Z : wS ∈ Z := Submodule.subset_span (by simp)

/-- **NORMAL FORM.**  Membership in the central plane is exactly the existence
of a two-coefficient expansion. -/
theorem mem_Z_iff (x : W) : x ∈ Z ↔ ∃ a b : ℝ, x = a • w1 + b • wS := by
  rw [CentralPlane, Submodule.mem_span_pair]
  constructor
  · rintro ⟨a, b, rfl⟩; exact ⟨a, b, rfl⟩
  · rintro ⟨a, b, rfl⟩; exact ⟨a, b, rfl⟩

theorem smul_add_smul_mem_Z (a b : ℝ) : a • w1 + b • wS ∈ Z :=
  (mem_Z_iff _).2 ⟨a, b, rfl⟩

/-! ## Uniqueness of the two coefficients -/

/-- **DERIVED.**  The unit and the central element are linearly independent, so
the two-coefficient expansion is unique. -/
theorem Z_coeff_unique {a b a' b' : ℝ} (h : a • w1 + b • wS = a' • w1 + b' • wS) :
    a = a' ∧ b = b' := by
  have h0 := congrFun h 0
  have h7 := congrFun h 7
  simp [w1, wS] at h0 h7
  exact ⟨h0, h7⟩

theorem Z_eq_zero_iff {a b : ℝ} : a • w1 + b • wS = 0 ↔ a = 0 ∧ b = 0 := by
  constructor
  · intro h
    have h' : a • w1 + b • wS = (0 : ℝ) • w1 + (0 : ℝ) • wS := by simpa using h
    exact Z_coeff_unique h'
  · rintro ⟨rfl, rfl⟩; simp

/-! ## The complete internal multiplication -/

/-- **DERIVED.**  The complete internal multiplication of the central plane,
obtained from the two-sided unit, the centrality of `S`, and `S ⋆ S = -1`.
No further input is used. -/
theorem central_mul_rule (a b c d : ℝ) :
    (a • w1 + b • wS) ⋆ (c • w1 + d • wS)
      = (a * c - b * d) • w1 + (a * d + b * c) • wS := by
  simp only [add_mul_W, mul_add_W, smul_mul_W, mul_smul_W, one_mul_W, mul_one_W,
    wS_sq]
  module

/-- **CLOSURE.**  `Z ⋆ Z ⊆ Z`. -/
theorem Z_mul_mem {x y : W} (hx : x ∈ Z) (hy : y ∈ Z) : x ⋆ y ∈ Z := by
  obtain ⟨a, b, rfl⟩ := (mem_Z_iff x).1 hx
  obtain ⟨c, d, rfl⟩ := (mem_Z_iff y).1 hy
  rw [central_mul_rule]
  exact smul_add_smul_mem_Z _ _

/-- **COMMUTATIVITY.**  The induced multiplication of the central plane is
commutative. -/
theorem Z_mul_comm {x y : W} (hx : x ∈ Z) (hy : y ∈ Z) : x ⋆ y = y ⋆ x := by
  obtain ⟨a, b, rfl⟩ := (mem_Z_iff x).1 hx
  obtain ⟨c, d, rfl⟩ := (mem_Z_iff y).1 hy
  rw [central_mul_rule, central_mul_rule]
  ring_nf

/-- **CENTRALITY.**  Every element of the central plane commutes with *every*
element of the eight-dimensional carrier. -/
theorem Z_central {z : W} (hz : z ∈ Z) (x : W) : z ⋆ x = x ⋆ z := by
  obtain ⟨a, b, rfl⟩ := (mem_Z_iff z).1 hz
  rw [add_mul_W, mul_add_W, smul_mul_W, smul_mul_W, mul_smul_W, mul_smul_W,
    one_mul_W, mul_one_W, wS_central]

/-- The unit of the ambient carrier is a two-sided unit for the induced
multiplication of the central plane. -/
theorem Z_one_mul {x : W} (_hx : x ∈ Z) : w1 ⋆ x = x := one_mul_W x

/-! ## Exact dimension -/

theorem w1_wS_linearIndependent : LinearIndependent ℝ ![w1, wS] := by
  rw [LinearIndependent.pair_iff]
  intro s t hst
  exact Z_eq_zero_iff.1 hst

theorem Z_eq_span_range : Z = Submodule.span ℝ (Set.range ![w1, wS]) := by
  rw [CentralPlane]
  congr 1
  simp [Matrix.range_cons, Matrix.range_empty, Set.pair_comm]

/-- **EXACT DIMENSION.**  `dimℝ Z = 2`. -/
theorem finrank_Z : Module.finrank ℝ (Z : Submodule ℝ W) = 2 := by
  rw [Z_eq_span_range, finrank_span_eq_card w1_wS_linearIndependent]
  simp

/-- **CENTRAL PLANE (summary).**  Closed under the inherited product,
commutative, central in the whole carrier, and of exact real dimension two. -/
theorem centralPlane_summary :
    (∀ x y : W, x ∈ Z → y ∈ Z → x ⋆ y ∈ Z) ∧
    (∀ x y : W, x ∈ Z → y ∈ Z → x ⋆ y = y ⋆ x) ∧
    (∀ z : W, z ∈ Z → ∀ x : W, z ⋆ x = x ⋆ z) ∧
    Module.finrank ℝ (Z : Submodule ℝ W) = 2 :=
  ⟨fun _ _ hx hy => Z_mul_mem hx hy, fun _ _ hx hy => Z_mul_comm hx hy,
    fun _ hz x => Z_central hz x, finrank_Z⟩

end NullSectorTask09
