import RequestProject.Experiment2.NullSectorTask12.CarrierFamily

/-!
# Task 12, Layer 6: the distinguished axis and the action of the automorphism family
(§26 part 1, §27, §28, §29)

Everything proved *before* this module — existence of proper nonzero left carriers, the
exact set of generated-carrier dimensions `{4, 8}`, the minimal dimension `4`, the
minimal-generator criterion, the classification of minimal carriers, their infinitude and
their pairwise equivalence — is stated and proved without ever mentioning the
distinguished axis `wA`.  Those results are therefore recorded as

```
AXIS-INDEPENDENT.
```

The present module is the first one in which the axis is used, and it is used only to
*locate* particular carriers inside the already classified family, never to produce them.
The results recorded as

```
AXIS-DEPENDENT
```

are exactly: the explicit two-element set of carriers fixed by the whole automorphism
family that is exhibited here, and the half-angle comparison of the next module.

## Content

* the inherited automorphism family preserves the inherited central quadratic datum;
* `Φθ` maps left carriers to left carriers and minimal carriers to minimal carriers
  (`Submodule.map (Phi θ) (Lgen ψ) = Lgen (Phi θ ψ)`);
* an explicit two-sphere `esph n₁ n₂ n₃` (with `n₁² + n₂² + n₃² = 1`) of pairwise
  distinct minimal carriers, on which `Φθ` acts by rotating the pair `(n₂, n₃)`;
* consequently: **the family of minimal carriers is not fixed pointwise** — the carriers
  with `n₁ = 0` move on circles — while the two axial carriers `esph (±1) 0 0` are fixed
  for every `θ`.
-/

namespace NullSectorTask12

open NullSectorTask08 NullSectorTask09 NullSectorTask10

/-! ## The automorphism family preserves the inherited quadratic datum -/

theorem nRe_Phi (θ : ℝ) (x : W) : nRe (Phi θ x) = nRe x := by
  have hpyth := Real.sin_sq_add_cos_sq θ
  simp only [nRe, Phi_coord_0, Phi_coord_1, Phi_coord_2, Phi_coord_3, Phi_coord_4,
    Phi_coord_5, Phi_coord_6, Phi_coord_7]
  linear_combination (-(x 2) ^ 2 - (x 3) ^ 2 + (x 4) ^ 2 + (x 5) ^ 2) * hpyth

theorem nSc_Phi (θ : ℝ) (x : W) : nSc (Phi θ x) = nSc x := by
  have hpyth := Real.sin_sq_add_cos_sq θ
  simp only [nSc, Phi_coord_0, Phi_coord_1, Phi_coord_2, Phi_coord_3, Phi_coord_4,
    Phi_coord_5, Phi_coord_6, Phi_coord_7]
  linear_combination (2 * (x 2 * x 5 - x 3 * x 4)) * hpyth

theorem isNullElt_Phi (θ : ℝ) {x : W} (h : IsNullElt x) : IsNullElt (Phi θ x) :=
  ⟨by rw [nRe_Phi]; exact h.1, by rw [nSc_Phi]; exact h.2⟩

/-! ## The automorphism family permutes the carriers -/

/-- **DERIVED (§26.1).**  The image of a generated carrier is the carrier generated by
the image. -/
theorem Phi_map_Lgen (θ : ℝ) (ψ : W) :
    Submodule.map (Phi θ) (Lgen ψ) = Lgen (Phi θ ψ) := by
  ext y
  simp only [Submodule.mem_map, mem_Lgen_iff]
  constructor
  · rintro ⟨z, ⟨x, rfl⟩, rfl⟩
    exact ⟨Phi θ x, (Phi_mul θ x ψ).symm⟩
  · rintro ⟨x, rfl⟩
    obtain ⟨x', rfl⟩ := (Phi_bijective θ).2 x
    exact ⟨x' ⋆ ψ, ⟨x', rfl⟩, Phi_mul θ x' ψ⟩

/-- **DERIVED (§26.1).**  The image of a left carrier is a left carrier. -/
theorem isLeftCarrier_map_Phi {L : Submodule ℝ W} (hL : IsLeftCarrier L) (θ : ℝ) :
    IsLeftCarrier (Submodule.map (Phi θ) L) := by
  rintro x y ⟨ψ, hψ, rfl⟩
  obtain ⟨x', rfl⟩ := (Phi_bijective θ).2 x
  exact ⟨x' ⋆ ψ, hL x' ψ hψ, Phi_mul θ x' ψ⟩

/-- **PRINCIPAL THEOREM (§26.1).**  The inherited automorphism family maps every minimal
left carrier to a minimal left carrier. -/
theorem isMinimal_map_Phi {L : Submodule ℝ W} (hL : IsMinimalLeftCarrier L) (θ : ℝ) :
    IsMinimalLeftCarrier (Submodule.map (Phi θ) L) := by
  obtain ⟨ψ, hψ, hnull, rfl⟩ := isMinimal_eq_Lgen hL
  rw [Phi_map_Lgen]
  refine (isMinimal_Lgen_iff _).2 ⟨?_, isNullElt_Phi θ hnull⟩
  intro hzero
  exact hψ ((Phi_bijective θ).1 (by rw [hzero, map_zero]))

/-! ## An explicit two-sphere of minimal carriers -/

/-- An explicit two-parameter family of self-product generators built from the derived
basis elements `wA, wB, wC`. -/
noncomputable def esph (n₁ n₂ n₃ : ℝ) : W := ![1 / 2, n₁ / 2, n₂ / 2, n₃ / 2, 0, 0, 0, 0]

@[simp] theorem esph_coord_0 (n₁ n₂ n₃ : ℝ) : esph n₁ n₂ n₃ 0 = 1 / 2 := rfl
@[simp] theorem esph_coord_1 (n₁ n₂ n₃ : ℝ) : esph n₁ n₂ n₃ 1 = n₁ / 2 := rfl
@[simp] theorem esph_coord_2 (n₁ n₂ n₃ : ℝ) : esph n₁ n₂ n₃ 2 = n₂ / 2 := rfl
@[simp] theorem esph_coord_3 (n₁ n₂ n₃ : ℝ) : esph n₁ n₂ n₃ 3 = n₃ / 2 := rfl
@[simp] theorem esph_coord_4 (n₁ n₂ n₃ : ℝ) : esph n₁ n₂ n₃ 4 = 0 := rfl
@[simp] theorem esph_coord_5 (n₁ n₂ n₃ : ℝ) : esph n₁ n₂ n₃ 5 = 0 := rfl
@[simp] theorem esph_coord_6 (n₁ n₂ n₃ : ℝ) : esph n₁ n₂ n₃ 6 = 0 := rfl
@[simp] theorem esph_coord_7 (n₁ n₂ n₃ : ℝ) : esph n₁ n₂ n₃ 7 = 0 := rfl

theorem esph_selfProduct {n₁ n₂ n₃ : ℝ} (h : n₁ ^ 2 + n₂ ^ 2 + n₃ ^ 2 = 1) :
    IsSelfProduct (esph n₁ n₂ n₃) := by
  show esph n₁ n₂ n₃ ⋆ esph n₁ n₂ n₃ = esph n₁ n₂ n₃
  funext i
  fin_cases i <;> simp <;> linarith [h]

theorem esph_ne_zero (n₁ n₂ n₃ : ℝ) : esph n₁ n₂ n₃ ≠ 0 := by
  intro hz
  have : esph n₁ n₂ n₃ 0 = (0 : W) 0 := by rw [hz]
  simp at this

theorem esph_isNullElt {n₁ n₂ n₃ : ℝ} (h : n₁ ^ 2 + n₂ ^ 2 + n₃ ^ 2 = 1) :
    IsNullElt (esph n₁ n₂ n₃) := by
  constructor
  · show nRe (esph n₁ n₂ n₃) = 0
    simp only [nRe, esph_coord_0, esph_coord_1, esph_coord_2, esph_coord_3, esph_coord_4,
      esph_coord_5, esph_coord_6, esph_coord_7]
    linear_combination (-(1 : ℝ) / 4) * h
  · show nSc (esph n₁ n₂ n₃) = 0
    simp [nSc]

theorem isMinimal_Lgen_esph {n₁ n₂ n₃ : ℝ} (h : n₁ ^ 2 + n₂ ^ 2 + n₃ ^ 2 = 1) :
    IsMinimalLeftCarrier (Lgen (esph n₁ n₂ n₃)) :=
  (isMinimal_Lgen_iff _).2 ⟨esph_ne_zero n₁ n₂ n₃, esph_isNullElt h⟩

/-- **DERIVED.**  Distinct points of the two-sphere give distinct minimal carriers. -/
theorem Lgen_esph_inj {n₁ n₂ n₃ m₁ m₂ m₃ : ℝ} (hn : n₁ ^ 2 + n₂ ^ 2 + n₃ ^ 2 = 1)
    (h : Lgen (esph n₁ n₂ n₃) = Lgen (esph m₁ m₂ m₃)) :
    n₁ = m₁ ∧ n₂ = m₂ ∧ n₃ = m₃ := by
  have hmem : esph m₁ m₂ m₃ ∈ Lgen (esph n₁ n₂ n₃) := by
    rw [h]; exact self_mem_Lgen _
  obtain ⟨x, hx⟩ := (mem_Lgen_iff _ _).1 hmem
  have hprod : esph m₁ m₂ m₃ ⋆ esph n₁ n₂ n₃ = esph m₁ m₂ m₃ := by
    rw [← hx, mul_assoc_W, esph_selfProduct hn]
  have h1 := congrArg (fun y : W => y 1) hprod
  have h2 := congrArg (fun y : W => y 2) hprod
  have h3 := congrArg (fun y : W => y 3) hprod
  simp at h1 h2 h3
  exact ⟨by linarith, by linarith, by linarith⟩

/-! ## The action of the automorphism family on the two-sphere of carriers -/

/-- **DERIVED (§27).**  On the explicit family the automorphism acts by rotating the two
non-axial parameters and fixing the axial one. -/
theorem Phi_esph (θ n₁ n₂ n₃ : ℝ) :
    Phi θ (esph n₁ n₂ n₃)
      = esph n₁ (Real.cos θ * n₂ - Real.sin θ * n₃) (Real.sin θ * n₂ + Real.cos θ * n₃) := by
  funext i
  fin_cases i <;> simp [Phi, PhiFun, esph] <;> ring

/-- **DERIVED (§27), AXIS-DEPENDENT.**  The two axial carriers are fixed by the whole
automorphism family. -/
theorem Phi_map_Lgen_esph_axial (θ s : ℝ) :
    Submodule.map (Phi θ) (Lgen (esph s 0 0)) = Lgen (esph s 0 0) := by
  rw [Phi_map_Lgen, Phi_esph]
  norm_num

/-- **DERIVED (§27).**  A carrier of the equatorial circle is moved by the automorphism:
its image is the carrier of the rotated point. -/
theorem Phi_map_Lgen_esph_equator (θ φ : ℝ) :
    Submodule.map (Phi θ) (Lgen (esph 0 (Real.cos φ) (Real.sin φ)))
      = Lgen (esph 0 (Real.cos (θ + φ)) (Real.sin (θ + φ))) := by
  rw [Phi_map_Lgen, Phi_esph, Real.cos_add, Real.sin_add]

/-- **PRINCIPAL THEOREM (§27).**  The action of the automorphism family on the family of
minimal left carriers is *not* trivial: minimal carriers move.  Concretely, the quarter
rotation moves the minimal carrier of the equatorial point `(0,1,0)`. -/
theorem Phi_moves_some_minimal_carrier :
    Submodule.map (Phi (Real.pi / 2)) (Lgen (esph 0 1 0)) ≠ Lgen (esph 0 1 0) := by
  intro hcon
  rw [Phi_map_Lgen, Phi_esph, Real.cos_pi_div_two, Real.sin_pi_div_two] at hcon
  have harg : (0 : ℝ) * 1 - 1 * 0 = 0 := by norm_num
  have harg' : (1 : ℝ) * 1 + 0 * 0 = 1 := by norm_num
  rw [harg, harg'] at hcon
  obtain ⟨-, h2, -⟩ := Lgen_esph_inj (n₁ := 0) (n₂ := 0) (n₃ := 1) (by norm_num) hcon
  norm_num at h2

/-- **PRINCIPAL SUMMARY (§27).**  The automorphism family permutes the minimal left
carriers; it fixes the two axial ones for every parameter value; and it does not fix all
of them. -/
theorem Phi_carrier_family_action :
    (∀ (θ : ℝ) (L : Submodule ℝ W), IsMinimalLeftCarrier L →
        IsMinimalLeftCarrier (Submodule.map (Phi θ) L)) ∧
    (∀ θ : ℝ, Submodule.map (Phi θ) (Lgen (esph 1 0 0)) = Lgen (esph 1 0 0)) ∧
    (∀ θ : ℝ, Submodule.map (Phi θ) (Lgen (esph (-1) 0 0)) = Lgen (esph (-1) 0 0)) ∧
    Submodule.map (Phi (Real.pi / 2)) (Lgen (esph 0 1 0)) ≠ Lgen (esph 0 1 0) :=
  ⟨fun θ _ hL => isMinimal_map_Phi hL θ,
    fun θ => Phi_map_Lgen_esph_axial θ 1,
    fun θ => Phi_map_Lgen_esph_axial θ (-1),
    Phi_moves_some_minimal_carrier⟩

/-! ## Axis-dependence audit (§28, §29) -/

/-- **AXIS-INDEPENDENT (§29).**  Existence of proper nonzero left carriers, the exact
minimal dimension, the minimal-generator criterion and the infinitude of the family of
minimal carriers are all statements about the global algebra alone: the distinguished
axis occurs in none of them. -/
theorem axis_independent_core :
    (∃ L : Submodule ℝ W, IsNonzeroLeftCarrier L ∧ L ≠ ⊤) ∧
    (∀ L : Submodule ℝ W, IsMinimalLeftCarrier L → Module.finrank ℝ L = 4) ∧
    (∀ ψ : W, IsMinimalLeftCarrier (Lgen ψ) ↔ (ψ ≠ 0 ∧ IsNullElt ψ)) ∧
    {L : Submodule ℝ W | IsMinimalLeftCarrier L}.Infinite :=
  ⟨exists_proper_nonzero_leftCarrier, fun _ hL => finrank_of_isMinimal hL,
    isMinimal_Lgen_iff, minimal_carriers_infinite⟩

/-- **AXIS-DEPENDENT (§28, §29).**  What the distinguished axis contributes is not the
existence or the dimension of minimal carriers, but a *selection* inside the already
existing family: the two carriers generated by `(w1 ± wA)/2` are exactly the ones this
module exhibits as fixed by the whole automorphism family, and their generators are the
axial points of the explicit two-sphere. -/
theorem axis_dependent_selection :
    esph 1 0 0 = (2⁻¹ : ℝ) • (w1 + wA) ∧ esph (-1) 0 0 = (2⁻¹ : ℝ) • (w1 - wA) ∧
    (∀ θ : ℝ, Submodule.map (Phi θ) (Lgen (esph 1 0 0)) = Lgen (esph 1 0 0)) ∧
    (∀ θ : ℝ, Submodule.map (Phi θ) (Lgen (esph (-1) 0 0)) = Lgen (esph (-1) 0 0)) := by
  refine ⟨?_, ?_, fun θ => Phi_map_Lgen_esph_axial θ 1,
    fun θ => Phi_map_Lgen_esph_axial θ (-1)⟩
  · funext i; fin_cases i <;> norm_num [esph, w1, wA]
  · funext i; fin_cases i <;> norm_num [esph, w1, wA]

end NullSectorTask12
