import RequestProject.Experiment2.NullSectorTask12.MinimalCarrier

/-!
# Task 12, Layer 5: the family of minimal carriers (§17–§20)

* **Self-product generators.**  Every minimal left carrier is generated by a self-product
  element with unit coordinate `1/2` and vanishing central coordinate.
* **FAMILY.**  There are infinitely many *distinct* minimal left carriers: an explicit
  one-parameter family `Lgen (emin u)`, `u : ℝ`, of pairwise different carriers is
  constructed from the global algebra alone (AXIS-INDEPENDENT — the distinguished axis is
  not used).
* **EQUIVALENT.**  Any two minimal left carriers are related by an *invertible right
  transformation* in the following intrinsic sense (§19): there is an `r : W` such that
  right multiplication by `r` restricts to a bijection of the first carrier onto the
  second.  Such a map automatically commutes with every left multiplication, and the
  relation is reflexive, symmetric and transitive on minimal carriers.
* **Verdict for §20: `FAMILY OF EQUIVALENT CARRIERS`.**  The inherited structure of the
  global algebra does *not* select a unique minimal left carrier.
-/

namespace NullSectorTask12

open NullSectorTask08 NullSectorTask09

/-! ## Self-product generators of minimal carriers -/

/-- **DERIVED.**  Every minimal left carrier is generated by a self-product element with
unit coordinate `1/2`. -/
theorem isMinimal_eq_Lgen_selfProduct {L : Submodule ℝ W} (hL : IsMinimalLeftCarrier L) :
    ∃ e : W, IsSelfProduct e ∧ e ≠ 0 ∧ IsNullElt e ∧ e 0 = 1 / 2 ∧ e 7 = 0
      ∧ L = Lgen e := by
  obtain ⟨ψ, hψ, hnull, rfl⟩ := isMinimal_eq_Lgen hL
  obtain ⟨e, hemem, heidem, hene, henull, he0, he7⟩ := exists_selfProduct_generator hψ hnull
  refine ⟨e, heidem, hene, henull, he0, he7, ?_⟩
  have hle : Lgen e ≤ Lgen ψ := Lgen_le (isLeftCarrier_Lgen ψ) hemem
  have h1 : Module.finrank ℝ (Lgen e) = 4 := finrank_Lgen_eq_four hene henull
  have h2 : Module.finrank ℝ (Lgen ψ) = 4 := finrank_Lgen_eq_four hψ hnull
  exact (Submodule.eq_of_le_of_finrank_eq hle (by rw [h1, h2])).symm

/-! ## An explicit infinite family of minimal carriers -/

/-- An explicit one-parameter family of self-product elements, built from the global
algebra only.  No distinguished direction is used. -/
noncomputable def emin (u : ℝ) : W :=
  ![1 / 2, 0, (1 - u ^ 2) / (2 * (1 + u ^ 2)), u / (1 + u ^ 2), 0, 0, 0, 0]

theorem one_add_sq_ne_zero (u : ℝ) : (1 : ℝ) + u ^ 2 ≠ 0 := by positivity

@[simp] theorem emin_coord_0 (u : ℝ) : emin u 0 = 1 / 2 := rfl
@[simp] theorem emin_coord_1 (u : ℝ) : emin u 1 = 0 := rfl
@[simp] theorem emin_coord_2 (u : ℝ) : emin u 2 = (1 - u ^ 2) / (2 * (1 + u ^ 2)) := rfl
@[simp] theorem emin_coord_3 (u : ℝ) : emin u 3 = u / (1 + u ^ 2) := rfl
@[simp] theorem emin_coord_4 (u : ℝ) : emin u 4 = 0 := rfl
@[simp] theorem emin_coord_5 (u : ℝ) : emin u 5 = 0 := rfl
@[simp] theorem emin_coord_6 (u : ℝ) : emin u 6 = 0 := rfl
@[simp] theorem emin_coord_7 (u : ℝ) : emin u 7 = 0 := rfl

theorem emin_selfProduct (u : ℝ) : IsSelfProduct (emin u) := by
  have h : (1 : ℝ) + u ^ 2 ≠ 0 := one_add_sq_ne_zero u
  show emin u ⋆ emin u = emin u
  funext i
  fin_cases i <;> simp <;> field_simp <;> ring

theorem emin_ne_zero (u : ℝ) : emin u ≠ 0 := by
  intro hz
  have : emin u 0 = (0 : W) 0 := by rw [hz]
  simp at this

theorem emin_isNullElt (u : ℝ) : IsNullElt (emin u) := by
  have h : (1 : ℝ) + u ^ 2 ≠ 0 := one_add_sq_ne_zero u
  constructor
  · show nRe (emin u) = 0
    simp [nRe]
    field_simp
    ring
  · show nSc (emin u) = 0
    simp [nSc]

theorem isMinimal_Lgen_emin (u : ℝ) : IsMinimalLeftCarrier (Lgen (emin u)) :=
  (isMinimal_Lgen_iff (emin u)).2 ⟨emin_ne_zero u, emin_isNullElt u⟩

/-- **DERIVED.**  Different parameters give different minimal carriers. -/
theorem Lgen_emin_injective : Function.Injective (fun u : ℝ => Lgen (emin u)) := by
  intro u v huv
  simp only at huv
  have hmem : emin v ∈ Lgen (emin u) := by rw [huv]; exact self_mem_Lgen _
  obtain ⟨x, hx⟩ := (mem_Lgen_iff _ _).1 hmem
  have hprod : emin v ⋆ emin u = emin v := by
    rw [← hx, mul_assoc_W, emin_selfProduct u]
  have h2 := congrArg (fun y : W => y 2) hprod
  have h3 := congrArg (fun y : W => y 3) hprod
  simp at h2 h3
  have hu : (1 : ℝ) + u ^ 2 ≠ 0 := one_add_sq_ne_zero u
  have hv : (1 : ℝ) + v ^ 2 ≠ 0 := one_add_sq_ne_zero v
  have hsq : u ^ 2 = v ^ 2 := by
    field_simp at h2
    nlinarith [h2]
  field_simp at h3
  have h4 : (1 + u ^ 2) * (u - v) = 0 := by linear_combination h3 + u * hsq
  rcases mul_eq_zero.1 h4 with h | h
  · exact absurd h hu
  · linarith

/-- **PRINCIPAL THEOREM (§17, §18): `FAMILY`.**  There are infinitely many distinct
minimal left carriers. -/
theorem minimal_carriers_infinite :
    {L : Submodule ℝ W | IsMinimalLeftCarrier L}.Infinite :=
  Set.infinite_of_injective_forall_mem Lgen_emin_injective isMinimal_Lgen_emin

/-- **DERIVED.**  In particular the minimal left carrier is not unique. -/
theorem minimal_carrier_not_unique :
    ∃ L L' : Submodule ℝ W, IsMinimalLeftCarrier L ∧ IsMinimalLeftCarrier L' ∧ L ≠ L' := by
  refine ⟨Lgen (emin 0), Lgen (emin 1), isMinimal_Lgen_emin 0, isMinimal_Lgen_emin 1, ?_⟩
  intro h
  have := Lgen_emin_injective h
  norm_num at this

/-! ## Intrinsic equivalence by invertible right transformations (§19) -/

/-- **§19.  NEUTRAL INTRINSIC EQUIVALENCE.**  Two carriers are equivalent when right
multiplication by a single algebra element restricts to a bijection of the first onto the
second.  Such a transformation automatically commutes with every left multiplication;
no conventional notion of representation equivalence is imported. -/
def CarrierEquiv (L L' : Submodule ℝ W) : Prop :=
  ∃ r : W, (∀ ψ ∈ L, ψ ⋆ r ∈ L') ∧ (∀ ψ ∈ L, ∀ φ ∈ L, ψ ⋆ r = φ ⋆ r → ψ = φ)
    ∧ (∀ φ ∈ L', ∃ ψ ∈ L, ψ ⋆ r = φ)

/-- A right transformation commutes with every left multiplication: this is exactly
associativity. -/
theorem carrierEquiv_intertwines (r x ψ : W) : (x ⋆ ψ) ⋆ r = x ⋆ (ψ ⋆ r) :=
  mul_assoc_W x ψ r

theorem carrierEquiv_refl (L : Submodule ℝ W) : CarrierEquiv L L := by
  refine ⟨w1, ?_, ?_, ?_⟩
  · intro ψ hψ; rwa [mul_one_W]
  · rintro ψ - φ - h; rwa [mul_one_W, mul_one_W] at h
  · intro φ hφ; exact ⟨φ, hφ, mul_one_W φ⟩

theorem carrierEquiv_trans {L L' L'' : Submodule ℝ W} (h : CarrierEquiv L L')
    (h' : CarrierEquiv L' L'') : CarrierEquiv L L'' := by
  obtain ⟨r, hmap, hinj, hsurj⟩ := h
  obtain ⟨s, hmap', hinj', hsurj'⟩ := h'
  refine ⟨r ⋆ s, ?_, ?_, ?_⟩
  · intro ψ hψ
    rw [← mul_assoc_W]
    exact hmap' _ (hmap ψ hψ)
  · intro ψ hψ φ hφ heq
    rw [← mul_assoc_W, ← mul_assoc_W] at heq
    exact hinj ψ hψ φ hφ (hinj' _ (hmap ψ hψ) _ (hmap φ hφ) heq)
  · intro χ hχ
    obtain ⟨φ, hφ, rfl⟩ := hsurj' χ hχ
    obtain ⟨ψ, hψ, rfl⟩ := hsurj φ hφ
    exact ⟨ψ, hψ, (mul_assoc_W ψ r s).symm⟩

/-! ## Existence of a nonzero triple product -/

/-- **DERIVED (trace argument).**  For two self-product elements with unit coordinate
`1/2` and vanishing central coordinate there is an element with nonzero triple
product. -/
theorem exists_triple_ne_zero {e f : W} (he0 : e 0 = 1 / 2) (he7 : e 7 = 0)
    (hf0 : f 0 = 1 / 2) (hf7 : f 7 = 0) : ∃ y : W, e ⋆ (y ⋆ f) ≠ 0 := by
  by_contra hcon
  push_neg at hcon
  have hzero : (Lmul e).comp (Rmul f) = 0 := by
    apply LinearMap.ext
    intro y
    simpa using hcon y
  have htr := trace_Lmul_comp_Rmul e f
  rw [hzero, map_zero, he0, he7, hf0, hf7] at htr
  norm_num at htr

/-! ## All minimal carriers are equivalent -/

/-- **PRINCIPAL THEOREM (§18, §19): `EQUIVALENT`.**  Any two minimal left carriers are
related by an invertible right transformation. -/
theorem minimal_carriers_equivalent {L L' : Submodule ℝ W} (hL : IsMinimalLeftCarrier L)
    (hL' : IsMinimalLeftCarrier L') : CarrierEquiv L L' := by
  obtain ⟨e, heidem, -, -, he0, he7, rfl⟩ := isMinimal_eq_Lgen_selfProduct hL
  obtain ⟨f, hfidem, -, -, hf0, hf7, rfl⟩ := isMinimal_eq_Lgen_selfProduct hL'
  obtain ⟨y, hy⟩ := exists_triple_ne_zero he0 he7 hf0 hf7
  set r : W := e ⋆ (y ⋆ f) with hr
  have hmap : ∀ ψ ∈ Lgen e, ψ ⋆ r ∈ Lgen f := by
    intro ψ _
    refine (mem_Lgen_iff _ _).2 ⟨ψ ⋆ (e ⋆ y), ?_⟩
    rw [mul_assoc_W ψ (e ⋆ y) f, mul_assoc_W e y f, hr]
  -- the kernel of the right transformation is a left carrier inside `Lgen e`
  have hker : ∀ ψ ∈ Lgen e, ψ ⋆ r = 0 → ψ = 0 := by
    have hK : IsLeftCarrier (Lgen e ⊓ LinearMap.ker (Rmul r)) := by
      rintro x ψ ⟨hψ1, hψ2⟩
      refine ⟨isLeftCarrier_Lgen e x ψ hψ1, ?_⟩
      have hψ2' : ψ ⋆ r = 0 := LinearMap.mem_ker.1 hψ2
      have hxψ : (x ⋆ ψ) ⋆ r = 0 := by rw [mul_assoc_W x ψ r, hψ2', mul_zero_W]
      exact LinearMap.mem_ker.2 hxψ
    have hne : Lgen e ⊓ LinearMap.ker (Rmul r) ≠ Lgen e := by
      intro hcon
      have hemem : e ∈ Lgen e ⊓ LinearMap.ker (Rmul r) := by
        rw [hcon]; exact self_mem_Lgen e
      have : e ⋆ r = 0 := hemem.2
      rw [hr, ← mul_assoc_W, heidem] at this
      exact hy this
    rcases hL.2 _ hK inf_le_left with hbot | htop
    · intro ψ hψ hzero
      have : ψ ∈ Lgen e ⊓ LinearMap.ker (Rmul r) := ⟨hψ, by simpa using hzero⟩
      rw [hbot] at this
      simpa using this
    · exact absurd htop hne
  refine ⟨r, hmap, ?_, ?_⟩
  · intro ψ hψ φ hφ heq
    have hsub : (ψ - φ) ⋆ r = 0 := by
      have h := map_sub (Rmul r) ψ φ
      simp only [Rmul_apply] at h
      rw [h, heq, sub_self]
    exact sub_eq_zero.1 (hker (ψ - φ) (Submodule.sub_mem _ hψ hφ) hsub)
  · -- the image is a nonzero left carrier inside `Lgen f`
    have himg : IsLeftCarrier (Submodule.map (Rmul r) (Lgen e)) := by
      rintro x φ ⟨ψ, hψ, rfl⟩
      exact ⟨x ⋆ ψ, isLeftCarrier_Lgen e x ψ hψ, by simpa using mul_assoc_W x ψ r⟩
    have hle : Submodule.map (Rmul r) (Lgen e) ≤ Lgen f := by
      rintro φ ⟨ψ, hψ, rfl⟩
      exact hmap ψ hψ
    have hne : Submodule.map (Rmul r) (Lgen e) ≠ ⊥ := by
      intro hcon
      have hmem : r ∈ Submodule.map (Rmul r) (Lgen e) :=
        ⟨e, self_mem_Lgen e, by rw [Rmul_apply, hr, ← mul_assoc_W, heidem]⟩
      rw [hcon] at hmem
      exact hy (by simpa [hr] using hmem)
    rcases hL'.2 _ himg hle with hbot | htop
    · exact absurd hbot hne
    · intro φ hφ
      rw [← htop] at hφ
      obtain ⟨ψ, hψ, hψr⟩ := hφ
      exact ⟨ψ, hψ, hψr⟩

/-- **DERIVED.**  The intrinsic equivalence is symmetric on minimal carriers. -/
theorem carrierEquiv_symm {L L' : Submodule ℝ W} (hL : IsMinimalLeftCarrier L)
    (hL' : IsMinimalLeftCarrier L') (_h : CarrierEquiv L L') : CarrierEquiv L' L :=
  minimal_carriers_equivalent hL' hL

/-- **PRINCIPAL VERDICT (§20): `FAMILY OF EQUIVALENT CARRIERS`.**  Minimal left carriers
exist, there are infinitely many of them, they all have dimension four, they are pairwise
equivalent, and the inherited algebra structure therefore does not select a unique
one. -/
theorem carrier_family_verdict :
    {L : Submodule ℝ W | IsMinimalLeftCarrier L}.Infinite ∧
    (∀ L ∈ {L : Submodule ℝ W | IsMinimalLeftCarrier L}, Module.finrank ℝ L = 4) ∧
    (∀ L ∈ {L : Submodule ℝ W | IsMinimalLeftCarrier L},
      ∀ L' ∈ {L : Submodule ℝ W | IsMinimalLeftCarrier L}, CarrierEquiv L L') :=
  ⟨minimal_carriers_infinite, fun _ hL => finrank_of_isMinimal hL,
    fun _ hL _ hL' => minimal_carriers_equivalent hL hL'⟩


/-! ## Compression by a self-product generator

The *compression* operator `x ↦ e ⋆ x ⋆ e` of a self-product generator is idempotent, so
its rank is its trace, which the inherited trace identity evaluates to `2`.  Since the
central multiples of `e` already form a two-dimensional subspace of the range, the two
agree.  This exact two-dimensionality of `e ⋆ W ⋆ e` is the computational core of the
half-angle intersection, the central-action and the internal-endomorphism layers. -/

/-- The compression operator of `e`. -/
noncomputable def compress (e : W) : W →ₗ[ℝ] W := (Lmul e).comp (Rmul e)

@[simp] theorem compress_apply (e x : W) : compress e x = e ⋆ (x ⋆ e) := rfl

theorem compress_idem {e : W} (he : IsSelfProduct e) (x : W) :
    compress e (compress e x) = compress e x := by
  simp only [compress_apply]
  rw [mul_assoc_W e (x ⋆ e) e, mul_assoc_W x e e, he, ← mul_assoc_W e e (x ⋆ e), he]

/-- **DERIVED (trace).**  The compression of a self-product generator with unit
coordinate `1/2` and vanishing central coordinate has rank exactly two. -/
theorem finrank_range_compress {e : W} (he : IsSelfProduct e) (h0 : e 0 = 1 / 2)
    (h7 : e 7 = 0) : Module.finrank ℝ (LinearMap.range (compress e)) = 2 := by
  have h := finrank_range_of_idem (compress_idem he)
  rw [compress, trace_Lmul_comp_Rmul, h0, h7] at h
  have h2 : ((Module.finrank ℝ (LinearMap.range (compress e)) : ℝ)) = ((2 : ℕ) : ℝ) := by
    rw [compress]; rw [h]; norm_num
  exact_mod_cast h2

/-- The central multiples of `e`. -/
noncomputable def Zspan (e : W) : Submodule ℝ W := Submodule.span ℝ {e, wS ⋆ e}

theorem mem_Zspan_iff (e y : W) : y ∈ Zspan e ↔ ∃ a b : ℝ, a • e + b • (wS ⋆ e) = y :=
  Submodule.mem_span_pair

theorem self_mem_Zspan (e : W) : e ∈ Zspan e :=
  Submodule.subset_span (by simp)

theorem wS_mul_mem_Zspan (e : W) : wS ⋆ e ∈ Zspan e :=
  Submodule.subset_span (by simp)

/-- **DERIVED.**  A nonzero central multiple of a nonzero element is nonzero. -/
theorem central_smul_ne_zero {e : W} (hne : e ≠ 0) {a b : ℝ} (hab : ¬ (a = 0 ∧ b = 0)) :
    a • e + b • (wS ⋆ e) ≠ 0 := by
  intro hzero
  have hz : (a • w1 + b • wS) ⋆ e = 0 := by rw [zsmul_mul]; exact hzero
  have := congrArg (fun y : W => zinv a b ⋆ y) hz
  simp only [mul_zero_W] at this
  rw [← mul_assoc_W, zinv_spec' hab, one_mul_W] at this
  exact hne this

theorem linearIndependent_Zspan {e : W} (hne : e ≠ 0) :
    LinearIndependent ℝ ![e, wS ⋆ e] := by
  rw [LinearIndependent.pair_iff]
  intro s t hst
  by_contra hcon
  exact central_smul_ne_zero hne (by tauto) hst

theorem finrank_Zspan {e : W} (hne : e ≠ 0) : Module.finrank ℝ (Zspan e) = 2 := by
  have hset : Zspan e = Submodule.span ℝ (Set.range ![e, wS ⋆ e]) := by
    rw [Zspan]
    congr 1
    simp only [Matrix.range_cons, Matrix.range_empty, Set.union_empty, Set.union_singleton]
    exact Set.pair_comm _ _
  rw [hset, finrank_span_eq_card (linearIndependent_Zspan hne)]
  simp

/-- **PRINCIPAL LEMMA.**  For a self-product generator with unit coordinate `1/2` and
vanishing central coordinate, the compressed carrier `e ⋆ W ⋆ e` is exactly the plane of
central multiples of `e`. -/
theorem range_compress_eq_Zspan {e : W} (he : IsSelfProduct e) (hne : e ≠ 0)
    (h0 : e 0 = 1 / 2) (h7 : e 7 = 0) :
    LinearMap.range (compress e) = Zspan e := by
  have hle : Zspan e ≤ LinearMap.range (compress e) := by
    rw [Zspan, Submodule.span_le]
    intro y hy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
    rcases hy with hy | hy
    · exact ⟨e, by rw [hy]; simp only [compress_apply]; rw [he, he]⟩
    · refine ⟨wS, ?_⟩
      rw [hy]
      simp only [compress_apply]
      rw [Z_central wS_mem_Z e, ← mul_assoc_W, he, ← Z_central wS_mem_Z e]
  exact (Submodule.eq_of_le_of_finrank_eq hle
    (by rw [finrank_Zspan hne, finrank_range_compress he h0 h7])).symm

/-- **DERIVED.**  Every compression is a central multiple of the generator. -/
theorem compress_mem_Zspan {e : W} (he : IsSelfProduct e) (hne : e ≠ 0) (h0 : e 0 = 1 / 2)
    (h7 : e 7 = 0) (x : W) : e ⋆ (x ⋆ e) ∈ Zspan e := by
  rw [← range_compress_eq_Zspan he hne h0 h7]
  exact ⟨x, rfl⟩

/-- **DERIVED (§17).**  Every proper nonzero left carrier contains a minimal one — indeed
it is itself minimal. -/
theorem proper_contains_minimal {L : Submodule ℝ W} (hL : IsProperLeftCarrier L) :
    ∃ M : Submodule ℝ W, IsMinimalLeftCarrier M ∧ M ≤ L :=
  ⟨L, isMinimal_of_proper hL, le_rfl⟩

end NullSectorTask12
