import RequestProject.Experiment2.NullSectorTask12.GeneratedCarrier

/-!
# Task 12, Layer 3: the exact dimensions of generated carriers (§13)

Three facts are combined.

1. If the generator is invertible, the generated carrier is everything (dimension `8`).
2. If the generator is nonzero with vanishing central quadratic datum, then
   * the carrier contains the generated carrier of a *derived* self-product element,
     whose dimension is computed by the trace identity to be exactly `4`;
   * the whole carrier consists of elements with vanishing quadratic datum, and a real
     subspace on which the real coefficient `nRe` vanishes identically has dimension at
     most `4` (an isotropy bound proved by an explicit coordinate projection).
3. Hence the only possible dimensions of a generated carrier of a nonzero element are
   `4` and `8`, and both occur.

Status: DERIVED.  AXIS-INDEPENDENT.
-/

namespace NullSectorTask12

open NullSectorTask08 NullSectorTask09

/-! ## The dimension of a carrier generated by a self-product element -/

theorem Rmul_selfProduct_idem {e : W} (he : IsSelfProduct e) (x : W) :
    Rmul e (Rmul e x) = Rmul e x := by
  show (x ⋆ e) ⋆ e = x ⋆ e
  rw [mul_assoc_W, he]

/-- **DERIVED.**  The exact dimension of a carrier generated by a self-product element:
eight times its unit coordinate. -/
theorem finrank_Lgen_selfProduct {e : W} (he : IsSelfProduct e) :
    (Module.finrank ℝ (Lgen e) : ℝ) = 8 * e 0 := by
  rw [Lgen, finrank_range_of_idem (Rmul_selfProduct_idem he), trace_Rmul]

theorem finrank_Lgen_selfProduct_half {e : W} (he : IsSelfProduct e) (h0 : e 0 = 1 / 2) :
    Module.finrank ℝ (Lgen e) = 4 := by
  have h := finrank_Lgen_selfProduct he
  rw [h0] at h
  have h4 : (Module.finrank ℝ (Lgen e) : ℝ) = (4 : ℝ) := by rw [h]; norm_num
  exact_mod_cast h4

/-! ## The isotropy bound -/

/-- The coordinate projection onto the four coordinates on which `nRe` is positive. -/
def proj4 : W →ₗ[ℝ] (Fin 4 → ℝ) where
  toFun y := ![y 0, y 4, y 5, y 6]
  map_add' := by intro x y; funext i; fin_cases i <;> simp
  map_smul' := by intro c x; funext i; fin_cases i <;> simp

/-- **DERIVED (isotropy bound).**  A real subspace on which the real coefficient of the
inherited central quadratic datum vanishes identically has dimension at most four. -/
theorem finrank_le_four_of_nRe_zero (L : Submodule ℝ W) (h : ∀ y ∈ L, nRe y = 0) :
    Module.finrank ℝ L ≤ 4 := by
  set q : L →ₗ[ℝ] (Fin 4 → ℝ) := proj4.comp L.subtype with hq
  have hker : LinearMap.ker q = ⊥ := by
    rw [LinearMap.ker_eq_bot']
    rintro ⟨y, hy⟩ hzero
    have h0 : y 0 = 0 := congrArg (fun v : Fin 4 → ℝ => v 0) hzero
    have h4 : y 4 = 0 := congrArg (fun v : Fin 4 → ℝ => v 1) hzero
    have h5 : y 5 = 0 := congrArg (fun v : Fin 4 → ℝ => v 2) hzero
    have h6 : y 6 = 0 := congrArg (fun v : Fin 4 → ℝ => v 3) hzero
    have hn := h y hy
    rw [nRe, h0, h4, h5, h6] at hn
    have hy0 : y = 0 := by
      refine eq_zero_of_coords h0 ?_ ?_ ?_ h4 h5 h6 ?_ <;>
        nlinarith [sq_nonneg (y 1), sq_nonneg (y 2), sq_nonneg (y 3), sq_nonneg (y 7)]
    exact Subtype.ext hy0
  have hsum := LinearMap.finrank_range_add_finrank_ker q
  rw [hker, finrank_bot, add_zero] at hsum
  have hle : Module.finrank ℝ (LinearMap.range q) ≤ 4 := by
    have h := Submodule.finrank_le (LinearMap.range q)
    simp at h
    exact h
  omega

/-! ## Every element of a null generated carrier is null -/

theorem isNullElt_of_mem_Lgen {ψ : W} (hnull : IsNullElt ψ) {y : W} (hy : y ∈ Lgen ψ) :
    IsNullElt y := by
  obtain ⟨x, rfl⟩ := (mem_Lgen_iff ψ y).1 hy
  exact null_mul hnull

/-! ## The two possible dimensions -/

/-- **PRINCIPAL THEOREM (§13), part 1.**  A carrier generated by a nonzero element with
vanishing central quadratic datum has dimension exactly four. -/
theorem finrank_Lgen_eq_four {ψ : W} (hψ : ψ ≠ 0) (hnull : IsNullElt ψ) :
    Module.finrank ℝ (Lgen ψ) = 4 := by
  obtain ⟨e, hemem, heidem, hene, henull, he0, -⟩ := exists_selfProduct_generator hψ hnull
  have hle : Lgen e ≤ Lgen ψ := Lgen_le (isLeftCarrier_Lgen ψ) hemem
  have h4 : Module.finrank ℝ (Lgen e) = 4 := finrank_Lgen_selfProduct_half heidem he0
  have hge : 4 ≤ Module.finrank ℝ (Lgen ψ) := by
    rw [← h4]; exact Submodule.finrank_mono hle
  have hub : Module.finrank ℝ (Lgen ψ) ≤ 4 :=
    finrank_le_four_of_nRe_zero _ (fun y hy => (isNullElt_of_mem_Lgen hnull hy).1)
  omega

/-- **PRINCIPAL THEOREM (§13), part 2.**  A carrier generated by an invertible element is
the whole carrier, of dimension eight. -/
theorem finrank_Lgen_eq_eight {ψ : W} (hψ : ¬ IsNullElt ψ) :
    Module.finrank ℝ (Lgen ψ) = 8 := by
  rw [Lgen_eq_top_of_hasInverse ((hasInverse_iff ψ).2 hψ)]
  simp

/-- **PRINCIPAL THEOREM (§13).**  The dimension of the carrier generated by a nonzero
element is `4` or `8`, and which of the two occurs is decided exactly by the vanishing of
the inherited central quadratic datum. -/
theorem generated_carrier_dimension (ψ : W) (hψ : ψ ≠ 0) :
    (IsNullElt ψ ∧ Module.finrank ℝ (Lgen ψ) = 4) ∨
      (¬ IsNullElt ψ ∧ Module.finrank ℝ (Lgen ψ) = 8) := by
  by_cases h : IsNullElt ψ
  · exact Or.inl ⟨h, finrank_Lgen_eq_four hψ h⟩
  · exact Or.inr ⟨h, finrank_Lgen_eq_eight h⟩

/-! ## Both dimensions occur -/

/-- **DERIVED.**  Properties of the half-sum of the unit with any square root of the
unit that has vanishing unit coordinate.  No distinguished direction is used: the
statement holds for every such square root. -/
theorem halfSum_props {m : W} (hm : m ⋆ m = w1) (hm0 : m 0 = 0) :
    IsSelfProduct (halfSum m) ∧ halfSum m ≠ 0 ∧ IsNullElt (halfSum m)
      ∧ halfSum m 0 = 1 / 2 := by
  have hidem := halfSum_selfProduct hm
  have hc0 : halfSum m 0 = 1 / 2 := by rw [halfSum_coord_0, hm0]; norm_num
  have hne : halfSum m ≠ 0 := by
    intro h
    rw [h] at hc0
    norm_num at hc0
  refine ⟨hidem, hne, ?_, hc0⟩
  rcases selfProduct_dichotomy hidem with h | h
  · exact h
  · exfalso
    rw [h] at hc0
    norm_num [w1] at hc0

/-- **PRINCIPAL THEOREM (§13), exact dimension set.**  The set of dimensions of carriers
generated by nonzero elements is exactly `{4, 8}`. -/
theorem possible_generated_dimensions :
    {n : ℕ | ∃ ψ : W, ψ ≠ 0 ∧ Module.finrank ℝ (Lgen ψ) = n} = {4, 8} := by
  ext n
  simp only [Set.mem_setOf_eq, Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · rintro ⟨ψ, hψ, rfl⟩
    rcases generated_carrier_dimension ψ hψ with ⟨-, h⟩ | ⟨-, h⟩
    · exact Or.inl h
    · exact Or.inr h
  · rintro (rfl | rfl)
    · obtain ⟨-, hne, hnull, -⟩ := halfSum_props wit8_wB_wB (by simp [wB])
      exact ⟨halfSum wB, hne, finrank_Lgen_eq_four hne hnull⟩
    · refine ⟨w1, ?_, finrank_Lgen_eq_eight ?_⟩
      · intro h
        have : (w1 : W) 0 = (0 : W) 0 := by rw [h]
        simp [w1] at this
      · rw [isNullElt_iff_Ncand, Ncand_one_w1]
        intro h
        have : (w1 : W) 0 = (0 : W) 0 := by rw [h]
        simp [w1] at this

end NullSectorTask12
