import Mathlib
import RequestProject.Spine.E1.SpinCover

/-!
# Spine / E1 : the kernel of the intrinsic spin cover is exactly `{±1}`

This module closes the intrinsic double cover.  With
`SpinCore.spinCover : SpinGroup →* GLor` of `RequestProject.Spine.E1.SpinCover` it proves,
in increasing strength:

* `SpinCore.mem_ker_spinCover_iff` — `u ∈ ker spinCover ↔ u = 1 ∨ u = -1`;
* `SpinCore.spinCover_ker_eq_zpowers` — `ker spinCover = ⟪-1⟫`, the subgroup generated by the
  nontrivial central element `-1`;
* `SpinCore.spinCover_ker_card` — the kernel has exactly two elements
  (`SpinCore.negOneSpin ≠ 1`, so the cover is genuinely two-to-one);
* `SpinCore.spinCover_ker_central` — the kernel is central in the spin group, in the
  pointwise form required by a central-cover interface;
* **`SpinCore.spin_double_cover`** — the bundled statement: `spinCover` is a surjective
  homomorphism `SpinGroup →* GLor` with central kernel exactly `{±1}`.

**Import firewall.**  `Mathlib` plus the intrinsic experiment-1 Clifford/spin layer only.
No `SL(2,ℂ)`, no complex matrix model, no Hermitian data, no historical experiment module,
no topology or lift layer.

**Provenance.**  The exact-kernel content is `SpinCore.kernel_exactly_pm_one`
(`RequestProject.Spine.E1.Paravector`, unchanged) transported to the bundled group; the
bundled statement `SpinCore.spinCover_kernel` of
`RequestProject.Spine.E1.SL2Comparison` is reconstructed here as
`SpinCore.mem_ker_spinCover_iff` (same content, phrased with `MonoidHom.ker` and with the
`±1` alternative read in the group of units rather than in `Cl₃(ℝ)`).  The subgroup,
cardinality, centrality and `ℤ/2` statements are new packaging of the same fact.
-/

noncomputable section

open CliffordAlgebra

namespace SpinCore

/-- Membership in the kernel of the spin cover, unbundled. -/
theorem mem_ker_spinCover_iff' (u : SpinGroup) :
    u ∈ spinCover.ker ↔ ((u : Cl3ˣ) : Cl3) = 1 ∨ ((u : Cl3ˣ) : Cl3) = -1 := by
  rw [MonoidHom.mem_ker, ← kernel_exactly_pm_one u.2]
  constructor
  · intro h x
    have := congrArg (fun F : GLor => (F : LorentzCarrier ≃ₗ[ℝ] LorentzCarrier) x) h
    simpa using this
  · intro h
    refine Subtype.ext (LinearEquiv.ext fun x => ?_)
    simpa using h x

/-- **The exact kernel.**  An element of the intrinsic spin group acts trivially on the
Lorentz carrier exactly when it is `±1`. -/
theorem mem_ker_spinCover_iff (u : SpinGroup) :
    u ∈ spinCover.ker ↔ u = 1 ∨ u = negOneSpin := by
  rw [mem_ker_spinCover_iff']
  constructor
  · rintro (h | h)
    · exact Or.inl (Subtype.ext (Units.ext (by simpa using h)))
    · exact Or.inr (Subtype.ext (Units.ext (by simpa using h)))
  · rintro (rfl | rfl)
    · exact Or.inl rfl
    · exact Or.inr negOneSpin_coe

/-- **The exact kernel, as a subgroup.**  `ker spinCover` is the subgroup generated by the
central element `-1`. -/
theorem spinCover_ker_eq_zpowers : spinCover.ker = Subgroup.zpowers negOneSpin := by
  refine le_antisymm (fun u hu => ?_) ?_
  · rcases (mem_ker_spinCover_iff u).1 hu with rfl | rfl
    · exact one_mem _
    · exact Subgroup.mem_zpowers _
  · rw [Subgroup.zpowers_le]
    exact (mem_ker_spinCover_iff negOneSpin).2 (Or.inr rfl)

/-- The kernel is central in the spin group: every kernel element commutes with every
element.  This is the algebraic input a central-cover interface asks for. -/
theorem spinCover_ker_central (z : SpinGroup) (hz : z ∈ spinCover.ker) (u : SpinGroup) :
    z * u = u * z := by
  rcases (mem_ker_spinCover_iff z).1 hz with rfl | rfl
  · rw [one_mul, mul_one]
  · exact spinGroup_neg_one_central u

/-- The kernel has exactly two elements: the cover is genuinely two-to-one. -/
theorem spinCover_ker_card : Nat.card (spinCover.ker : Subgroup SpinGroup) = 2 := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  rw [spinCover_ker_eq_zpowers, Nat.card_zpowers]
  exact orderOf_eq_prime negOneSpin_sq negOneSpin_ne_one

/-- **The intrinsic algebraic double cover (bundled).**  The intrinsic spin group of
`Cl₃(ℝ)` maps onto the intrinsic Lorentz group of the carrier by the Clifford action, the
map is a surjective group homomorphism, and its kernel is exactly the central `{±1}`. -/
theorem spin_double_cover :
    Function.Surjective spinCover ∧
    (∀ u : SpinGroup, u ∈ spinCover.ker ↔ u = 1 ∨ u = negOneSpin) ∧
    negOneSpin ≠ 1 ∧
    (∀ z ∈ spinCover.ker, ∀ u : SpinGroup, z * u = u * z) :=
  ⟨spinCover_surjective, mem_ker_spinCover_iff, negOneSpin_ne_one,
    fun z hz u => spinCover_ker_central z hz u⟩

end SpinCore

/-! ## Axiom audit of the intrinsic double cover

Each of the following must report only `propext`, `Classical.choice`, `Quot.sound`. -/

#print axioms SpinCore.spinCover
#print axioms SpinCore.spinCover_surjective
#print axioms SpinCore.mem_ker_spinCover_iff
#print axioms SpinCore.spinCover_ker_eq_zpowers
#print axioms SpinCore.spinCover_ker_central
#print axioms SpinCore.spinCover_ker_card
#print axioms SpinCore.spin_double_cover
