import RequestProject.Experiment2.NullSectorTask08.GeneratedClosure

/-!
# Task 08, Layer 8: minimality and word reduction

Every real-linear subspace of the ambient extension that contains the unit and
the three inherited spatial generators and is closed under the ambient product
already contains all four derived mixed channels, hence the whole derived
eight-dimensional closure.
-/

namespace NullSectorTask08

open NullSectorTask01 NullSectorTask04 NullSectorTask07

variable {E : Type*} [AddCommGroup E] [Module ℝ E] (S : AmbientExt E)

/-- A subspace containing the unit and the three inherited spatial generators
and closed under the ambient product. -/
structure IsGenClosed3 (H : Submodule ℝ E) : Prop where
  one_mem : S.oneE ∈ H
  genA_mem : S.genA ∈ H
  genB_mem : S.genB ∈ H
  genC_mem : genC S ∈ H
  mul_mem : ∀ x ∈ H, ∀ y ∈ H, S.mul x y ∈ H

variable {S}

/-- **MINIMAL (step 1).**  Such a subspace contains the Task-07 channel `P`. -/
theorem genP_mem_of_isGenClosed3 {H : Submodule ℝ E} (hH : IsGenClosed3 S H) :
    S.genP ∈ H :=
  hH.mul_mem _ hH.genA_mem _ hH.genB_mem

/-- **MINIMAL (step 2).**  Such a subspace contains `Q`. -/
theorem genQ_mem_of_isGenClosed3 {H : Submodule ℝ E} (hH : IsGenClosed3 S H) :
    genQ S ∈ H :=
  hH.mul_mem _ hH.genA_mem _ hH.genC_mem

/-- **MINIMAL (step 3).**  Such a subspace contains `R`. -/
theorem genR_mem_of_isGenClosed3 {H : Submodule ℝ E} (hH : IsGenClosed3 S H) :
    genR S ∈ H :=
  hH.mul_mem _ hH.genB_mem _ hH.genC_mem

/-- **MINIMAL (step 4).**  Such a subspace contains `S₃`. -/
theorem genS_mem_of_isGenClosed3 {H : Submodule ℝ E} (hH : IsGenClosed3 S H) :
    genS S ∈ H :=
  hH.mul_mem _ (genP_mem_of_isGenClosed3 hH) _ hH.genC_mem

/-- **MINIMAL.**  Any such subspace contains the entire generated closure. -/
theorem G3_le_of_isGenClosed3 {H : Submodule ℝ E} (hH : IsGenClosed3 S H) :
    G3 S ≤ H := by
  rw [G3, Submodule.span_le]
  rintro x ⟨i, rfl⟩
  fin_cases i
  · exact hH.one_mem
  · exact hH.genA_mem
  · exact hH.genB_mem
  · exact hH.genC_mem
  · exact genP_mem_of_isGenClosed3 hH
  · exact genQ_mem_of_isGenClosed3 hH
  · exact genR_mem_of_isGenClosed3 hH
  · exact genS_mem_of_isGenClosed3 hH

variable (S)

/-- The generated closure is itself product-closed and contains the three
generators. -/
theorem isGenClosed3_G3 : IsGenClosed3 S (G3 S) :=
  ⟨oneE_mem_G3 S, genA_mem_G3 S, genB_mem_G3 S, genC_mem_G3 S,
    fun _ hx _ hy => G3_mul_closed S hx hy⟩

/-- **MINIMALITY THEOREM.**  `G₃` is the smallest product-closed subspace
containing the unit and the three inherited spatial generators. -/
theorem G3_least :
    IsGenClosed3 S (G3 S) ∧ ∀ H : Submodule ℝ E, IsGenClosed3 S H → G3 S ≤ H :=
  ⟨isGenClosed3_G3 S, fun _ hH => G3_le_of_isGenClosed3 hH⟩

/-- **WORD REDUCTION.**  Every element obtainable from `1, A, B, C` by real
linear combinations and finitely many ambient products lies in the span of the
eight derived elements, and every element of that span has an eight-coefficient
normal form.  (The first conjunct is exactly the statement that `G₃` is
contained in every product-closed subspace generated by `1, A, B, C`; the
second is the normal-form theorem.) -/
theorem word_reduction (H : Submodule ℝ E) (hH : IsGenClosed3 S H) :
    G3 S ≤ H ∧ ∀ x ∈ G3 S, ∃ a0 a1 a2 a3 a4 a5 a6 a7 : ℝ,
      x = comb8 S a0 a1 a2 a3 a4 a5 a6 a7 :=
  ⟨G3_le_of_isGenClosed3 hH, fun x hx => (mem_G3_iff S x).1 hx⟩

/-- **STRUCTURAL INCLUSION.**  The Task-07 two-generator closure is a subspace
of the Task-08 three-generator closure. -/
theorem Gsub_le_G3 : S.Gsub ≤ G3 S := by
  rw [AmbientExt.Gsub, Submodule.span_le]
  rintro x ⟨i, rfl⟩
  fin_cases i
  · exact oneE_mem_G3 S
  · exact genA_mem_G3 S
  · exact genB_mem_G3 S
  · exact genP_mem_G3 S

/-- **PROPER INCLUSION.**  The inclusion of the Task-07 closure in the Task-08
closure is strict: the third generator itself is not in the smaller one. -/
theorem Gsub_lt_G3 : S.Gsub < G3 S :=
  lt_of_le_of_ne (Gsub_le_G3 S) (fun h => genC_not_mem_Gsub S (h ▸ genC_mem_G3 S))

end NullSectorTask08
