import RequestProject.Spine.E2.AtlasChange.OrdinaryCoverRefinement

/-!
# Task 32, Package E: ordinary atlas equivalence

**HARD TARGET A, endpoint (items 42–47).**

The relation is *generated by the operations actually reconstructed in Packages B and D* and by
nothing else (item 42):

* ordinary chart change / gauge on a fixed cover — `OrdinaryChartGaugeEquivalent`;
* ordinary cover refinement — `OrdinaryCoverRefinement`;
* passage to a common refinement, which is the composite of two refinement steps together
  with one chart-gauge step, and is therefore *derived* rather than postulated.

Following the stop-on-hard-frontier rule, the relation is a finite zig-zag (generated)
relation on the type `Presentation F` of ordinary atlas presentations of one bare family, and
it is proved to be an equivalence relation (item 44/45).

Item 47 is respected: the relation is **not** "they present the same family" — that is already
forced by the type `Presentation F` — it records *how* the local data are related.
-/

set_option synthInstance.maxHeartbeats 400000
set_option maxHeartbeats 1000000

namespace NullSectorTask32

open NullSectorTask26 NullSectorTask27 NullSectorTask28 NullSectorTask31

universe u v t

section Equivalence

variable {B : Type u} [TopologicalSpace B] {E : B → Type v} [∀ b, NormedAddCommGroup (E b)]
  [∀ b, InnerProductSpace ℝ (E b)]

/-- **PACKAGE E.**  An ordinary atlas presentation of a bare family, with its index type
bundled, so that presentations on different covers can be compared. -/
def Presentation (F : BareMetricOrientedFamily B E) : Type _ :=
  Σ ι : Type t, OrdinaryAtlasPresentation F ι

/-- **PACKAGE E (items 42–43, 45), principal definition.**  The generated (finite zig-zag)
ordinary atlas equivalence: the smallest relation containing ordinary chart gauges and
ordinary cover refinements, closed under symmetry and transitivity. -/
inductive OrdinaryAtlasEquivalent {F : BareMetricOrientedFamily B E} :
    Presentation.{u, v, t} F → Presentation.{u, v, t} F → Prop
  /-- One ordinary chart-gauge step. -/
  | gauge {ι ι' : Type t} (A : OrdinaryAtlasPresentation F ι)
      (A' : OrdinaryAtlasPresentation F ι') (h : OrdinaryChartGaugeEquivalent A A') :
      OrdinaryAtlasEquivalent ⟨ι, A⟩ ⟨ι', A'⟩
  /-- One ordinary cover-refinement step. -/
  | refineStep {ι κ : Type t} (A : OrdinaryAtlasPresentation F ι)
      (R : OrdinaryCoverRefinement A κ) : OrdinaryAtlasEquivalent ⟨ι, A⟩ ⟨κ, R.atlas⟩
  /-- Symmetry of the generated relation. -/
  | symm {P Q : Presentation.{u, v, t} F} : OrdinaryAtlasEquivalent P Q →
      OrdinaryAtlasEquivalent Q P
  /-- Transitivity of the generated relation. -/
  | trans {P Q R : Presentation.{u, v, t} F} : OrdinaryAtlasEquivalent P Q →
      OrdinaryAtlasEquivalent Q R → OrdinaryAtlasEquivalent P R

variable {F : BareMetricOrientedFamily B E}

/-- **PACKAGE E (item 44).**  Reflexivity, from the identity chart gauge. -/
theorem OrdinaryAtlasEquivalent.refl (P : Presentation.{u, v, t} F) :
    OrdinaryAtlasEquivalent P P := by
  obtain ⟨ι, A⟩ := P
  exact OrdinaryAtlasEquivalent.gauge A A (ordinaryChartGaugeEquivalent_refl A)

/-- **PACKAGE E (item 44), REQUIRED ENDPOINT.**  Ordinary atlas equivalence is an equivalence
relation. -/
theorem ordinaryAtlasEquivalent_equivalence :
    Equivalence (@OrdinaryAtlasEquivalent B _ E _ _ F) :=
  ⟨OrdinaryAtlasEquivalent.refl, OrdinaryAtlasEquivalent.symm, OrdinaryAtlasEquivalent.trans⟩

/-- **PACKAGE E.**  A presentation is equivalent to any of its ordinary refinements. -/
theorem ordinaryAtlasEquivalent_refine {ι κ : Type t} (A : OrdinaryAtlasPresentation F ι)
    (R : OrdinaryCoverRefinement A κ) :
    OrdinaryAtlasEquivalent (F := F) ⟨ι, A⟩ ⟨κ, R.atlas⟩ :=
  OrdinaryAtlasEquivalent.refineStep A R

/-- **PACKAGE E (item 42), passage to a common refinement, derived.**  Two presentations whose
chart comparisons are continuous are equivalent through their common ordinary refinement:
refine the first, gauge across on the common cover, and read the result as the refinement of
the second. -/
theorem ordinaryAtlasEquivalent_commonRefinement {ι ι' : Type t}
    (A : OrdinaryAtlasPresentation F ι) (A' : OrdinaryAtlasPresentation F ι')
    (h : OrdinaryChartGaugeEquivalent (commonRefinementLeft A A').atlas
      (commonRefinementRight A A').atlas) :
    OrdinaryAtlasEquivalent (F := F) ⟨ι, A⟩ ⟨ι', A'⟩ :=
  ((OrdinaryAtlasEquivalent.refineStep A (commonRefinementLeft A A')).trans
      (OrdinaryAtlasEquivalent.gauge _ _ h)).trans
    (OrdinaryAtlasEquivalent.refineStep A' (commonRefinementRight A A')).symm

end Equivalence

end NullSectorTask32
