import RequestProject.Spine.AlgebraicTopology.SimplicialChains
import Mathlib.Tactic.LinearCombination
import Mathlib.AlgebraicTopology.DoldKan.HomotopyEquivalence
import Mathlib.Algebra.Category.ModuleCat.Basic
import Mathlib.LinearAlgebra.Quotient.Basic
import Mathlib.Algebra.Homology.HomologicalComplex
import Mathlib.AlgebraicTopology.DoldKan.Decomposition
import Mathlib.AlgebraicTopology.DoldKan.Degeneracies
import Mathlib.AlgebraicTopology.DoldKan.Homotopies

/-!
# Task 13, Objective A : normalization of the project-native simplicial chain complex

The Spine's simplicial `ℤ₂`-chain complex of a simplicial set `S` is the **unnormalized** one,

`C_q^{simp,unn}(S;ℤ₂) = NerveGeom.SSetChain S q = S_q →₀ ℤ₂`,  `∂ = NerveGeom.sSetBoundary`

(unsigned, because `-1 = 1` in `ℤ₂`), and for the cover nerve `K = N(𝓤)` it is *literally* the
Task-9 complex (`NerveGeom.simpBoundary_eq`).  Task 13, Objective A, supplies the missing
degeneracy control:

* `SpineTask13.degenSubmodule S q` — the submodule `D_q(S) ⊆ C_q(S)` generated by the
  degenerate `q`-simplices (`WP3`);
* `SpineTask13.boundary_degen_mem` — `∂ D_{q+1}(S) ⊆ D_q(S)`, so `D_*(S)` is a subcomplex;
* `SpineTask13.NormChain S q = C_q(S) ⧸ D_q(S)` with the induced differential
  `SpineTask13.normBoundary` — the **normalized** complex `N_*(S)` as a quotient (`WP3`);
* `SpineTask13.normProj` / `SpineTask13.normInc` — the projection `p : C_* → N_*` and a
  section `i : N_* → C_*`, with

  - `normProj_comp_normInc` : `p ∘ i = id` **on the nose**,
  - `normInc_comp_normProj` : `i ∘ p = P∞`,
  - `normHtpy_zero`, `normHtpy_succ` : `∂h + h∂ = id + i∘p`,

  i.e. `C_*^{simp,unn}(S;ℤ₂) ≃_ch N_*(S;ℤ₂)`, a **chain-homotopy equivalence** (`WP4`,
  endpoint `NORMALIZATION_CHAIN_EQUIV`);
* `SpineTask13.normProj_natural`, `SpineTask13.normInc_natural` — naturality in `S`, hence
  compatibility with simplicial maps, with subcomplex/skeletal inclusions, and with the
  canonical comparison map `J = C_*(η_K)` (`WP5`, absolute part).

## How it is proved

Nothing here is a parallel normalization theory.  The proof reuses the pinned Dold–Kan
machinery of Mathlib v4.28.0:

| ingredient | pinned declaration |
| --- | --- |
| alternating face map complex | `AlgebraicTopology.alternatingFaceMapComplex` |
| Dold–Kan projector `P∞` | `AlgebraicTopology.DoldKan.PInfty` |
| `P∞` kills degeneracies | `AlgebraicTopology.DoldKan.σ_comp_PInfty` |
| `P∞ + Q∞ = id` | `AlgebraicTopology.DoldKan.PInfty_add_QInfty` |
| `Q` is a sum of terms ending in a degeneracy | `AlgebraicTopology.DoldKan.decomposition_Q` |
| homotopy `P∞ ≃ id` | `AlgebraicTopology.DoldKan.homotopyPInftyToId` |

The bridge to the Spine's hand-built complex is `afmc_d_hom`: over `ℤ₂` the alternating signs
of Mathlib's differential disappear, so Mathlib's differential on `ℤ₂[S]` **is** the Spine's
`sSetBoundary`.  Consequently `P∞`, its homotopy to the identity, and the whole normalization
statement are statements about the *actual* project complex, not about a substitute.
-/

noncomputable section

namespace SpineTask13

open CategoryTheory Opposite Simplicial AlgebraicTopology AlgebraicTopology.DoldKan
open NerveGeom

universe u

/-! ## Characteristic two -/

theorem z2_add_self_gen {M : Type*} [AddCommGroup M] [Module (ZMod 2) M] (x : M) : x + x = 0 := by
  have h2 : (2 : ZMod 2) = 0 := by decide
  rw [← two_smul (ZMod 2), h2, zero_smul]

theorem modCat_hom_add_self {A B : ModuleCat.{u} (ZMod 2)} (f : A ⟶ B) : f + f = 0 := by
  ext x
  show f.hom x + f.hom x = 0
  have h2 : (2 : ZMod 2) = 0 := by decide
  rw [← two_smul (ZMod 2), h2, zero_smul]

theorem modCat_hom_neg {A B : ModuleCat.{u} (ZMod 2)} (f : A ⟶ B) : -f = f := by
  have h := modCat_hom_add_self f
  linear_combination (norm := abel) -h

theorem modCat_hom_zsmul_neg_one_pow {A B : ModuleCat.{u} (ZMod 2)} (f : A ⟶ B) (i : ℕ) :
    ((-1 : ℤ) ^ i) • f = f := by
  rcases Nat.even_or_odd i with h | h
  · rw [h.neg_one_pow, one_smul]
  · rw [h.neg_one_pow, neg_smul, one_smul, modCat_hom_neg]

/-! ## The free `ℤ₂`-simplicial module of a simplicial set -/

/-- The simplicial `ℤ₂`-module `ℤ₂[S]` freely generated by a simplicial set `S`.  Degreewise
it is the Spine's own chain module `NerveGeom.SSetChain`. -/
def freeSSetModule (S : SSet.{u}) : SimplicialObject (ModuleCat.{u} (ZMod 2)) where
  obj n := ModuleCat.of (ZMod 2) (S.obj n →₀ ZMod 2)
  map f := ModuleCat.ofHom (Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.map f))
  map_id n := by ext x; simp [Finsupp.mapDomain]
  map_comp f g := by ext x; simp [Finsupp.lmapDomain]

/-- Degreewise, `ℤ₂[S]` is the project's `SSetChain`. -/
theorem freeSSetModule_obj (S : SSet.{u}) (q : ℕ) :
    (freeSSetModule S).obj (op (SimplexCategory.mk q)) = ModuleCat.of (ZMod 2) (SSetChain S q) :=
  rfl

theorem freeSSetModule_sigma (S : SSet.{u}) {n : ℕ} (i : Fin (n + 1)) :
    (freeSSetModule S).σ i = ModuleCat.ofHom (Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.σ i)) :=
  rfl

theorem freeSSetModule_delta (S : SSet.{u}) {n : ℕ} (i : Fin (n + 2)) :
    (freeSSetModule S).δ i = ModuleCat.ofHom (Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.δ i)) :=
  rfl

/-- The alternating face map complex of `ℤ₂[S]`, in degree `q` the Spine's chain module. -/
theorem afmc_X (S : SSet.{u}) (q : ℕ) :
    (AlternatingFaceMapComplex.obj (freeSSetModule S)).X q
      = ModuleCat.of (ZMod 2) (SSetChain S q) := rfl

/-- **The Spine's unnormalized boundary is Mathlib's alternating face map differential.**
Over `ℤ₂` the alternating signs disappear. -/
theorem afmc_d_hom (S : SSet.{u}) (q : ℕ) :
    ((AlternatingFaceMapComplex.obj (freeSSetModule S)).d (q + 1) q).hom = sSetBoundary S q := by
  have hd : (AlternatingFaceMapComplex.obj (freeSSetModule S)).d (q + 1) q
      = AlternatingFaceMapComplex.objD (freeSSetModule S) q :=
    alternatingFaceMapComplex_obj_d (freeSSetModule S) q
  rw [hd]
  unfold AlternatingFaceMapComplex.objD
  simp only [modCat_hom_zsmul_neg_one_pow]
  rw [sSetBoundary, ModuleCat.hom_sum]
  rfl

/-- `∂ ∘ ∂ = 0` for the Spine's unnormalized complex, inherited from the pinned complex. -/
theorem sSetBoundary_comp_sSetBoundary (S : SSet.{u}) (q : ℕ) :
    (sSetBoundary S q).comp (sSetBoundary S (q + 1)) = 0 := by
  have h := congrArg ModuleCat.Hom.hom
    ((AlternatingFaceMapComplex.obj (freeSSetModule S)).d_comp_d (q + 2) (q + 1) q)
  rw [ModuleCat.hom_comp, afmc_d_hom, afmc_d_hom, ModuleCat.hom_zero] at h
  exact h

/-! ## The Dold–Kan projector, read as a linear map on the Spine's chains -/

/-- `P∞` in degree `q`, as an endomorphism of the Spine's chain module. -/
def proj (S : SSet.{u}) (q : ℕ) : SSetChain S q →ₗ[ZMod 2] SSetChain S q :=
  (PInfty (X := freeSSetModule S)).f q |>.hom

/-- `P∞` is a chain map for the Spine's boundary. -/
theorem proj_comm (S : SSet.{u}) (q : ℕ) :
    (proj S q).comp (sSetBoundary S q) = (sSetBoundary S q).comp (proj S (q + 1)) := by
  have h2 := congrArg ModuleCat.Hom.hom ((PInfty (X := freeSSetModule S)).comm (q + 1) q)
  rw [ModuleCat.hom_comp, ModuleCat.hom_comp, afmc_d_hom] at h2
  exact h2.symm

theorem proj_comm_apply (S : SSet.{u}) (q : ℕ) (x : SSetChain S (q + 1)) :
    proj S q (sSetBoundary S q x) = sSetBoundary S q (proj S (q + 1) x) :=
  congrFun (congrArg DFunLike.coe (proj_comm S q)) x

/-! ## WP3 : the degeneracy subcomplex -/

/-- **WP3.  The degeneracy submodule** `D_q(S) ⊆ C_q^{simp,unn}(S;ℤ₂)`: the submodule
generated by the degenerate `q`-simplices, i.e. the sum of the images of the linearised
degeneracy operators.  In degree `0` there are no degenerate simplices. -/
def degenSubmodule (S : SSet.{u}) : (q : ℕ) → Submodule (ZMod 2) (SSetChain S q)
  | 0 => ⊥
  | (n + 1) => ⨆ i : Fin (n + 1),
      LinearMap.range (Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.σ i))

theorem degenSubmodule_zero (S : SSet.{u}) : degenSubmodule S 0 = ⊥ := rfl

theorem degenSubmodule_succ (S : SSet.{u}) (n : ℕ) :
    degenSubmodule S (n + 1)
      = ⨆ i : Fin (n + 1), LinearMap.range (Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.σ i)) :=
  rfl

theorem mem_degenSubmodule_succ {S : SSet.{u}} {n : ℕ} (i : Fin (n + 1)) (x : SSetChain S n) :
    Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.σ i) x ∈ degenSubmodule S (n + 1) :=
  Submodule.mem_iSup_of_mem i ⟨x, rfl⟩

/-- Every degenerate simplex spans a degenerate chain. -/
theorem single_degen_mem {S : SSet.{u}} {n : ℕ} (i : Fin (n + 1))
    (σ : S.obj (op (SimplexCategory.mk n))) (c : ZMod 2) :
    Finsupp.single (S.σ i σ) c ∈ degenSubmodule S (n + 1) := by
  have h : Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.σ i) (Finsupp.single σ c)
      = Finsupp.single (S.σ i σ) c := by
    simp [Finsupp.lmapDomain, Finsupp.mapDomain_single]
  rw [← h]
  exact mem_degenSubmodule_succ i _

/-- **`P∞` annihilates degenerate chains** (pinned `σ_comp_PInfty`). -/
theorem proj_degen_zero (S : SSet.{u}) (q : ℕ) {x : SSetChain S q}
    (hx : x ∈ degenSubmodule S q) : proj S q x = 0 := by
  cases q with
  | zero =>
      rw [degenSubmodule_zero, Submodule.mem_bot] at hx
      simp [hx]
  | succ n =>
      have hle : degenSubmodule S (n + 1) ≤ LinearMap.ker (proj S (n + 1)) := by
        rw [degenSubmodule_succ]
        refine iSup_le fun i => ?_
        rw [LinearMap.range_le_ker_iff]
        have h2 := congrArg ModuleCat.Hom.hom (σ_comp_PInfty (freeSSetModule S) i)
        rw [ModuleCat.hom_comp] at h2
        simpa using h2
      exact hle hx

/-- `x - P∞ x = Q∞ x`. -/
theorem sub_proj_eq_QInfty (S : SSet.{u}) (q : ℕ) (x : SSetChain S q) :
    x - proj S q x = ((QInfty (X := freeSSetModule S)).f q).hom x := by
  have h' := congrArg (fun (m : AlternatingFaceMapComplex.obj (freeSSetModule S) ⟶
      AlternatingFaceMapComplex.obj (freeSSetModule S)) => ModuleCat.Hom.hom (m.f q) x)
    (PInfty_add_QInfty (X := freeSSetModule S))
  simp only [HomologicalComplex.add_f_apply, HomologicalComplex.id_f, ModuleCat.hom_add,
    LinearMap.add_apply, ModuleCat.hom_id, LinearMap.id_apply] at h'
  exact (eq_sub_of_add_eq' h').symm

/-- **`x - P∞ x` is a degenerate chain** (pinned `decomposition_Q`). -/
theorem sub_proj_mem_degen (S : SSet.{u}) (q : ℕ) (x : SSetChain S q) :
    x - proj S q x ∈ degenSubmodule S q := by
  rw [sub_proj_eq_QInfty]
  cases q with
  | zero =>
      rw [QInfty_f, Q_f_0_eq]
      simp [degenSubmodule_zero]
  | succ n =>
      rw [QInfty_f, decomposition_Q n (n + 1), ModuleCat.hom_sum, LinearMap.sum_apply]
      refine Submodule.sum_mem _ fun i _ => ?_
      rw [ModuleCat.hom_comp, ModuleCat.hom_comp]
      exact mem_degenSubmodule_succ i.rev _

/-- **WP3, principal.  `D_*(S)` is a subcomplex:** `∂ D_{q+1}(S) ⊆ D_q(S)`. -/
theorem boundary_degen_mem (S : SSet.{u}) (q : ℕ) {x : SSetChain S (q + 1)}
    (hx : x ∈ degenSubmodule S (q + 1)) :
    sSetBoundary S q x ∈ degenSubmodule S q := by
  have h0 : proj S q (sSetBoundary S q x) = 0 := by
    rw [proj_comm_apply, proj_degen_zero S (q + 1) hx, map_zero]
  have h := sub_proj_mem_degen S q (sSetBoundary S q x)
  rwa [h0, sub_zero] at h

/-! ## The normalized complex `N_*(S) = C_*(S)/D_*(S)` -/

/-- The normalized chain module `N_q(S) = C_q(S)/D_q(S)`. -/
abbrev NormChain (S : SSet.{u}) (q : ℕ) : Type u :=
  SSetChain S q ⧸ degenSubmodule S q

/-- The normalization projection `p : C_*(S) → N_*(S)`. -/
def normProj (S : SSet.{u}) (q : ℕ) : SSetChain S q →ₗ[ZMod 2] NormChain S q :=
  (degenSubmodule S q).mkQ

@[simp] theorem normProj_apply (S : SSet.{u}) (q : ℕ) (x : SSetChain S q) :
    normProj S q x = Submodule.Quotient.mk x := rfl

theorem normProj_surjective (S : SSet.{u}) (q : ℕ) : Function.Surjective (normProj S q) :=
  Submodule.mkQ_surjective _

/-- The induced boundary on `N_*(S)`. -/
def normBoundary (S : SSet.{u}) (q : ℕ) : NormChain S (q + 1) →ₗ[ZMod 2] NormChain S q :=
  Submodule.mapQ _ _ (sSetBoundary S q) (fun _ hx => boundary_degen_mem S q hx)

/-- `p` is a chain map. -/
theorem normProj_comm (S : SSet.{u}) (q : ℕ) :
    (normProj S q).comp (sSetBoundary S q) = (normBoundary S q).comp (normProj S (q + 1)) :=
  LinearMap.ext fun _ => rfl

/-- The normalized complex is a complex: `∂̄ ∘ ∂̄ = 0`. -/
theorem normBoundary_comp_normBoundary (S : SSet.{u}) (q : ℕ) :
    (normBoundary S q).comp (normBoundary S (q + 1)) = 0 := by
  refine Submodule.linearMap_qext _ (LinearMap.ext fun x => ?_)
  show normBoundary S q (normBoundary S (q + 1) (Submodule.Quotient.mk x)) = 0
  have hstep : normBoundary S q (normBoundary S (q + 1) (Submodule.Quotient.mk x))
      = Submodule.Quotient.mk (sSetBoundary S q (sSetBoundary S (q + 1) x)) := rfl
  rw [hstep,
    show sSetBoundary S q (sSetBoundary S (q + 1) x)
        = ((sSetBoundary S q).comp (sSetBoundary S (q + 1))) x from rfl,
    sSetBoundary_comp_sSetBoundary]
  simp

/-- **The normalization section** `i : N_*(S) → C_*(S)`, induced by `P∞`. -/
def normInc (S : SSet.{u}) (q : ℕ) : NormChain S q →ₗ[ZMod 2] SSetChain S q :=
  (degenSubmodule S q).liftQ (proj S q) (fun _ hx => proj_degen_zero S q hx)

@[simp] theorem normInc_mk (S : SSet.{u}) (q : ℕ) (x : SSetChain S q) :
    normInc S q (Submodule.Quotient.mk x) = proj S q x := rfl

/-- **`i ∘ p = P∞`.** -/
theorem normInc_comp_normProj (S : SSet.{u}) (q : ℕ) :
    (normInc S q).comp (normProj S q) = proj S q :=
  LinearMap.ext fun _ => rfl

/-- **`p ∘ i = id`**: the section is a genuine section, on the nose. -/
theorem normProj_comp_normInc (S : SSet.{u}) (q : ℕ) :
    (normProj S q).comp (normInc S q) = LinearMap.id := by
  refine Submodule.linearMap_qext _ (LinearMap.ext fun x => ?_)
  show normProj S q (proj S q x) = normProj S q x
  rw [← sub_eq_zero, ← map_sub]
  have h : x - proj S q x ∈ degenSubmodule S q := sub_proj_mem_degen S q x
  have : normProj S q (x - proj S q x) = 0 := (Submodule.Quotient.mk_eq_zero _).2 h
  rw [show proj S q x - x = -(x - proj S q x) by abel, map_neg, this, neg_zero]

/-- `i` is a chain map. -/
theorem normInc_comm (S : SSet.{u}) (q : ℕ) :
    (normInc S q).comp (normBoundary S q) = (sSetBoundary S q).comp (normInc S (q + 1)) := by
  refine Submodule.linearMap_qext _ (LinearMap.ext fun x => ?_)
  show normInc S q (normBoundary S q (Submodule.Quotient.mk x))
      = sSetBoundary S q (normInc S (q + 1) (Submodule.Quotient.mk x))
  show proj S q (sSetBoundary S q x) = sSetBoundary S q (proj S (q + 1) x)
  exact proj_comm_apply S q x

/-! ## WP4 : the contracting homotopy `id ≃ i ∘ p` -/

/-- The Dold–Kan homotopy between `P∞` and the identity, read as a degree `+1` linear map on
the Spine's chains. -/
def normHtpy (S : SSet.{u}) (q : ℕ) : SSetChain S q →ₗ[ZMod 2] SSetChain S (q + 1) :=
  ((homotopyPInftyToId (freeSSetModule S)).hom q (q + 1)).hom

/-- **WP4, degree `0`:** `∂h₀ = id + i∘p`. -/
theorem normHtpy_zero (S : SSet.{u}) :
    (sSetBoundary S 0).comp (normHtpy S 0) = LinearMap.id + proj S 0 := by
  have h := (homotopyPInftyToId (freeSSetModule S)).comm 0
  rw [Homotopy.dNext_zero_chainComplex, Homotopy.prevD_chainComplex, zero_add] at h
  have h2 := congrArg ModuleCat.Hom.hom h
  rw [ModuleCat.hom_add, ModuleCat.hom_comp, afmc_d_hom, HomologicalComplex.id_f,
    ModuleCat.hom_id] at h2
  have h3 : proj S 0 = (sSetBoundary S 0).comp (normHtpy S 0) + LinearMap.id := h2
  have hz := z2_add_self_gen (LinearMap.id : SSetChain S 0 →ₗ[ZMod 2] SSetChain S 0)
  rw [h3]
  linear_combination (norm := abel) -hz

/-- **WP4, positive degree:** `∂h + h∂ = id + i∘p`. -/
theorem normHtpy_succ (S : SSet.{u}) (q : ℕ) :
    (sSetBoundary S (q + 1)).comp (normHtpy S (q + 1))
        + (normHtpy S q).comp (sSetBoundary S q)
      = LinearMap.id + proj S (q + 1) := by
  have h := (homotopyPInftyToId (freeSSetModule S)).comm (q + 1)
  rw [Homotopy.dNext_succ_chainComplex, Homotopy.prevD_chainComplex] at h
  have h2 := congrArg ModuleCat.Hom.hom h
  rw [ModuleCat.hom_add, ModuleCat.hom_add, ModuleCat.hom_comp, ModuleCat.hom_comp,
    afmc_d_hom, afmc_d_hom, HomologicalComplex.id_f, ModuleCat.hom_id] at h2
  have h3 : proj S (q + 1)
      = (normHtpy S q).comp (sSetBoundary S q)
        + (sSetBoundary S (q + 1)).comp (normHtpy S (q + 1)) + LinearMap.id := h2
  have hz := z2_add_self_gen (LinearMap.id : SSetChain S (q + 1) →ₗ[ZMod 2] SSetChain S (q + 1))
  rw [h3]
  linear_combination (norm := abel) -hz

/-! ## WP5 : naturality of the normalization -/

/-- The linearisation of a simplicial map carries degenerate chains to degenerate chains. -/
theorem sSetChainMap_degen_mem {S T : SSet.{u}} (φ : S ⟶ T) (q : ℕ) {x : SSetChain S q}
    (hx : x ∈ degenSubmodule S q) : sSetChainMap φ q x ∈ degenSubmodule T q := by
  cases q with
  | zero =>
      rw [degenSubmodule_zero, Submodule.mem_bot] at hx
      simp [hx, degenSubmodule_zero]
  | succ n =>
      have hle : degenSubmodule S (n + 1)
          ≤ Submodule.comap (sSetChainMap φ (n + 1)) (degenSubmodule T (n + 1)) := by
        rw [degenSubmodule_succ]
        refine iSup_le fun i => ?_
        rintro _ ⟨y, rfl⟩
        show sSetChainMap φ (n + 1)
          (Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.σ i) y) ∈ degenSubmodule T (n + 1)
        have hcomm : sSetChainMap φ (n + 1) ∘ₗ Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.σ i)
            = Finsupp.lmapDomain (ZMod 2) (ZMod 2) (T.σ i) ∘ₗ sSetChainMap φ n := by
          refine Finsupp.lhom_ext' fun σ => LinearMap.ext_ring ?_
          simp only [LinearMap.comp_apply, Finsupp.lsingle_apply, sSetChainMap_single,
            Finsupp.lmapDomain_apply, Finsupp.mapDomain_single]
          have hnat := congrFun (φ.naturality (SimplexCategory.σ i).op) σ
          simp only [types_comp_apply] at hnat
          exact congrArg (fun z => Finsupp.single z (1 : ZMod 2)) hnat
        rw [show sSetChainMap φ (n + 1) (Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.σ i) y)
            = (sSetChainMap φ (n + 1) ∘ₗ Finsupp.lmapDomain (ZMod 2) (ZMod 2) (S.σ i)) y from rfl,
          hcomm]
        exact mem_degenSubmodule_succ i _
      exact hle hx

/-- The linearisation of a simplicial map, as a morphism of simplicial `ℤ₂`-modules. -/
def freeSSetModuleMap {S T : SSet.{u}} (φ : S ⟶ T) : freeSSetModule S ⟶ freeSSetModule T where
  app n := ModuleCat.ofHom (Finsupp.lmapDomain (ZMod 2) (ZMod 2) (φ.app n))
  naturality {m n} f := by
    ext x
    show Finsupp.mapDomain (φ.app n) (Finsupp.mapDomain (S.map f) x)
        = Finsupp.mapDomain (T.map f) (Finsupp.mapDomain (φ.app m) x)
    rw [← Finsupp.mapDomain_comp, ← Finsupp.mapDomain_comp]
    have hnat : (fun y => φ.app n (S.map f y)) = fun y => T.map f (φ.app m y) := by
      funext y
      have hy := congrFun (φ.naturality f) y
      simp only [types_comp_apply] at hy
      exact hy
    exact congrArg (fun g => Finsupp.mapDomain g x) hnat

/-- The induced map on normalized chains. -/
def normMap {S T : SSet.{u}} (φ : S ⟶ T) (q : ℕ) : NormChain S q →ₗ[ZMod 2] NormChain T q :=
  Submodule.mapQ _ _ (sSetChainMap φ q) (fun _ hx => sSetChainMap_degen_mem φ q hx)

/-- **WP5, naturality of `p`.**  `p` commutes with every simplicial map. -/
theorem normProj_natural {S T : SSet.{u}} (φ : S ⟶ T) (q : ℕ) :
    (normProj T q).comp (sSetChainMap φ q) = (normMap φ q).comp (normProj S q) :=
  LinearMap.ext fun _ => rfl

/-- **WP5, naturality of `i`.**  `i` commutes with every simplicial map (naturality of
`P∞`). -/
theorem normInc_natural {S T : SSet.{u}} (φ : S ⟶ T) (q : ℕ) :
    (normInc T q).comp (normMap φ q) = (sSetChainMap φ q).comp (normInc S q) := by
  refine Submodule.linearMap_qext _ (LinearMap.ext fun x => ?_)
  show normInc T q (normMap φ q (Submodule.Quotient.mk x))
      = sSetChainMap φ q (normInc S q (Submodule.Quotient.mk x))
  show proj T q (sSetChainMap φ q x) = sSetChainMap φ q (proj S q x)
  have hφ : ((freeSSetModuleMap φ).app (op (SimplexCategory.mk q))).hom = sSetChainMap φ q := rfl
  have h := congrArg ModuleCat.Hom.hom (PInfty_f_naturality q (freeSSetModuleMap φ))
  rw [ModuleCat.hom_comp, ModuleCat.hom_comp, hφ] at h
  have h' := congrFun (congrArg DFunLike.coe h) x
  simpa using h'

/-- `∂̄` commutes with the induced maps on normalized chains. -/
theorem normMap_comm {S T : SSet.{u}} (φ : S ⟶ T) (q : ℕ) :
    (normMap φ q).comp (normBoundary S q) = (normBoundary T q).comp (normMap φ (q + 1)) := by
  refine Submodule.linearMap_qext _ (LinearMap.ext fun x => ?_)
  show normMap φ q (normBoundary S q (Submodule.Quotient.mk x))
      = normBoundary T q (normMap φ (q + 1) (Submodule.Quotient.mk x))
  show Submodule.Quotient.mk (sSetChainMap φ q (sSetBoundary S q x))
      = Submodule.Quotient.mk (sSetBoundary T q (sSetChainMap φ (q + 1) x))
  exact congrArg Submodule.Quotient.mk
    (congrFun (congrArg DFunLike.coe (sSetBoundary_naturality φ q)) x)

end SpineTask13
