import RequestProject.Spine.AlgebraicTopology.SingularHomotopy
import RequestProject.Spine.AlgebraicTopology.DiscreteHomology

/-!
# Task 19, WP2 : the kernel of the augmentation on `H₀`

The `r = 1` standard-cell pair, and the base of the sphere induction, need the *kernel* of the
degree-zero augmentation and not only `H₀` itself.  This module supplies:

* `SpineTask19.augH_natural` — the augmentation is natural;
* `SpineTask19.Hred0` — `ker (augH X)`, the reduced `H₀`;
* `SpineTask19.Hred0_eq_bot` — it vanishes for a nonempty path-connected space;
* `SpineTask19.hred0Equiv` — it is a homotopy invariant;
* `SpineTask19.hred0TwoEquiv` — for a two-point space it is `ℤ₂`, generated by the sum of the
  two point classes.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits NerveGeom SpineTask18

universe u

namespace SpineTask19

variable {X Y : TopCat.{u}}

/-! ## Naturality of the augmentation -/

theorem augS_singMap (g : X ⟶ Y) (z : SSetChain (TopCat.toSSet.obj X) 0) :
    augS Y 0 (singMap g 0 z) = augS X 0 z := by
  induction z using lchain_induction with
  | h0 => simp
  | hadd f h hf hh => rw [map_add, map_add, map_add, hf, hh]
  | hsingle σ => rw [singMap_single, augS_single, augS_single]

theorem augH_natural (g : X ⟶ Y) (t : (singCx X).homology 0) :
    augH Y ((HomologicalComplex.homologyMap (singCxMap g) 0).hom t) = augH X t := by
  obtain ⟨z, hz, rfl⟩ := hcls_surjective t
  rw [homologyMap_hcls, augH_hcls, augH_hcls]
  exact augS_singMap g z

/-! ## Reduced `H₀` -/

/-- The reduced degree-zero homology: the kernel of the augmentation. -/
def Hred0 (X : TopCat.{u}) : Submodule (ZMod 2) ((singCx X).homology 0) :=
  LinearMap.ker (augH X)

theorem augH_injective [PathConnectedSpace ↥X] (x₀ : ↥X) : Function.Injective (augH X) :=
  (h0Equiv (X := X) x₀).injective

theorem Hred0_eq_bot [PathConnectedSpace ↥X] (x₀ : ↥X) : Hred0 X = ⊥ :=
  LinearMap.ker_eq_bot'.2 fun t ht => (augH_injective x₀) (by rw [ht, map_zero])

/-- A map out of a nonempty path-connected space is injective on `H₀`. -/
theorem mono_homologyMap_zero (g : X ⟶ Y) [PathConnectedSpace ↥X] (x₀ : ↥X) :
    Mono (HomologicalComplex.homologyMap (singCxMap g) 0) := by
  refine (ModuleCat.mono_iff_injective _).2 fun t s h => ?_
  refine (augH_injective x₀) ?_
  rw [← augH_natural g t, ← augH_natural g s, h]

/-- Transport of a kernel along a linear equivalence compatible with the functionals. -/
def kerCongr {M N : Type*} [AddCommGroup M] [Module (ZMod 2) M] [AddCommGroup N]
    [Module (ZMod 2) N] (e : M ≃ₗ[ZMod 2] N) (f : M →ₗ[ZMod 2] ZMod 2)
    (g : N →ₗ[ZMod 2] ZMod 2) (h : ∀ x, g (e x) = f x) :
    LinearMap.ker f ≃ₗ[ZMod 2] LinearMap.ker g where
  toFun x := ⟨e x.1, by rw [LinearMap.mem_ker, h]; exact x.2⟩
  map_add' x y := Subtype.ext (map_add e x.1 y.1)
  map_smul' c x := Subtype.ext (map_smul e c x.1)
  invFun y := ⟨e.symm y.1, by
    rw [LinearMap.mem_ker, ← h (e.symm y.1), e.apply_symm_apply]
    exact y.2⟩
  left_inv x := Subtype.ext (e.symm_apply_apply x)
  right_inv y := Subtype.ext (e.apply_symm_apply y)

/-- **Reduced `H₀` is a homotopy invariant.** -/
def hred0Equiv (e : ContinuousMap.HomotopyEquiv ↥X ↥Y) : Hred0 X ≃ₗ[ZMod 2] Hred0 Y :=
  kerCongr (singHomologyIsoOfHomotopyEquiv e 0).toLinearEquiv (augH X) (augH Y)
    (fun t => augH_natural (TopCat.ofHom e.toFun) t)

/-! ## Two points -/

section TwoPoint

theorem sum_ptCls_mem (p₀ p₁ : X) : ptCls X p₀ + ptCls X p₁ ∈ Hred0 X := by
  rw [Hred0, LinearMap.mem_ker, map_add, augH_ptCls, augH_ptCls]
  decide

/-- The generator of the reduced `H₀` of a two-point space. -/
def twoRedMap (p₀ p₁ : X) : ZMod 2 →ₗ[ZMod 2] Hred0 X where
  toFun a := ⟨a • (ptCls X p₀ + ptCls X p₁), Submodule.smul_mem _ a (sum_ptCls_mem p₀ p₁)⟩
  map_add' a b := Subtype.ext (add_smul a b _)
  map_smul' c a := Subtype.ext (mul_smul c a _)

theorem twoRedMap_bijective [TotallyDisconnectedSpace ↥X] (p₀ p₁ : X) (hne : p₀ ≠ p₁)
    (hall : ∀ x : X, x = p₀ ∨ x = p₁) : Function.Bijective (twoRedMap p₀ p₁) := by
  constructor
  · intro a b hab
    have h : (a - b) • (ptCls X p₀ + ptCls X p₁) = 0 := by
      have h' : a • (ptCls X p₀ + ptCls X p₁) = b • (ptCls X p₀ + ptCls X p₁) :=
        congrArg Subtype.val hab
      rw [sub_smul, h', sub_self]
    rw [smul_add] at h
    obtain ⟨h1, -⟩ := h0_two_indep p₀ p₁ hne _ _ h
    exact sub_eq_zero.1 h1
  · rintro ⟨t, ht⟩
    obtain ⟨a, b, rfl⟩ := h0_two_spanning p₀ p₁ hne hall t
    have hsum : a + b = 0 := by
      rw [Hred0, LinearMap.mem_ker, map_add, map_smul, map_smul, augH_ptCls, augH_ptCls,
        smul_eq_mul, smul_eq_mul, mul_one, mul_one] at ht
      exact ht
    have key : ∀ a b : ZMod 2, a + b = 0 → b = a := by decide
    have hba := key a b hsum
    refine ⟨a, Subtype.ext ?_⟩
    show a • (ptCls X p₀ + ptCls X p₁) = a • ptCls X p₀ + b • ptCls X p₁
    rw [hba, smul_add]

/-- **WP2.**  The reduced `H₀` of a two-point space is `ℤ₂`. -/
def hred0TwoEquiv [TotallyDisconnectedSpace ↥X] (p₀ p₁ : X) (hne : p₀ ≠ p₁)
    (hall : ∀ x : X, x = p₀ ∨ x = p₁) : Hred0 X ≃ₗ[ZMod 2] ZMod 2 :=
  (LinearEquiv.ofBijective (twoRedMap p₀ p₁) (twoRedMap_bijective p₀ p₁ hne hall)).symm

end TwoPoint

end SpineTask19
