import RequestProject.Spine.AlgebraicTopology.Normalization
import Mathlib.LinearAlgebra.Isomorphisms
import Mathlib.AlgebraicTopology.SimplicialSet.Skeleton

/-!
# Task 13, Objective B : what normalization computes, and the skeletal filtration

Objective A (`RequestProject.Spine.AlgebraicTopology.Normalization`) produced the normalized complex
`N_*(S) = C_*^{simp,unn}(S;ℤ₂)/D_*(S)` and a chain-homotopy equivalence with the project's
unnormalized complex.  This module answers the two remaining *simplicial-side* questions of
Objective B.

## What `D` and `N` are, precisely

* `degenSubmodule_eq_supported` — `D_q(S)` is **exactly** the submodule of chains supported on
  the degenerate `q`-simplices (`SSet.degenerate`, pinned).  Nothing larger, nothing smaller.
* `normChainEquiv` — consequently `N_q(S)` is **freely generated over `ℤ₂` by the
  nondegenerate `q`-simplices**.  This is the generator statement required by WP6, in its
  absolute form.

## The skeletal filtration (WP5/WP6)

Mathlib's `SSet.skeleton n` is the subcomplex generated by the simplices of dimension `< n`,
so the classical `r`-skeleton `K^{(r)}` is `Sk X (r + 1)` here, and the skeletal pair
`K^{(r-1)} ⊆ K^{(r)}` is `skInc X r : Sk X r ⟶ Sk X (r + 1)`.

* `degenerate_of_mem_skeleton` — in dimension `≥ n` every simplex of the `n`-skeleton is
  degenerate;
* `normChain_skeleton_subsingleton` — hence `N_q(K^{(r)}) = 0` for `q > r`;
* `relNormChain_subsingleton_of_lt`, `relNormChain_subsingleton_of_gt` — **`N_q(K^{(r)},
  K^{(r-1)}) = 0` for every `q ≠ r`** (below the top cell the skeletal inclusion is bijective
  on `q`-simplices, above it everything is degenerate);
* `relNormChainEquiv`, `nonDegenerateSkeletonEquiv` — **`N_r(K^{(r)}, K^{(r-1)})` is free on
  the nondegenerate `r`-simplices**, and those are precisely the nondegenerate `r`-simplices
  of `X`.  Note that the relative subcomplex contributes nothing in degree `r`: its normalized
  chains already vanish there.

## The relative normalization comparison (WP5)

`relNormProj` and `relNormInc` are the induced maps between the relative unnormalized and the
relative normalized chains of the skeletal pair, and `relNormProj_comp_relNormInc` proves
`pʳᵉˡ ∘ iʳᵉˡ = id`.  The second half of a relative chain-homotopy equivalence,
`iʳᵉˡ ∘ pʳᵉˡ ≃ id`, is **not** proved: it needs naturality of the pinned homotopy
`AlgebraicTopology.DoldKan.homotopyPInftyToId` in the simplicial object, and the pin provides
naturality only of the pieces `hσ'` it is assembled from.  See
`TASK13_NORMALIZED_SKELETAL_COMPARISON.md`.
-/

noncomputable section

namespace SpineTask13

open CategoryTheory Opposite Simplicial AlgebraicTopology AlgebraicTopology.DoldKan
open NerveGeom

universe u

/-! ## A quotient lemma for free modules -/

section FreeQuotient

variable {α : Type u} (s : Set α) (R : Type) [CommRing R]

theorem ker_lcomapDomain_compl :
    LinearMap.ker (Finsupp.lcomapDomain (R := R) (M := R) (Subtype.val : ↥sᶜ → α)
      Subtype.val_injective) = Finsupp.supported R R s := by
  ext x
  simp only [LinearMap.mem_ker, Finsupp.mem_supported]
  constructor
  · intro h a ha
    by_contra hs
    exact (Finsupp.mem_support_iff.1 ha) (congrFun (congrArg DFunLike.coe h) ⟨a, hs⟩)
  · intro h
    ext ⟨a, ha⟩
    show x a = 0
    by_contra hx
    exact ha (h (Finsupp.mem_support_iff.2 hx))

theorem surjective_lcomapDomain_compl :
    Function.Surjective (Finsupp.lcomapDomain (R := R) (M := R) (Subtype.val : ↥sᶜ → α)
      Subtype.val_injective) := by
  intro y
  refine ⟨Finsupp.mapDomain Subtype.val y, ?_⟩
  ext a
  show Finsupp.mapDomain Subtype.val y a.val = y a
  rw [Finsupp.mapDomain_apply Subtype.val_injective]

/-- The free module on `α` modulo the chains supported on `s` is free on the complement of
`s`. -/
def quotSupportedEquiv :
    ((α →₀ R) ⧸ Finsupp.supported R R s) ≃ₗ[R] (↥sᶜ →₀ R) :=
  (Submodule.quotEquivOfEq _ _ (ker_lcomapDomain_compl s R).symm).trans
    (LinearMap.quotKerEquivOfSurjective _ (surjective_lcomapDomain_compl s R))

end FreeQuotient

/-! ## The degeneracy submodule is the submodule of chains supported on degenerate simplices -/

/-- **WP3/WP6, the precise generator statement.**  `D_q(S)` consists of exactly the chains
supported on the *degenerate* `q`-simplices. -/
theorem degenSubmodule_eq_supported (S : SSet.{u}) (q : ℕ) :
    degenSubmodule S q = Finsupp.supported (ZMod 2) (ZMod 2) (S.degenerate q) := by
  classical
  apply le_antisymm
  · cases q with
    | zero => rw [degenSubmodule_zero]; exact bot_le
    | succ n =>
        rw [degenSubmodule_succ]
        refine iSup_le fun i => ?_
        rintro _ ⟨y, rfl⟩
        refine (Finsupp.mem_supported (ZMod 2) _).2 ?_
        intro a ha
        have ha' := Finsupp.mapDomain_support (f := S.σ i) (s := y) ha
        simp only [Finset.mem_image] at ha'
        obtain ⟨b, _, rfl⟩ := ha'
        exact S.σ_mem_degenerate i b
  · rw [Finsupp.supported_eq_span_single]
    refine Submodule.span_le.2 ?_
    rintro _ ⟨x, hx, rfl⟩
    cases q with
    | zero => simp at hx
    | succ n =>
        rw [S.degenerate_eq_iUnion_range_σ] at hx
        simp only [Set.mem_iUnion, Set.mem_range] at hx
        obtain ⟨i, y, rfl⟩ := hx
        exact single_degen_mem i y 1

/-- **WP6, absolute form.**  The normalized chain module in degree `q` is free on the
*nondegenerate* `q`-simplices. -/
def normChainEquiv (S : SSet.{u}) (q : ℕ) :
    NormChain S q ≃ₗ[ZMod 2] (↥(S.nonDegenerate q) →₀ ZMod 2) :=
  (Submodule.quotEquivOfEq _ _ (degenSubmodule_eq_supported S q)).trans
    (quotSupportedEquiv (S.degenerate q) (ZMod 2))

theorem normChainEquiv_apply (S : SSet.{u}) (q : ℕ) (x : SSetChain S q)
    (a : ↥(S.nonDegenerate q)) :
    normChainEquiv S q (normProj S q x) a = x a.1 := rfl

/-- If every `q`-simplex of `S` is degenerate then the normalized chain module vanishes. -/
theorem normChain_subsingleton_of_all_degenerate (S : SSet.{u}) (q : ℕ)
    (h : ∀ x : S _⦋q⦌, x ∈ S.degenerate q) : Subsingleton (NormChain S q) := by
  have htop : degenSubmodule S q = ⊤ := by
    rw [degenSubmodule_eq_supported]
    refine top_le_iff.1 fun x _ => ?_
    exact (Finsupp.mem_supported (ZMod 2) _).2 fun a _ => h a
  rw [show NormChain S q = (SSetChain S q ⧸ degenSubmodule S q) from rfl, htop]
  infer_instance

/-! ## WP5/WP6 : the skeletal filtration -/

/-- The `r`-th skeleton of a simplicial set, as a simplicial set.  Mathlib's `X.skeleton n`
contains the simplices whose nondegenerate representative has dimension `< n`, so the
classical `r`-skeleton `K^{(r)}` is `Sk X (r + 1)`. -/
abbrev Sk (X : SSet.{u}) (r : ℕ) : SSet.{u} := (X.skeleton r : X.Subcomplex).toSSet

/-- The skeletal inclusion `K^{(r-1)} ⊆ K^{(r)}`. -/
abbrev skInc (X : SSet.{u}) (r : ℕ) : Sk X r ⟶ Sk X (r + 1) :=
  SSet.Subcomplex.homOfLE (X.skeleton.monotone (Nat.le_succ r))

/-- **Every simplex of the `n`-skeleton in dimension `≥ n` is degenerate.** -/
theorem degenerate_of_mem_skeleton {X : SSet.{u}} {n q : ℕ} (hnq : n ≤ q)
    (x : (Sk X n) _⦋q⦌) : x ∈ (Sk X n).degenerate q := by
  obtain ⟨m, f, hf, y, hy⟩ := (Sk X n).exists_nonDegenerate x
  have hyX : y.1.1 ∈ X.nonDegenerate m :=
    (SSet.Subcomplex.mem_nonDegenerate_iff _ _).1 y.2
  have hmem : y.1.1 ∈ (X.skeleton n).obj (op (SimplexCategory.mk m)) := y.1.2
  have hmn : m < n :=
    (X.mem_skeleton_obj_iff_of_nonDegenerate ⟨y.1.1, hyX⟩ n).1 hmem
  rw [SSet.mem_degenerate_iff]
  exact ⟨m, lt_of_lt_of_le hmn hnq, f, hf, y.1, hy.symm⟩

/-- **WP6, vanishing above the top cell.**  For `q ≥ n` the normalized chains of the
skeleton `Sk X n` vanish. -/
theorem normChain_skeleton_subsingleton {X : SSet.{u}} {n q : ℕ} (hnq : n ≤ q) :
    Subsingleton (NormChain (Sk X n) q) :=
  normChain_subsingleton_of_all_degenerate _ _ (fun x => degenerate_of_mem_skeleton hnq x)

/-- The relative normalized chains of the skeletal pair `K^{(r-1)} ⊆ K^{(r)}`, i.e.
`N_*(K^{(r)}, K^{(r-1)})` in Mathlib's skeleton indexing. -/
abbrev RelNormChain (X : SSet.{u}) (r q : ℕ) : Type u :=
  NormChain (Sk X (r + 1)) q ⧸ LinearMap.range (normMap (skInc X r) q)

/-- The relative **unnormalized** chains of the skeletal pair `K^{(r-1)} ⊆ K^{(r)}`. -/
abbrev RelChain (X : SSet.{u}) (r q : ℕ) : Type u :=
  SSetChain (Sk X (r + 1)) q ⧸ LinearMap.range (sSetChainMap (skInc X r) q)

/-- **WP5, relative comparison map.**  The normalization projection descends to the relative
complexes of the skeletal pair. -/
def relNormProj (X : SSet.{u}) (r q : ℕ) : RelChain X r q →ₗ[ZMod 2] RelNormChain X r q :=
  Submodule.mapQ _ _ (normProj (Sk X (r + 1)) q) (by
    rintro _ ⟨y, rfl⟩
    exact ⟨normProj (Sk X r) q y,
      (congrFun (congrArg DFunLike.coe (normProj_natural (skInc X r) q)) y).symm⟩)

/-- **WP5, relative section.**  The section `i` of Objective A also descends, because `P∞` is
natural. -/
def relNormInc (X : SSet.{u}) (r q : ℕ) : RelNormChain X r q →ₗ[ZMod 2] RelChain X r q :=
  Submodule.mapQ _ _ (normInc (Sk X (r + 1)) q) (by
    rintro _ ⟨y, rfl⟩
    exact ⟨normInc (Sk X r) q y,
      (congrFun (congrArg DFunLike.coe (normInc_natural (skInc X r) q)) y).symm⟩)

/-- **WP5, relative half-equivalence.**  `pʳᵉˡ ∘ iʳᵉˡ = id`: the relative normalization is a
split surjection.  (The remaining half, `iʳᵉˡ ∘ pʳᵉˡ ≃ id`, needs naturality of the pinned
homotopy `homotopyPInftyToId`, which is not a pinned lemma; see the audit document.) -/
theorem relNormProj_comp_relNormInc (X : SSet.{u}) (r q : ℕ) :
    (relNormProj X r q).comp (relNormInc X r q) = LinearMap.id := by
  refine Submodule.linearMap_qext _ (LinearMap.ext fun z => ?_)
  obtain ⟨x, rfl⟩ := normProj_surjective (Sk X (r + 1)) q z
  show Submodule.Quotient.mk (normProj (Sk X (r + 1)) q (normInc (Sk X (r + 1)) q
      (normProj (Sk X (r + 1)) q x))) = Submodule.Quotient.mk (normProj (Sk X (r + 1)) q x)
  rw [show normProj (Sk X (r + 1)) q (normInc (Sk X (r + 1)) q (normProj (Sk X (r + 1)) q x))
      = ((normProj (Sk X (r + 1)) q).comp (normInc (Sk X (r + 1)) q))
          (normProj (Sk X (r + 1)) q x) from rfl,
    normProj_comp_normInc]
  rfl

/-- **WP6, vanishing below the top cell.**  For `q < r` the skeletal inclusion is bijective
in dimension `q`, so the relative normalized chains vanish. -/
theorem relNormChain_subsingleton_of_lt {X : SSet.{u}} {r q : ℕ} (hq : q < r) :
    Subsingleton (RelNormChain X r q) := by
  have hsurj : Function.Surjective (normMap (skInc X r) q) := by
    have htop : (X.skeleton r).obj (op (SimplexCategory.mk q)) = ⊤ :=
      X.skeleton_obj_eq_top hq
    have hsimp : Function.Surjective ((skInc X r).app (op (SimplexCategory.mk q))) := by
      rintro ⟨y, hy⟩
      refine ⟨⟨y, ?_⟩, rfl⟩
      rw [htop]
      trivial
    have hchain : Function.Surjective (sSetChainMap (skInc X r) q) := by
      intro c
      refine ⟨Finsupp.mapDomain (Function.surjInv hsimp) c, ?_⟩
      show Finsupp.mapDomain _ (Finsupp.mapDomain _ c) = c
      rw [← Finsupp.mapDomain_comp]
      have hcomp : ((skInc X r).app (op (SimplexCategory.mk q))) ∘ Function.surjInv hsimp = id :=
        funext fun y => Function.surjInv_eq hsimp y
      rw [hcomp, Finsupp.mapDomain_id]
    intro z
    obtain ⟨w, rfl⟩ := normProj_surjective (Sk X (r + 1)) q z
    obtain ⟨v, rfl⟩ := hchain w
    exact ⟨normProj (Sk X r) q v,
      congrFun (congrArg DFunLike.coe (normProj_natural (skInc X r) q).symm) v⟩
  have hrange : LinearMap.range (normMap (skInc X r) q) = ⊤ :=
    LinearMap.range_eq_top.2 hsurj
  rw [show RelNormChain X r q
      = (NormChain (Sk X (r + 1)) q ⧸ LinearMap.range (normMap (skInc X r) q)) from rfl, hrange]
  infer_instance

/-- **WP6, vanishing above the top cell, relative form.**  For `q > r` the relative
normalized chains of the skeletal pair vanish. -/
theorem relNormChain_subsingleton_of_gt {X : SSet.{u}} {r q : ℕ} (hq : r < q) :
    Subsingleton (RelNormChain X r q) :=
  have : Subsingleton (NormChain (Sk X (r + 1)) q) :=
    normChain_skeleton_subsingleton (Nat.succ_le_of_lt hq)
  Quotient.instSubsingletonQuotient _

/-- **WP6, the top cell.**  In the critical degree the relative normalized chains of the
skeletal pair are freely generated over `ℤ₂` by the **nondegenerate** `r`-simplices of
`K^{(r)}`. -/
def relNormChainEquiv (X : SSet.{u}) (r : ℕ) :
    RelNormChain X r r ≃ₗ[ZMod 2] (↑((Sk X (r + 1)).nonDegenerate r) →₀ ZMod 2) :=
  have _hsub : Subsingleton (NormChain (Sk X r) r) :=
    normChain_skeleton_subsingleton (le_refl r)
  have hbot : LinearMap.range (normMap (skInc X r) r) = ⊥ := by
    refine le_antisymm ?_ bot_le
    rintro _ ⟨z, rfl⟩
    rw [Subsingleton.elim z 0, map_zero]
    exact Submodule.zero_mem _
  (Submodule.quotEquivOfEqBot _ hbot).trans (normChainEquiv (Sk X (r + 1)) r)

/-- The nondegenerate `r`-simplices of the `r`-skeleton `K^{(r)} = Sk X (r+1)` are exactly the
nondegenerate `r`-simplices of `X`. -/
def nonDegenerateSkeletonEquiv (X : SSet.{u}) (r : ℕ) :
    ↑((Sk X (r + 1)).nonDegenerate r) ≃ ↑(X.nonDegenerate r) where
  toFun x := ⟨x.1.1, (SSet.Subcomplex.mem_nonDegenerate_iff _ _).1 x.2⟩
  invFun x := ⟨⟨x.1, by
      have htop : (X.skeleton (r + 1)).obj (op (SimplexCategory.mk r)) = ⊤ :=
        X.skeleton_obj_eq_top (Nat.lt_succ_self r)
      rw [htop]
      trivial⟩,
    (SSet.Subcomplex.mem_nonDegenerate_iff _ _).2 x.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

end SpineTask13
