import RequestProject.Experiment2.NullSectorTask23.LocalProduct

/-!
# Task 23, Package G: reconstruction of the global carrier from the local pieces

**RECONSTRUCTION LAYER.  This is the principal Task-23 endpoint (item 61).**

The disjoint union of the local product pieces is formed (item 51), the overlap relation
generated by the transition signs is defined (item 52), it is proved to be an equivalence
relation — reflexivity from `τ_aa = +1`, symmetry from the inverse law, transitivity from
the triple-overlap law (items 53, 54) — the quotient carrier is constructed (item 55), the
natural map to the certified carrier is defined and proved well defined, surjective and
injective (items 56–59), and finally the strongest topological statement is proved: the map
is a homeomorphism (item 60).

The base map is reconstructed as well: the certified projection of the reconstructed element
is exactly the visible element recorded by the local datum.
-/

set_option synthInstance.maxHeartbeats 400000
set_option maxHeartbeats 1000000

namespace NullSectorTask23

open NullSectorTask01 NullSectorTask04 NullSectorTask06 NullSectorTask07 NullSectorTask08
open NullSectorTask09 NullSectorTask10 NullSectorTask11 NullSectorTask12 NullSectorTask13
open NullSectorTask14 NullSectorTask15 NullSectorTask16 NullSectorTask17 NullSectorTask18
open NullSectorTask19 NullSectorTask20 NullSectorTask21

open Quaternion Topology

/-! ## The disjoint union of the local pieces (item 51) -/

/-- **NEUTRAL DEFINITION (item 51).**  The disjoint union of the local product pieces. -/
abbrev Pieces : Type := Σ i : Fin 4, ↥(Vset i) × Sgn

/-- The visible element recorded by a local datum. -/
def baseOf (x : Pieces) : GvisT := (x.2.1 : GvisT)

/-- The core element assembled from a local datum. -/
noncomputable def glue (x : Pieces) : LiftT := sact x.2.2 (sec x.1 x.2.1)

theorem pr_glue (x : Pieces) : pr (glue x) = baseOf x := by
  rw [glue, pr_sact, pr_sec, baseOf]

/-! ## The overlap relation (item 52) -/

/-- **NEUTRAL DEFINITION (item 52).**  Two local data are related when they record the same
visible element and their signs differ by the transition sign of the two domains. -/
def RelPieces (x y : Pieces) : Prop :=
  ∃ (g : GvisT) (hx : g ∈ Vset x.1) (hy : g ∈ Vset y.1),
    baseOf x = g ∧ baseOf y = g ∧ y.2.2 = tauAt x.1 y.1 g hx hy * x.2.2

/-- **PACKAGE G (item 53).**  Reflexivity, from the identity law. -/
theorem RelPieces.refl (x : Pieces) : RelPieces x x :=
  ⟨baseOf x, x.2.1.2, x.2.1.2, rfl, rfl, by rw [tauAt_self, one_mul]⟩

/-- **PACKAGE G (item 53).**  Symmetry, from the inverse law. -/
theorem RelPieces.symm {x y : Pieces} (h : RelPieces x y) : RelPieces y x := by
  obtain ⟨g, hx, hy, hbx, hby, hsign⟩ := h
  refine ⟨g, hy, hx, hby, hbx, ?_⟩
  rw [← tauAt_symm' y.1 x.1 g hy hx, hsign, ← mul_assoc, Sgn.mul_self, one_mul]

/-- **PACKAGE G (item 54).**  Transitivity, from the triple-overlap law. -/
theorem RelPieces.trans {x y z : Pieces} (h : RelPieces x y) (h' : RelPieces y z) :
    RelPieces x z := by
  obtain ⟨g, hx, hy, hbx, hby, hsign⟩ := h
  obtain ⟨g', hy', hz', hby', hbz, hsign'⟩ := h'
  have hgg : g' = g := by rw [← hby', hby]
  subst hgg
  refine ⟨g', hx, hz', hbx, hbz, ?_⟩
  rw [hsign', hsign, ← mul_assoc, ← tauAt_trans x.1 y.1 z.1 g' hx hy hz']

/-- **PACKAGE G.**  The relation is exactly equality of the assembled core elements: the
local data are glued by the transition signs and by nothing else. -/
theorem relPieces_iff_glue_eq {x y : Pieces} : RelPieces x y ↔ glue x = glue y := by
  constructor
  · rintro ⟨g, hx, hy, hbx, hby, hsign⟩
    have hx1 : x.2.1 = (⟨g, hx⟩ : ↥(Vset x.1)) := Subtype.ext hbx
    have hy1 : y.2.1 = (⟨g, hy⟩ : ↥(Vset y.1)) := Subtype.ext hby
    rw [glue, glue, hx1, hy1, hsign, sec_eq_tau_smul hx hy, ← sact_mul]
    congr 1
    rw [mul_right_comm, Sgn.mul_self, one_mul]
  · intro h
    have hbase : baseOf x = baseOf y := by
      rw [← pr_glue, ← pr_glue, h]
    have hx : baseOf x ∈ Vset x.1 := x.2.1.2
    have hy : baseOf x ∈ Vset y.1 := by rw [hbase]; exact y.2.1.2
    refine ⟨baseOf x, hx, hy, rfl, hbase.symm, ?_⟩
    have hx1 : x.2.1 = (⟨baseOf x, hx⟩ : ↥(Vset x.1)) := rfl
    have hy1 : y.2.1 = (⟨baseOf x, hy⟩ : ↥(Vset y.1)) := Subtype.ext hbase.symm
    have hglue : sact y.2.2 (sec y.1 ⟨baseOf x, hy⟩) = sact x.2.2 (sec x.1 ⟨baseOf x, hx⟩) := by
      rw [← hx1, ← hy1, ← glue, ← glue, h]
    rw [sec_eq_tau_smul hx hy, ← sact_mul] at hglue
    have hmul := sact_injective_sign (sec x.1 ⟨baseOf x, hx⟩) hglue
    exact Sgn.eq_mul_of_mul_eq (by rw [mul_comm]; exact hmul)

/-! ## The reconstructed carrier (item 55) -/

/-- **NEUTRAL DEFINITION (item 55).**  The reconstruction setoid. -/
def recSetoid : Setoid Pieces where
  r := RelPieces
  iseqv := ⟨RelPieces.refl, RelPieces.symm, RelPieces.trans⟩

/-- **NEUTRAL DEFINITION (item 55).**  The reconstructed carrier. -/
def LiftLocal : Type := Quotient recSetoid

instance : TopologicalSpace LiftLocal := instTopologicalSpaceQuotient

/-- The class of a local datum. -/
def locClass (x : Pieces) : LiftLocal := Quotient.mk recSetoid x

theorem locClass_surjective : Function.Surjective locClass := Quotient.mk_surjective

theorem continuous_locClass : Continuous locClass := continuous_quotient_mk'

theorem locClass_eq_iff {x y : Pieces} : locClass x = locClass y ↔ RelPieces x y :=
  Quotient.eq (r := recSetoid)

/-! ## The natural map to the certified carrier (items 56–59) -/

/-- **PACKAGE G (items 56, 57).**  The natural map, well defined by the overlap relation. -/
noncomputable def toLift : LiftLocal → LiftT :=
  Quotient.lift glue fun _ _ h => relPieces_iff_glue_eq.1 h

@[simp] theorem toLift_locClass (x : Pieces) : toLift (locClass x) = glue x := rfl

/-- **PACKAGE G (item 59).**  Injectivity. -/
theorem toLift_injective : Function.Injective toLift := by
  intro z z' h
  obtain ⟨x, rfl⟩ := locClass_surjective z
  obtain ⟨y, rfl⟩ := locClass_surjective z'
  exact locClass_eq_iff.2 (relPieces_iff_glue_eq.2 h)

/-- **PACKAGE G (item 58).**  Surjectivity. -/
theorem toLift_surjective : Function.Surjective toLift := by
  intro u
  obtain ⟨i, hi⟩ := exists_qco_ne_zero u.2
  refine ⟨locClass ⟨i, ⟨⟨pr u, mem_Vset_of hi⟩, sgnOf hi⟩⟩, ?_⟩
  show sact (sgnOf hi) (sec i ⟨pr u, mem_Vset_of hi⟩) = u
  rw [sec_eq_sact_of_rep (mem_Vset_of hi) rfl hi, ← sact_mul, Sgn.mul_self, sact_one]

theorem toLift_bijective : Function.Bijective toLift :=
  ⟨toLift_injective, toLift_surjective⟩

/-! ## The topological statement (item 60) -/

theorem continuous_glue : Continuous glue := by
  refine continuous_sigma ?_
  intro i
  have h : (fun p : ↥(Vset i) × Sgn => glue ⟨i, p⟩)
      = fun p : ↥(Vset i) × Sgn => ((locProd i p : ↥(Uset i)) : LiftT) := rfl
  rw [h]
  exact continuous_subtype_val.comp (continuous_locProd i)

theorem continuous_toLift : Continuous toLift := by
  refine continuous_quot_lift _ continuous_glue

/-- The inclusion of one local piece into the disjoint union. -/
def inc (i : Fin 4) (p : ↥(Vset i) × Sgn) : Pieces := ⟨i, p⟩

theorem continuous_inc (i : Fin 4) : Continuous (inc i) := by
  show Continuous fun p : ↥(Vset i) × Sgn => (⟨i, p⟩ : Pieces)
  exact continuous_sigmaMk (σ := fun j : Fin 4 => ↥(Vset j) × Sgn)

theorem image_sigma {X : Type*} (f : Pieces → X) (P : Set Pieces) :
    f '' P = ⋃ i : Fin 4, (fun p : ↥(Vset i) × Sgn => f (inc i p)) '' (inc i ⁻¹' P) := by
  ext x
  constructor
  · rintro ⟨⟨i, p⟩, hp, rfl⟩
    exact Set.mem_iUnion.2 ⟨i, ⟨p, hp, rfl⟩⟩
  · intro hx
    obtain ⟨i, p, hp, rfl⟩ := Set.mem_iUnion.1 hx
    exact ⟨inc i p, hp, rfl⟩

theorem isOpenMap_glue : IsOpenMap glue := by
  intro P hP
  rw [image_sigma glue P]
  refine isOpen_iUnion fun i => ?_
  have hP' : IsOpen (inc i ⁻¹' P) := hP.preimage (continuous_inc i)
  have h : (fun p : ↥(Vset i) × Sgn => glue (inc i p))
      = fun p : ↥(Vset i) × Sgn => ((locProd i p : ↥(Uset i)) : LiftT) := rfl
  have h2 : (fun p : ↥(Vset i) × Sgn => ((locProd i p : ↥(Uset i)) : LiftT)) '' (inc i ⁻¹' P)
      = Subtype.val '' (locProd i '' (inc i ⁻¹' P)) := (Set.image_image _ _ _).symm
  rw [h, h2]
  exact (isOpen_Uset i).isOpenMap_subtype_val _ ((locProdHomeo i).isOpenMap _ hP')

theorem isOpenMap_toLift : IsOpenMap toLift := by
  intro O hO
  have hP : IsOpen (locClass ⁻¹' O) := hO.preimage continuous_locClass
  have himg : toLift '' O = glue '' (locClass ⁻¹' O) := by
    ext u
    constructor
    · rintro ⟨z, hz, rfl⟩
      obtain ⟨x, rfl⟩ := locClass_surjective z
      exact ⟨x, hz, rfl⟩
    · rintro ⟨x, hx, rfl⟩
      exact ⟨locClass x, hx, rfl⟩
  rw [himg]
  exact isOpenMap_glue _ hP

/-- **PACKAGE G (items 60, 61), PRINCIPAL TASK-23 ENDPOINT.**  The reconstructed carrier is
homeomorphic to the certified carrier: the global carrier is recovered exactly from the local
representatives and the two-element overlap signs. -/
noncomputable def liftLocalHomeo : LiftLocal ≃ₜ LiftT :=
  (Equiv.ofBijective _ toLift_bijective).toHomeomorphOfContinuousOpen
    continuous_toLift isOpenMap_toLift

theorem liftLocalHomeo_apply (z : LiftLocal) : liftLocalHomeo z = toLift z := rfl

/-! ## The reconstructed projection -/

theorem baseOf_congr {x y : Pieces} (h : RelPieces x y) : baseOf x = baseOf y := by
  obtain ⟨g, -, -, hbx, hby, -⟩ := h
  rw [hbx, hby]

/-- The visible element attached to a class of local data. -/
def prLocal : LiftLocal → GvisT := Quotient.lift baseOf fun _ _ h => baseOf_congr h

@[simp] theorem prLocal_locClass (x : Pieces) : prLocal (locClass x) = baseOf x := rfl

/-- **PACKAGE G.**  The reconstruction recovers the projection as well, not only the
carrier. -/
theorem pr_toLift (z : LiftLocal) : pr (toLift z) = prLocal z := by
  obtain ⟨x, rfl⟩ := locClass_surjective z
  exact pr_glue x

end NullSectorTask23
