import RequestProject.Experiment2.NullSectorTask13.AutomorphismCarrierAction

/-!
# Task 13, Layer 11: the exact global fixed locus of the carrier-family action
(§35, §36)

Task 12 exhibited two minimal carriers fixed by the whole automorphism family and one that
moves, and left the exact fixed locus **UNRESOLVED**.  This module settles it.

The key step is an exact *global parametrization* of the family of minimal carriers, which
Task 12 did not have:

`minimal_eq_Lgen_esph` — **every** minimal left carrier is the carrier generated by a
point of the explicit unit two-sphere of self-product elements, and the point is unique.

The construction is intrinsic: from an arbitrary self-product generator `e` one forms
`e^† ⋆ e`, where `†` is the inherited coordinate reflection that fixes `1, A, B, C` and
reverses the four remaining derived basis elements.  Its unit coordinate is a sum of
squares, hence nonzero, its four reversed coordinates vanish identically, and the
inherited multiplicativity of the central quadratic datum forces the remaining three
coordinates onto the unit sphere.  Minimality then upgrades the resulting inclusion of
carriers to an equality.

With the parametrization in hand, the fixed-locus question becomes the fixed-point
question for a plane rotation, and is answered exactly.
-/

namespace NullSectorTask13

open NullSectorTask08 NullSectorTask09 NullSectorTask10 NullSectorTask11 NullSectorTask12

/-! ## The inherited coordinate reflection -/

/-- **DERIVED, INSTRUMENTAL.**  The coordinate reflection of the inherited carrier that
fixes `1, A, B, C` and reverses `P, Q, R, S`.  It is used only to produce a distinguished
generator inside a given minimal carrier; no metric or conjugation structure is
attached. -/
def dg (x : W) : W := ![x 0, x 1, x 2, x 3, -x 4, -x 5, -x 6, -x 7]

@[simp] theorem dg_coord_0 (x : W) : dg x 0 = x 0 := rfl
@[simp] theorem dg_coord_1 (x : W) : dg x 1 = x 1 := rfl
@[simp] theorem dg_coord_2 (x : W) : dg x 2 = x 2 := rfl
@[simp] theorem dg_coord_3 (x : W) : dg x 3 = x 3 := rfl
@[simp] theorem dg_coord_4 (x : W) : dg x 4 = -x 4 := rfl
@[simp] theorem dg_coord_5 (x : W) : dg x 5 = -x 5 := rfl
@[simp] theorem dg_coord_6 (x : W) : dg x 6 = -x 6 := rfl
@[simp] theorem dg_coord_7 (x : W) : dg x 7 = -x 7 := rfl

/-- The unit coordinate of `dg x ⋆ x` is the sum of the squares of the coordinates. -/
theorem dg_mul_coord_0 (x : W) :
    (dg x ⋆ x) 0 = x 0 ^ 2 + x 1 ^ 2 + x 2 ^ 2 + x 3 ^ 2 + x 4 ^ 2 + x 5 ^ 2
      + x 6 ^ 2 + x 7 ^ 2 := by
  simp [dg]
  ring

/-- The four reversed coordinates of `dg x ⋆ x` vanish identically. -/
theorem dg_mul_coord_4567 (x : W) :
    (dg x ⋆ x) 4 = 0 ∧ (dg x ⋆ x) 5 = 0 ∧ (dg x ⋆ x) 6 = 0 ∧ (dg x ⋆ x) 7 = 0 := by
  refine ⟨?_, ?_, ?_, ?_⟩ <;> · simp [dg]; ring

/-! ## Every minimal carrier is generated by a point of the explicit two-sphere -/

/-- **PRINCIPAL THEOREM (global parametrization).**  Every minimal left carrier is
generated by a point of the explicit unit two-sphere of self-product elements.  This
closes the Task-12 gap: the family of minimal carriers is exactly the two-sphere. -/
theorem minimal_eq_Lgen_esph {L : Submodule ℝ W} (hL : IsMinimalLeftCarrier L) :
    ∃ n₁ n₂ n₃ : ℝ, n₁ ^ 2 + n₂ ^ 2 + n₃ ^ 2 = 1 ∧ L = Lgen (esph n₁ n₂ n₃) := by
  obtain ⟨e, heidem, hene, henull, he0, he7, rfl⟩ := isMinimal_eq_Lgen_selfProduct hL
  obtain ⟨g, hgdef⟩ : ∃ g : W, g = dg e ⋆ e := ⟨_, rfl⟩
  have hg0pos : 0 < g 0 := by
    rw [hgdef, dg_mul_coord_0, he0]
    positivity
  have hg0ne : g 0 ≠ 0 := ne_of_gt hg0pos
  obtain ⟨hg4, hg5, hg6, hg7⟩ : g 4 = 0 ∧ g 5 = 0 ∧ g 6 = 0 ∧ g 7 = 0 := by
    rw [hgdef]; exact dg_mul_coord_4567 e
  have hgnull : IsNullElt g := by
    have hmul : Ncand 1 (dg e ⋆ e) = Ncand 1 (dg e) ⋆ Ncand 1 e :=
      Ncand_mul 1 (by norm_num) _ _
    have he : Ncand 1 e = 0 := (isNullElt_iff_Ncand e).1 henull
    rw [he, mul_zero_W] at hmul
    exact (isNullElt_iff_Ncand g).2 (by rw [hgdef, hmul])
  have hnRe : g 0 ^ 2 - g 1 ^ 2 - g 2 ^ 2 - g 3 ^ 2 = 0 := by
    have h := hgnull.1
    simp only [nRe] at h
    rw [hg4, hg5, hg6, hg7] at h
    linarith
  have hsum : (g 1 / g 0) ^ 2 + (g 2 / g 0) ^ 2 + (g 3 / g 0) ^ 2 = 1 := by
    field_simp
    linarith [hnRe]
  refine ⟨g 1 / g 0, g 2 / g 0, g 3 / g 0, hsum, ?_⟩
  have hfg : esph (g 1 / g 0) (g 2 / g 0) (g 3 / g 0) = (1 / (2 * g 0)) • g := by
    funext i
    fin_cases i <;> simp [esph, hg4, hg5, hg6, hg7] <;> field_simp
  have hfmem : esph (g 1 / g 0) (g 2 / g 0) (g 3 / g 0) ∈ Lgen e := by
    refine (mem_Lgen_iff _ _).2 ⟨(1 / (2 * g 0)) • dg e, ?_⟩
    rw [smul_mul_W, ← hgdef, ← hfg]
  have hfne : esph (g 1 / g 0) (g 2 / g 0) (g 3 / g 0) ≠ 0 := esph_ne_zero _ _ _
  have hfnull : IsNullElt (esph (g 1 / g 0) (g 2 / g 0) (g 3 / g 0)) := esph_isNullElt hsum
  have hle : Lgen (esph (g 1 / g 0) (g 2 / g 0) (g 3 / g 0)) ≤ Lgen e :=
    Lgen_le (isLeftCarrier_Lgen e) hfmem
  have h1 : Module.finrank ℝ (Lgen (esph (g 1 / g 0) (g 2 / g 0) (g 3 / g 0))) = 4 :=
    finrank_Lgen_eq_four hfne hfnull
  have h2 : Module.finrank ℝ (Lgen e) = 4 := finrank_Lgen_eq_four hene henull
  exact (Submodule.eq_of_le_of_finrank_eq hle (by rw [h1, h2])).symm

/-- **DERIVED.**  Conversely every point of the two-sphere gives a minimal carrier, and
distinct points give distinct carriers: the parametrization is exact. -/
theorem minimal_carrier_parametrization :
    (∀ n₁ n₂ n₃ : ℝ, n₁ ^ 2 + n₂ ^ 2 + n₃ ^ 2 = 1 →
      IsMinimalLeftCarrier (Lgen (esph n₁ n₂ n₃))) ∧
    (∀ L : Submodule ℝ W, IsMinimalLeftCarrier L →
      ∃ n₁ n₂ n₃ : ℝ, n₁ ^ 2 + n₂ ^ 2 + n₃ ^ 2 = 1 ∧ L = Lgen (esph n₁ n₂ n₃)) ∧
    (∀ n₁ n₂ n₃ m₁ m₂ m₃ : ℝ, n₁ ^ 2 + n₂ ^ 2 + n₃ ^ 2 = 1 →
      Lgen (esph n₁ n₂ n₃) = Lgen (esph m₁ m₂ m₃) → n₁ = m₁ ∧ n₂ = m₂ ∧ n₃ = m₃) :=
  ⟨fun _ _ _ h => isMinimal_Lgen_esph h, fun _ hL => minimal_eq_Lgen_esph hL,
    fun _ _ _ _ _ _ hn h => Lgen_esph_inj hn h⟩

/-! ## §36 — fixity at a single parameter value -/

/-- **PRINCIPAL THEOREM (§36).**  Exact criterion for fixity at *one* parameter value: a
minimal carrier of the two-sphere is fixed by `Φθ` exactly when the automorphism is
already trivial in the transverse plane (`cos θ = 1`), or when the carrier is axial.  The
exceptional angles therefore enlarge the fixed set to everything, and are recorded
separately from global invariance. -/
theorem phi_fixed_single_angle {n₁ n₂ n₃ : ℝ} (hn : n₁ ^ 2 + n₂ ^ 2 + n₃ ^ 2 = 1)
    (θ : ℝ) :
    phiCarrier θ (Lgen (esph n₁ n₂ n₃)) = Lgen (esph n₁ n₂ n₃) ↔
      (Real.cos θ = 1 ∧ Real.sin θ = 0) ∨ (n₂ = 0 ∧ n₃ = 0) := by
  have hpy := Real.sin_sq_add_cos_sq θ
  have hrot : phiCarrier θ (Lgen (esph n₁ n₂ n₃))
      = Lgen (esph n₁ (Real.cos θ * n₂ - Real.sin θ * n₃)
          (Real.sin θ * n₂ + Real.cos θ * n₃)) := by
    rw [phiCarrier, Phi_map_Lgen, Phi_esph]
  have hnorm : n₁ ^ 2 + (Real.cos θ * n₂ - Real.sin θ * n₃) ^ 2
      + (Real.sin θ * n₂ + Real.cos θ * n₃) ^ 2 = 1 := by
    linear_combination (n₂ ^ 2 + n₃ ^ 2) * hpy + hn
  constructor
  · intro h
    rw [hrot] at h
    obtain ⟨-, h2, h3⟩ := Lgen_esph_inj hnorm h
    by_cases hc : Real.cos θ = 1
    · left
      refine ⟨hc, ?_⟩
      have hs2 : Real.sin θ ^ 2 = 0 := by
        rw [hc] at hpy; linarith
      exact sq_eq_zero_iff.mp hs2
    · right
      have hdet : (Real.cos θ - 1) ^ 2 + Real.sin θ ^ 2 ≠ 0 := by
        intro hzero
        have hsq : (Real.cos θ - 1) ^ 2 = 0 := by
          linarith [sq_nonneg (Real.cos θ - 1), sq_nonneg (Real.sin θ)]
        exact hc (by
          have := sq_eq_zero_iff.mp hsq
          linarith)
      have e2 : (Real.cos θ - 1) * n₂ - Real.sin θ * n₃ = 0 := by linarith
      have e3 : Real.sin θ * n₂ + (Real.cos θ - 1) * n₃ = 0 := by linarith
      constructor
      · have k2 : ((Real.cos θ - 1) ^ 2 + Real.sin θ ^ 2) * n₂ = 0 := by
          linear_combination (Real.cos θ - 1) * e2 + Real.sin θ * e3
        rcases mul_eq_zero.1 k2 with h | h
        · exact absurd h hdet
        · exact h
      · have k3 : ((Real.cos θ - 1) ^ 2 + Real.sin θ ^ 2) * n₃ = 0 := by
          linear_combination (-(Real.sin θ)) * e2 + (Real.cos θ - 1) * e3
        rcases mul_eq_zero.1 k3 with h | h
        · exact absurd h hdet
        · exact h
  · rintro (⟨hc, hs⟩ | ⟨h2, h3⟩)
    · rw [hrot, hc, hs]
      norm_num
    · rw [hrot, h2, h3]
      norm_num

/-! ## §35 — the exact global fixed locus -/

/-- **PRINCIPAL THEOREM (§35): `phi_fixed_carrier_iff`, `FIXED CARRIER`.**  A minimal left
carrier is fixed by the *whole* inherited automorphism family exactly when it is one of
the two axial carriers generated by `(1 ± A)/2`.  The complete fixed locus therefore
consists of exactly two carriers — no larger family, and in particular not a continuous
one. -/
theorem phi_fixed_carrier_iff {L : Submodule ℝ W} (hL : IsMinimalLeftCarrier L) :
    (∀ θ : ℝ, phiCarrier θ L = L) ↔ L = Lgen eplus ∨ L = Lgen eminus := by
  have heP : eplus = esph 1 0 0 := eplus_eq.trans axis_dependent_selection.1.symm
  have heM : eminus = esph (-1) 0 0 := eminus_eq.trans axis_dependent_selection.2.1.symm
  constructor
  · intro hfix
    obtain ⟨n₁, n₂, n₃, hn, rfl⟩ := minimal_eq_Lgen_esph hL
    have h := (phi_fixed_single_angle hn Real.pi).1 (hfix Real.pi)
    have hcase : n₂ = 0 ∧ n₃ = 0 := by
      rcases h with ⟨hc, -⟩ | h
      · rw [Real.cos_pi] at hc; norm_num at hc
      · exact h
    obtain ⟨h2, h3⟩ := hcase
    have hn1 : n₁ = 1 ∨ n₁ = -1 := by
      have hsq : n₁ * n₁ = 1 := by rw [h2, h3] at hn; nlinarith [hn]
      exact mul_self_eq_one_iff.1 hsq
    rcases hn1 with h1 | h1
    · left; rw [heP, h1, h2, h3]
    · right; rw [heM, h1, h2, h3]
  · rintro (rfl | rfl) θ
    · rw [heP, phiCarrier]; exact Phi_map_Lgen_esph_axial θ 1
    · rw [heM, phiCarrier]; exact Phi_map_Lgen_esph_axial θ (-1)

/-- **DERIVED (§35, §36).**  The exact fixed locus, stated as a set: exactly two minimal
carriers, and they are distinct. -/
theorem phi_fixed_locus_exact :
    {L : Submodule ℝ W | IsMinimalLeftCarrier L ∧ ∀ θ : ℝ, phiCarrier θ L = L}
      = {Lgen eplus, Lgen eminus} ∧ Lgen eplus ≠ Lgen eminus := by
  have heP : eplus = esph 1 0 0 := eplus_eq.trans axis_dependent_selection.1.symm
  have heM : eminus = esph (-1) 0 0 := eminus_eq.trans axis_dependent_selection.2.1.symm
  have hminP : IsMinimalLeftCarrier (Lgen eplus) := by
    rw [heP]; exact isMinimal_Lgen_esph (by norm_num)
  have hminM : IsMinimalLeftCarrier (Lgen eminus) := by
    rw [heM]; exact isMinimal_Lgen_esph (by norm_num)
  constructor
  · ext L
    simp only [Set.mem_setOf_eq, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · rintro ⟨hL, hfix⟩
      exact (phi_fixed_carrier_iff hL).1 hfix
    · rintro (rfl | rfl)
      · exact ⟨hminP, (phi_fixed_carrier_iff hminP).2 (Or.inl rfl)⟩
      · exact ⟨hminM, (phi_fixed_carrier_iff hminM).2 (Or.inr rfl)⟩
  · intro hcon
    rw [heP, heM] at hcon
    obtain ⟨h1, -, -⟩ := Lgen_esph_inj (n₁ := 1) (n₂ := 0) (n₃ := 0) (by norm_num) hcon
    norm_num at h1

end NullSectorTask13
