import RequestProject.Spine.Solder.RegularGauge
import RequestProject.Spine.Solder.WeakInsufficiency
import RequestProject.Spine.Comparison.SolderTangentGate

/-!
# Spine / Comparison : the Task-35 smooth solder / bundle-equivalence certificate

**The Task-35 comparison endpoint, and a leaf of the production DAG.**

Task 34 closed the *fibrewise/algebraic* solder gate and left open, explicitly, the
*topological/smooth* one.  Task 35 closes the regularity gap at the level stated here, and
this module collects the result in one certificate,
`SpinNative.SmoothTangentSolderData.smooth_solder_tangent_certificate`.

## The Task-35 answer

> **Is the missing regular coupling exactly a smooth bundle equivalence between the internal
> Lorentz bundle generated by the native Spin cocycle and the tangent bundle of the Task-33
> emergent manifold?**

Yes, at the exact regularity level that the pinned infrastructure and the certified data
support, and this is proved in both directions in
`SpinNative.smooth_solder_iff_regular_bundle_equivalence`:

* a regular solder datum *is* a fibrewise linear equivalence
  `InternalLorentzBundle(S) ≃ TM` whose total-space maps are continuous in both directions
  (hence a homeomorphism covering `id_M`) and whose local representatives in the actual
  chart trivializations are `C^∞`;
* conversely any such equivalence is a regular solder datum.

There is **no further geometric primitive between the two notions**.  What is *not* claimed
is a morphism of *smooth* vector bundles in the differential-geometric sense: the internal
Lorentz bundle is built from the native Spin cocycle, which the project's transition datum
`CechSpinLift.VisibleCocycle` requires only to be **continuous**, so it carries no smooth
bundle structure to begin with (Mathlib's `VectorBundleCore.IsContMDiff` mixin is not
available for it).  Task 35 records instead the exact converse constraint
(`SpinNative.SmoothTangentSolderData.contDiffOn_solderLorentzRep`): a regular solder forces
the *projected* Lorentz transition to have a `C^∞` representative in the chart coordinates.

## The Spin endpoint (Task 35 §9)

`SpinNative.SmoothTangentSolderData.spin_endpoint_topological` classifies it exactly:

```text
tangent Lorentz frame cocycle = projected native Lorentz cocycle : DERIVED
native Spin cocycle is a lift of it                              : DERIVED
regularity of that lift                                          : TOPOLOGICAL (continuous)
smooth Spin structure                                            : NOT CLAIMED
```

The upgrade "continuous Spin lift ⇒ smooth Spin lift" is **not** performed.  It would need a
smooth structure on the intrinsic Spin group together with a *smooth* local section of the
intrinsic double cover `SpinCore.spinCover`; the project certifies only a **continuous**
local section (`SpinCore.spinCover_hasLocalSection`), and the pinned Mathlib supplies no
smooth structure for the intrinsic Clifford group of this project.  That is the exact
missing infrastructure, and no stronger statement is made.

## Explicitly absent

`w₁(TM)`, `w₂(TM)`, Stiefel–Whitney classes, Levi-Civita connection, spin connection,
curvature, torsion, Einstein equations, dynamics, quantization — none of these occurs in this
module or in its import closure below `Mathlib`.
-/

set_option synthInstance.maxHeartbeats 400000
set_option maxHeartbeats 1000000

noncomputable section

namespace SpinNative

open CechSpinLift NullSectorTask28 SpinCore LorentzFrames EmergentBase
  EmergentBase.BaseGluingData SolderBundle

universe t

variable {ι : Type t} {B : BaseGluingData LocalModel ι}
  {S : NativeSpinTransitionData ↥SpinGroup (emergentCover B)}

namespace SmoothTangentSolderData

variable (E : SmoothTangentSolderData B S)

/-! ## The Spin endpoint, classified -/

/-- **DERIVED (Task 35) — the exact regularity level of the Spin endpoint.**

1. the frame transition cocycle of the genuine tangent Lorentz frames obtained from the
   regular solder equals the projected internal Lorentz cocycle of the Spin seed;
2. the native Spin transition system is a lift of that cocycle along the intrinsic double
   cover — a **Spin structure for the actual tangent frame data**;
3. the regularity available for that lift is **continuity** (the native datum's own
   condition), while the *projected* Lorentz transition is, thanks to the regular solder,
   `C^∞` in the chart coordinates.

The gap between 3's two halves is exactly the missing smooth local section of `spinCover`;
"smooth Spin structure" is therefore **not** claimed.  See the module docstring. -/
theorem spin_endpoint_topological (h : B.SmoothGluing) :
    (∀ i j, ∀ x ∈ (emergentCover B).overlap₂ i j,
      (E.toTangentSolderData h).toLorentzTangentFrameData.transition i j x
        = (project internalSpinProjection S).g i j x) ∧
    Nonempty (SpinFrameStructure
      (E.toTangentSolderData h).toLorentzTangentFrameData) ∧
    (∀ i j, ContinuousOn (fun x => S.g i j x) ((emergentCover B).overlap₂ i j)) ∧
    (∀ i j, ContDiffOn ℝ (⊤ : ℕ∞) (fun y => E.solderLorentzRep i j y) (B.W i j)) :=
  ⟨fun _ _ _ hx => (E.toTangentSolderData h).projected_eq_tangentFrameTransition _ _ hx,
   ⟨(E.toTangentSolderData h).nativeSpin_to_tangentSpinFrameStructure⟩,
   fun i j => S.continuousOn_g i j,
   fun i j => E.contDiffOn_solderLorentzRep h i j⟩

/-! ## The principal Task-35 certificate -/

/-- **DERIVED (Task 35), THE PRINCIPAL CERTIFICATE.**

For a smooth base-gluing datum `B`, an emergent Spin-native seed `S` on its emergent cover,
and a **regular** solder datum `E`:

1. **the manifold.**  `M = Space B` is a `C^∞` manifold over the four-dimensional intrinsic
   local model of the Clifford/Spin core (Task 33), and the model is four-dimensional;
2. **the genuine tangent transitions.**  Mathlib's own tangent-bundle coordinate changes of
   the *actual* Task-33 atlas are the derivatives `D(φ_ij)` of the primitive's
   identification maps;
3. **the internal Lorentz transitions.**  The transition functions of the internal Lorentz
   bundle are exactly the projected native Spin transitions `ρ(g̃_ij)`;
4. **the regular solder intertwines them**, with `C^∞` local representatives: the local
   representative of the induced bundle map in the trivializations of the piece `i` is the
   smooth comparison `A i`;
5. **bundle equivalence.**  The internal Lorentz bundle and the tangent bundle are
   equivalent: a fibrewise linear equivalence whose total-space maps are continuous both
   ways, i.e. a homeomorphism of total spaces covering `id_M`;
6. **the metric.**  `B_𝒮` transports to a symmetric, nondegenerate Lorentz metric whose
   coefficient functions are `C^∞` in every chart and which transforms as a tensor;
7. **orientation and time orientation**, at the exact level proved: the solder frame changes
   have determinant `1`, the future cone field is chart-independent, and each chart carries a
   `C^∞` future-directed unit timelike field (a *global* smooth representative is not
   claimed);
8. **the frame cocycle.**  The tangent Lorentz frame transition cocycle equals the projected
   native Lorentz cocycle;
9. **the Spin endpoint.**  The native Spin cocycle is a lift of that cocycle along the
   intrinsic double cover, at the *topological* regularity level (its own continuity).

Nothing about `w₁`, `w₂`, Stiefel–Whitney classes, connections, curvature, torsion, field
equations or quantization is used or claimed. -/
theorem smooth_solder_tangent_certificate (h : B.SmoothGluing) :
    -- 1. the emergent smooth four-manifold
    IsManifold localModelI (⊤ : ℕ∞) (Space B) ∧
    Module.finrank ℝ LocalModel = 4 ∧
    -- 2. the genuine tangent transitions are the derivatives of the actual atlas
    (∀ (i j : ι) (hi : Nonempty (B.D i : Set LocalModel))
        (hj : Nonempty (B.D j : Set LocalModel))
        (mi : B.pieceChart i hi ∈ atlas LocalModel (Space B))
        (mj : B.pieceChart j hj ∈ atlas LocalModel (Space B))
        (y : LocalModel) (hy : y ∈ B.W i j),
      (tangentCore h).coordChange ⟨B.pieceChart i hi, mi⟩ ⟨B.pieceChart j hj, mj⟩
          (B.chart i ⟨y, B.W_subset i j hy⟩)
        = B.tangentTransitionMap i j y) ∧
    -- 3. the internal Lorentz transitions are the projected native Spin transitions
    (∀ (i j : ι) (x : Space B) (v : LocalModel),
      (internalLorentzBundleCore S).coordChange i j x v
        = projectedLorentzTransition S j i x v) ∧
    -- 4. the regular solder intertwines them, with smooth local representatives
    (∀ (i : ι) (hi : Nonempty (B.D i : Set LocalModel))
        (mi : B.pieceChart i hi ∈ atlas LocalModel (Space B)),
      (∀ x ∈ B.chartRange i, ∀ v : LocalModel,
        coreRep (internalLorentzBundleCore S) (tangentCore h) (E.fiberEquiv h) i
            ⟨B.pieceChart i hi, mi⟩ x v = E.A i (B.pieceCoord i x) v) ∧
      ContDiffOn ℝ (⊤ : ℕ∞)
        (fun y => ((E.A i y : LocalModel →L[ℝ] LocalModel))) (B.D i)) ∧
    -- 5. the bundle equivalence with the genuine tangent bundle
    Nonempty (CoreBundleEquiv (internalLorentzBundleCore S) (tangentCore h)) ∧
    (∀ p : (internalLorentzBundleCore S).TotalSpace,
      ((E.toCoreBundleEquiv h).toHomeomorph p).proj = p.proj) ∧
    -- 6. the smooth Lorentz metric
    (∀ i u v, ContDiffOn ℝ (⊤ : ℕ∞) (fun y => E.metricCoeff i y u v) (B.D i)) ∧
    (∀ i y u v, E.metricCoeff i y u v = E.metricCoeff i y v u) ∧
    (∀ i y, ∀ u ≠ (0 : LocalModel), ∃ v, E.metricCoeff i y u v ≠ 0) ∧
    (∀ i j, ∀ y ∈ B.W i j, ∀ u v,
      E.metricCoeff j (B.φ i j y) (B.tangentTransitionMap i j y u)
          (B.tangentTransitionMap i j y v) = E.metricCoeff i y u v) ∧
    -- 7. orientation and time orientation, at the exact level proved
    (∀ i j, ∀ y ∈ B.W i j, LinearMap.det (E.frameChange i j y) = 1) ∧
    (∀ i j, ∀ y ∈ B.W i j, ∀ u,
      u ∈ E.futureCone i y ↔ B.tangentTransitionMap i j y u ∈ E.futureCone j (B.φ i j y)) ∧
    (∀ i, ContDiffOn ℝ (⊤ : ℕ∞) (E.timeField i) (B.D i)) ∧
    (∀ i y, E.timeField i y ∈ E.futureCone i y) ∧
    -- 8. the tangent frame cocycle is the projected native Lorentz cocycle
    (∀ i j, ∀ x ∈ (emergentCover B).overlap₂ i j,
      (E.toTangentSolderData h).toLorentzTangentFrameData.transition i j x
        = (project internalSpinProjection S).g i j x) ∧
    -- 9. the native Spin cocycle is a (topological) Spin lift of it
    Nonempty (SpinFrameStructure (E.toTangentSolderData h).toLorentzTangentFrameData) :=
  ⟨isManifold_of_smoothGluing h,
   finrank_localModel,
   fun _ _ hi hj mi mj _ hy =>
     BaseGluingData.tangentTransition_eq_derivative_baseTransition B h hi hj mi mj hy,
   fun _ _ x v => internalLorentzBundleCore_coordChange S _ _ x v,
   fun i hi mi => ⟨fun _ hx v => E.coreRep_eq h i hi mi hx v, E.contDiffOn_A i⟩,
   ⟨E.toCoreBundleEquiv h⟩,
   fun _ => rfl,
   fun i u v => E.contDiffOn_metricCoeff i u v,
   fun i y u v => E.metricCoeff_symm i y u v,
   fun i y _ hu => E.metricCoeff_nondegenerate i y hu,
   fun i j _ hy u v => E.metricCoeff_transform i j hy u v,
   fun i j _ hy => E.frameChange_det i j hy,
   fun i j _ hy u => E.futureCone_transform i j hy u,
   fun i => E.contDiffOn_timeField i,
   fun i y => E.timeField_mem_futureCone i y,
   fun _ _ _ hx => (E.toTangentSolderData h).projected_eq_tangentFrameTransition _ _ hx,
   ⟨(E.toTangentSolderData h).nativeSpin_to_tangentSpinFrameStructure⟩⟩

end SmoothTangentSolderData

end SpinNative

end

/-! ## Axiom audit -/

#print axioms SpinNative.SmoothTangentSolderData.spin_endpoint_topological
#print axioms SpinNative.SmoothTangentSolderData.smooth_solder_tangent_certificate
