import RequestProject.Spine.E2.AtlasChange.AtlasChangeLiftability

/-!
# Task 32, Package C: the mandatory Task-XXXI good/bad control

**Items 25–33, and the negative controls 114–117.**

The Task-XXXI negative system is realized by the *constant* metric-oriented rank-three family
`badFamilyBase` over the visible model group, presented by a two-chart ordinary atlas
(`badTriv₀`, `badTriv₁`).  This module exhibits, on the **same** bare family and the **same**
indexed cover, the trivial presentation generated by `badTriv₀` alone, and proves:

* both presentations have the same underlying bare metric-oriented family (item 27);
* they are related by an ordinary chart gauge, with the explicit values
  `h₀(b) = 1`, `h₁(b) = b` (items 28–29);
* the trivial presentation is directly liftable / Task-XXXI neutral (item 30);
* the two-chart presentation is **not** (item 31, inherited from Task XXXI);
* hence `fixedPresentation_neutrality_not_familyInvariant` (item 32) — the key control
  separating presentation-level from geometry-level notions;
* the ordinary chart gauge `h₁(b) = b` itself has **no** global internal lift (item 59), which
  is exactly why fixed-atlas neutrality changes under this presentation transformation;
* the bare family is family-level liftable (items 52–54), so the Task-XXXI non-neutrality is
  **not** a family obstruction (Package Q, item 107);
* the converse of the refinement theorem is **refuted**: an ordinary refinement of the bad
  atlas is directly liftable although the bad atlas is not (Package H, item 62).
-/

set_option synthInstance.maxHeartbeats 400000
set_option maxHeartbeats 1000000

namespace NullSectorTask32

open NullSectorTask26 NullSectorTask27 NullSectorTask28 NullSectorTask29 NullSectorTask31
open NullSectorTask31.Examples

namespace GoodBad

variable {L : Type} [Group L] [TopologicalSpace L] [IsTopologicalGroup L]
  (P : InternalProjection L GvisModel)

/-! ## The two presentations of one bare family -/

/-- **PACKAGE C (item 26).**  The trivial/global presentation generated by `badTriv₀`, on the
same `Bool`-indexed cover as the Task-XXXI presentation. -/
noncomputable def trivialAtlas : OrdinaryAtlasPresentation badFamilyBase Bool where
  U := fun _ => Set.univ
  isOpen_U := fun _ => isOpen_univ
  cover := fun b => ⟨false, Set.mem_univ b⟩
  triv := fun _ => badTriv₀
  continuousOn_overlap := fun _ _ => continuousOn_badOverlap false false

/-- **PACKAGE C (item 26).**  The two-chart Task-XXXI presentation generated by `badTriv₀`
and `badTriv₁`. -/
noncomputable def badAtlas : OrdinaryAtlasPresentation badFamilyBase Bool :=
  badFamily.atlas

/-- **PACKAGE C (item 27), REQUIRED ENDPOINT.**  Both presentations present the **same**
underlying bare metric-oriented rank-three family. -/
theorem same_underlying_bare_family :
    bareOf (presentedFamily badFamilyBase trivialAtlas) = bareOf badFamily := rfl

theorem badAtlas_eq_presentation : badAtlas = presentationOf badFamily := rfl

/-! ## The ordinary chart change relating them -/

/-- **PACKAGE C (item 28).**  The joint ordinary atlas containing both presentations: chart
label `false` is the global identity trivialization, chart label `true` is the Task-XXXI
two-chart atlas. -/
noncomputable def goodBadJoint : JointOrdinaryAtlas badFamilyBase Bool Bool where
  U := fun _ => Set.univ
  isOpen_U := fun _ => isOpen_univ
  cover := fun b => ⟨false, Set.mem_univ b⟩
  triv := fun s i => badTriv (s && i)
  continuousOn_overlap := fun p q => continuousOn_badOverlap (p.1 && p.2) (q.1 && q.2)

@[simp] theorem goodBadJoint_atlas_false : goodBadJoint.atlas false = trivialAtlas := rfl

@[simp] theorem goodBadJoint_atlas_true : goodBadJoint.atlas true = badAtlas := rfl

/-- **PACKAGE C (item 29), REQUIRED ENDPOINT.**  `h₀(b) = 1`. -/
theorem gauge_zero (b : ↥(goodBadJoint.U false)) :
    goodBadJoint.gauge false true false b = 1 :=
  transitionOn_self badTriv₀ _

/-- **PACKAGE C (item 29), REQUIRED ENDPOINT.**  `h₁(b) = b`: the second chart gauge is the
base point itself, exactly the Task-XXXI control `h₁(b) = b`. -/
theorem gauge_one (b : ↥(goodBadJoint.U true)) :
    goodBadJoint.gauge false true true b = (b : ↥GvisModel) := by
  refine Subtype.ext (LinearIsometryEquiv.ext fun m => ?_)
  show ((b : ↥GvisModel) : Model ≃ₗᵢ[ℝ] Model)
      ((LinearIsometryEquiv.refl ℝ Model).symm m)
    = ((b : ↥GvisModel) : Model ≃ₗᵢ[ℝ] Model) m
  rfl

/-- **PACKAGE C (item 28), REQUIRED ENDPOINT.**  The two presentations are ordinary
chart-gauge equivalent, and hence (Package B) their ordinary transition systems are related by
the exact conjugation law. -/
theorem ordinaryChartGaugeEquivalent_trivial_bad :
    OrdinaryChartGaugeEquivalent trivialAtlas badAtlas :=
  goodBadJoint.ordinaryChartGaugeEquivalent false true

/-- **PACKAGE E (item 46).**  The generated ordinary atlas equivalence identifies the two
Task-XXXI presentations of the constant family. -/
theorem ordinaryAtlasEquivalent_trivial_bad :
    OrdinaryAtlasEquivalent (F := badFamilyBase) ⟨Bool, trivialAtlas⟩ ⟨Bool, badAtlas⟩ :=
  OrdinaryAtlasEquivalent.gauge _ _ ordinaryChartGaugeEquivalent_trivial_bad

/-- **PACKAGE C.**  The exact ordinary transition gauge law for this pair. -/
theorem transition_gauge_law_trivial_bad (i j : Bool) (b : ↥GvisModel)
    (h : b ∈ trivialAtlas.U i ∩ trivialAtlas.U j) :
    badAtlas.transitionFun i j ⟨b, h⟩
      = goodBadJoint.gauge false true j ⟨b, h.2⟩ * trivialAtlas.transitionFun i j ⟨b, h⟩ *
        (goodBadJoint.gauge false true i ⟨b, h.1⟩)⁻¹ :=
  goodBadJoint.transition_gauge_law false true i j b h

/-! ## Direct liftability of the two presentations -/

theorem trivialAtlas_transitions_trivial (i j : Bool)
    (x : ↥((ofOrdinary (ordinarySystem trivialAtlas)).U i ∩
      (ofOrdinary (ordinarySystem trivialAtlas)).U j)) :
    (ofOrdinary (ordinarySystem trivialAtlas)).g i j x = 1 :=
  transitionOn_self badTriv₀ _

/-- **PACKAGE C (item 30), REQUIRED ENDPOINT.**  The trivial presentation is directly
liftable. -/
theorem trivialAtlas_directAtlasLiftable : DirectAtlasLiftable P trivialAtlas :=
  internalLiftable_of_transitions_trivial trivialAtlas_transitions_trivial

/-- **PACKAGE C (item 31), REQUIRED ENDPOINT.**  The Task-XXXI two-chart presentation is
**not** directly liftable.  Inherited verbatim from Task XXXI. -/
theorem badAtlas_not_directAtlasLiftable
    (hP : ¬ P.HasContinuousInternalRep (id : GvisModel → _) Set.univ) :
    ¬ DirectAtlasLiftable P badAtlas :=
  badFamily_not_internalLiftable P hP

/-- **PACKAGE C (item 30).**  Neutrality of the trivial presentation's Task-XXXI defect. -/
theorem trivialAtlas_neutral :
    IsNeutralGlobalKernelDefect P (ofOrdinary (ordinarySystem trivialAtlas)) :=
  internalLiftable_iff_globalKernelDefect_neutral.1 (trivialAtlas_directAtlasLiftable P)

/-- **PACKAGE C (item 31).**  Non-neutrality of the bad presentation's Task-XXXI defect. -/
theorem badAtlas_not_neutral
    (hP : ¬ P.HasContinuousInternalRep (id : GvisModel → _) Set.univ) :
    ¬ IsNeutralGlobalKernelDefect P (ofOrdinary (ordinarySystem badAtlas)) :=
  badFamily_not_isNeutralGlobalKernelDefect P hP

/-- **PACKAGE C (item 32), REQUIRED ENDPOINT
`fixedPresentation_neutrality_not_familyInvariant`.**  One and the same underlying bare frame
family admits one fixed ordinary presentation that is neutral/liftable and another that is
non-neutral/non-liftable.  This is negative control 114/116 in formal form. -/
theorem fixedPresentation_neutrality_not_familyInvariant
    (hP : ¬ P.HasContinuousInternalRep (id : GvisModel → _) Set.univ) :
    ∃ (ι₀ ι₁ : Type) (A₀ : OrdinaryAtlasPresentation badFamilyBase ι₀)
      (A₁ : OrdinaryAtlasPresentation badFamilyBase ι₁),
      (DirectAtlasLiftable P A₀ ∧
        IsNeutralGlobalKernelDefect P (ofOrdinary (ordinarySystem A₀))) ∧
      (¬ DirectAtlasLiftable P A₁ ∧
        ¬ IsNeutralGlobalKernelDefect P (ofOrdinary (ordinarySystem A₁))) :=
  ⟨Bool, Bool, trivialAtlas, badAtlas,
    ⟨trivialAtlas_directAtlasLiftable P, trivialAtlas_neutral P⟩,
    ⟨badAtlas_not_directAtlasLiftable P hP, badAtlas_not_neutral P hP⟩⟩

/-! ## The ordinary chart gauge has no global internal lift -/

/-- **PACKAGE G (item 59), REQUIRED ENDPOINT.**  The Task-XXXI good/bad ordinary chart gauge
does **not** satisfy the internal-lift condition of `InternallyLiftableOrdinaryGauge`: a
continuous internal representative of `h₁(b) = b` on the whole chart domain would be a
continuous global internal representative of the identity of the visible group, refuted by the
certified layers.  This explains mathematically why fixed-atlas neutrality changes under this
presentation transformation. -/
theorem goodBadGauge_not_internallyLiftable
    (hP : ¬ P.HasContinuousInternalRep (id : GvisModel → _) Set.univ) :
    ¬ InternallyLiftableOrdinaryGauge P
      (ofOrdinary (ordinarySystem trivialAtlas)) (goodBadJoint.gauge false true) := by
  rintro ⟨H, hHc, hHp⟩
  refine hP ⟨fun b => H true ⟨b, Set.mem_univ _⟩, ?_, ?_⟩
  · exact continuousOn_univ.2 ((hHc true).comp (Continuous.subtype_mk continuous_id _))
  · intro b _
    exact (hHp true ⟨b, Set.mem_univ _⟩).trans (gauge_one ⟨b, Set.mem_univ _⟩)

/-! ## Family level: the constant Task-XXXI family is liftable -/

/-- **PACKAGE F (items 52–53), REQUIRED ENDPOINT.**  The bare geometry underlying the
Task-XXXI bad family is family-level liftable, witnessed by its trivial presentation. -/
theorem badFamilyBase_familyLiftable : FamilyLiftable.{0, 0, 0} P badFamilyBase :=
  familyLiftable_of_directAtlasLiftable P (trivialAtlas_directAtlasLiftable P)

/-- **PACKAGE F (item 54), REQUIRED ENDPOINT — one of the principal Task-XXXII endpoints.**
`¬ DirectAtlasLiftable badAtlas` **and** `FamilyLiftable underlyingBadFamily`. -/
theorem badAtlas_not_liftable_and_family_liftable
    (hP : ¬ P.HasContinuousInternalRep (id : GvisModel → _) Set.univ) :
    ¬ DirectAtlasLiftable P badAtlas ∧ FamilyLiftable.{0, 0, 0} P badFamilyBase :=
  ⟨badAtlas_not_directAtlasLiftable P hP, badFamilyBase_familyLiftable P⟩

/-! ## Package H: the converse of the refinement theorem is refuted -/

/-- An ordinary cover refinement of the bad atlas which simply reindexes onto the first
chart.  It satisfies every requirement of `OrdinaryCoverRefinement`. -/
noncomputable def badRefinement : OrdinaryCoverRefinement badAtlas Unit where
  r := fun _ => false
  V := fun _ => Set.univ
  isOpen_V := fun _ => isOpen_univ
  cover_V := fun b => ⟨(), Set.mem_univ b⟩
  subset := fun _ => subset_refl _

theorem badRefinement_transitions_trivial (i j : Unit)
    (x : ↥((ofOrdinary (ordinarySystem badRefinement.atlas)).U i ∩
      (ofOrdinary (ordinarySystem badRefinement.atlas)).U j)) :
    (ofOrdinary (ordinarySystem badRefinement.atlas)).g i j x = 1 :=
  transitionOn_self _ _

/-- **PACKAGE H (item 62), REQUIRED NEGATIVE RESULT.**  The converse of
`directAtlasLiftable_refine` is **false**: an ordinary cover refinement of the Task-XXXI bad
atlas is directly liftable, while the bad atlas itself is not. -/
theorem directLiftability_refinement_converse_refuted
    (hP : ¬ P.HasContinuousInternalRep (id : GvisModel → _) Set.univ) :
    DirectAtlasLiftable P badRefinement.atlas ∧ ¬ DirectAtlasLiftable P badAtlas :=
  ⟨internalLiftable_of_transitions_trivial badRefinement_transitions_trivial,
    badAtlas_not_directAtlasLiftable P hP⟩

/-- **PACKAGE H (item 65).**  Consequently the bad atlas *is* refinement liftable, although it
is not directly liftable. -/
theorem badAtlas_refinementLiftable : RefinementLiftable.{0, 0, 0} P badAtlas :=
  ⟨Unit, badRefinement,
    internalLiftable_of_transitions_trivial badRefinement_transitions_trivial⟩

/-! ## Package Q: the exact status of the Task-XXXI bad control after repair -/

/-- **PACKAGE Q (items 107–108), REQUIRED FORMAL THEOREM CHAIN.**  In one statement:

* the bad fixed atlas is **not** directly liftable;
* the trivial atlas on the **same** bare family is directly liftable;
* the two are related by an ordinary chart gauge;
* the bare constant family is family-level liftable;
* therefore Task-XXXI non-neutrality is **not** itself a family obstruction. -/
theorem task31_bad_control_repaired
    (hP : ¬ P.HasContinuousInternalRep (id : GvisModel → _) Set.univ) :
    (¬ DirectAtlasLiftable P badAtlas) ∧
    DirectAtlasLiftable P trivialAtlas ∧
    OrdinaryChartGaugeEquivalent trivialAtlas badAtlas ∧
    bareOf (presentedFamily badFamilyBase trivialAtlas) = bareOf badFamily ∧
    FamilyLiftable.{0, 0, 0} P badFamilyBase :=
  ⟨badAtlas_not_directAtlasLiftable P hP, trivialAtlas_directAtlasLiftable P,
    ordinaryChartGaugeEquivalent_trivial_bad, same_underlying_bare_family,
    badFamilyBase_familyLiftable P⟩

end GoodBad

end NullSectorTask32
