import Mathlib.AlgebraicTopology.SimplicialSet.Boundary
import RequestProject.Spine.AlgebraicTopology.RelativeChains

/-!
# The standard cell pair

The single definition `SpineTask14.stdCellPair r`: the realized standard cell pair
`(|Δ[r]|, |∂Δ[r]|)`, as a map of singular simplicial sets, so that the generic relative chain
complex of `RequestProject.Spine.AlgebraicTopology.RelativeChains` can be applied to it.

Together with it, the two blocker-B1 propositions `StandardCellPairAcyclic` and
`StandardCellPairTop`, which speak only about the relative homology of this pair.

It is a definition, and it is kept in a module of its own so that the modules which only need
to *name* the standard cell pair — the blocker statements, the singular cell-family target map
— do not have to import the standard-cell homology, generator or excision proofs, nor the
canonical comparison `relJ`.
-/

noncomputable section

open CategoryTheory Limits Opposite Simplicial SSet

universe u

namespace SpineTask14

/-- The standard cell pair `(|Δ[r]|, |∂Δ[r]|)`, as a map of singular simplicial sets. -/
abbrev stdCellPair (r : ℕ) :
    TopCat.toSSet.obj (SSet.toTop.obj ((∂Δ[r] : (Δ[r] : SSet.{u}).Subcomplex) : SSet.{u})) ⟶
      TopCat.toSSet.obj (SSet.toTop.obj (Δ[r] : SSet.{u})) :=
  TopCat.toSSet.map (SSet.toTop.map (∂Δ[r] : (Δ[r] : SSet.{u}).Subcomplex).ι)

/-- **Blocker B1, vanishing part.**  `H_q^{sing}(|Δ[r]|,|∂Δ[r]|;ℤ₂) = 0` for `q ≠ r`.

*Not provable in the pin*: the pinned Mathlib has no relative singular homology (supplied here
by WP7), no excision, no barycentric subdivision, and no computation of the homology of a
sphere; and it does not identify `|∂Δ[r]|` with `𝕊 (r-1)` or `|Δ[r]|` with `𝔻 r`. -/
def StandardCellPairAcyclic (r : ℕ) : Prop :=
  ∀ q, q ≠ r → IsZero ((relChainCx (stdCellPair.{u} r)).homology q)

/-- **Blocker B1, top part.**  `H_r^{sing}(|Δ[r]|,|∂Δ[r]|;ℤ₂) ≅ ℤ₂`, generated by the class of
the identity singular `r`-simplex of `|Δ[r]|`. -/
def StandardCellPairTop (r : ℕ) : Prop :=
  Nonempty ((relChainCx (stdCellPair.{u} r)).homology r ≅ ModuleCat.of (ZMod 2) (ULift.{u} (ZMod 2)))

end SpineTask14
