import RequestProject.Spine.AlgebraicTopology.SimplicialChains
import RequestProject.Spine.Cech.Cohomology
import RequestProject.Spine.Cohomology.HomotopyInvariance
import RequestProject.Spine.GoodCover.Presimplicial

/-!
# Task 12 : acyclic-models applicability probes

This module contains the **formal part** of the Task-12 route-validation audit
(`TASK12_ACYCLIC_MODELS_APPLICABILITY.md`).  Nothing here proves any part of the geometric
comparison, and nothing in the production Spine depends on this file.  Its purpose is to
settle, inside the pinned environment and at theorem level, whether the classical
Acyclic-Models machinery can construct the *reverse* comparison map

`R : C_*^sing(|K|;ℤ₂) ⟶ C_*^simp(K;ℤ₂)`

for the two functors that Tasks 9–11 actually fixed,

`F(K) = C_*^simp(K;ℤ₂) = NerveGeom.SSetChain K`  and
`G(K) = C_*^sing(|K|;ℤ₂) = NerveGeom.SSetChain (Sing |K|)`.

## What is proved here

* **`freeOnStdSimplex_bijective`** (`FREE_ON_MODELS` for `F`) — for *every* simplicial set `K`
  and every degree `q`, the map `(Δ[q] ⟶ K) → K_q`, `f ↦ f(ι_q)`, is a bijection, and the
  corresponding singletons span the degree-`q` chain module.  So `F_q` is the free `ℤ₂`-module
  on `Hom_{SSet}(Δ[q], K)`: `F` is free on the standard-simplex models.
* **`singularGenerator_not_surjective`** (`COUNTEREXAMPLE`, `MODEL_CLASS_REJECTED` for `G`) —
  for `K = Δ[1]` and every degree `q`, the map `(Δ[q] ⟶ K) → Sing_q|K|` is *not* surjective:
  its source is finite, its target is uncountable.  Hence `G_q(Δ[1])` is not even generated by
  the standard-simplex models, let alone free on them.
* **`no_countable_family_generates`** — more is true and it kills every *countable* model
  class: no countable family of singular simplices spans `G_q(Δ[1])`.  Together with
  **`finite_hom_to_stdSimplex`** (a simplicial map into `Δ[m]` is determined by its values on
  vertices, so a model with finitely many vertices has only finitely many maps into `Δ[1]`)
  this rejects `{Δ[n]}`, all finite simplicial sets, all contractible finite simplicial sets,
  and any other countable class of models with finitely many vertices, *as free model classes
  for `G`*.
* **`stdSimplex_chain_acyclic`** (`ACYCLIC_ON_MODELS` for `F`) — an explicit natural cone
  contraction shows `H_{>0}(F(Δ[n])) = 0`.
* **`realization_stdSimplex_contractible`** — `|Δ[n]|` is contractible (it is homeomorphic to
  a nonempty convex set), the topological input for `H_{>0}(G(Δ[n])) = 0`; combined with the
  Task-8 homotopy invariance this gives **`singularCohomology_stdSimplex_vanishing`**, the
  acyclicity of `G` on the standard-simplex models in the project's own singular mod-2 theory.
* **`boundary2_homology_one_ne_zero`** (`COUNTEREXAMPLE`) — the finite simplicial set `∂Δ[2]`
  carries a `1`-cycle that is not a boundary, so **finite simplicial sets are not an acyclic
  model class**, in either variance.
* **`generator_eq_unit_comp`** (`WP8`, circularity) — the standard-simplex generator of a
  singular simplex is `yonedaEquiv (f ≫ η_K)`: passing through the adjunction returns exactly
  the unit `η_K` whose comparison is the open problem, so the adjunction repairs nothing.
* **`acyclicModels_forward_only`** — the conjunction of the two decisive facts, which is the
  Task-12 verdict `ONLY_FORWARD_MAP_F_TO_G`.

All statements are in universe `0`; the failure exhibited is a failure already there, so no
universe generality is lost.
-/

universe u

namespace SpineTask12

open CategoryTheory Simplicial Opposite SimplexCategory NerveGeom

/-! ## Generic facts about free `ℤ₂`-modules on a set -/

/-- The singletons `single s 1` span the free `ℤ₂`-module on `S`. -/
theorem span_singles_top {S : Type} :
    Submodule.span (ZMod 2) (Set.range fun s : S => Finsupp.single s (1 : ZMod 2)) = ⊤ := by
  rw [eq_top_iff]
  rintro x -
  induction x using Finsupp.induction_linear with
  | zero => exact zero_mem _
  | add a b ha hb => exact add_mem ha hb
  | single a c =>
      have h : Finsupp.single a c = c • Finsupp.single a (1 : ZMod 2) := by simp
      rw [h]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨a, rfl⟩)

/-- **Generation forces surjectivity.**  If the singletons indexed by a family `incl : T → S`
span the whole free `ℤ₂`-module on `S`, then `incl` is surjective.  This is the precise sense
in which "the model images generate" is a statement about the *set* of generators, and it is
what makes the counterexamples below decisive. -/
theorem surjective_of_span_singles {S T : Type} (incl : T → S)
    (h : Submodule.span (ZMod 2) (Set.range fun t => Finsupp.single (incl t) (1 : ZMod 2)) = ⊤) :
    Function.Surjective incl := by
  intro s
  by_contra hs
  push_neg at hs
  have hker :
      Submodule.span (ZMod 2) (Set.range fun t => Finsupp.single (incl t) (1 : ZMod 2))
        ≤ LinearMap.ker (Finsupp.lapply (M := ZMod 2) s) := by
    refine Submodule.span_le.2 ?_
    rintro _ ⟨t, rfl⟩
    simp [LinearMap.mem_ker, hs t]
  rw [h] at hker
  have h2 : Finsupp.single s (1 : ZMod 2) ∈ LinearMap.ker (Finsupp.lapply (M := ZMod 2) s) :=
    hker Submodule.mem_top
  rw [LinearMap.mem_ker] at h2
  simp at h2

/-! ## WP3, `F` : the simplicial chain functor is free on the standard simplices -/

/-- **`FREE_ON_MODELS` for `F`, part 1 (Yoneda).**  Simplicial `q`-simplices of `K` are exactly
the simplicial maps `Δ[q] ⟶ K`. -/
theorem freeOnStdSimplex_bijective (K : SSet.{0}) (q : ℕ) :
    Function.Bijective (fun f : (Δ[q] : SSet.{0}) ⟶ K => SSet.yonedaEquiv f) :=
  SSet.yonedaEquiv.bijective

/-- **`FREE_ON_MODELS` for `F`, part 2.**  The degree-`q` simplicial chain module of `K` is the
free `ℤ₂`-module on `Hom_{SSet}(Δ[q], K)`. -/
noncomputable def simpChainModelBasis (K : SSet.{0}) (q : ℕ) :
    (((Δ[q] : SSet.{0}) ⟶ K) →₀ ZMod 2) ≃ₗ[ZMod 2] SSetChain K q :=
  Finsupp.domLCongr SSet.yonedaEquiv

/-- **`FREE_ON_MODELS` for `F`, part 3.**  The basis element attached to a model map
`f : Δ[q] ⟶ K` is the image under `F(f)` of the fundamental chain of the model, which is the
form the Acyclic-Models theorem requires. -/
theorem simpChain_model_generator (K : SSet.{0}) (q : ℕ) (f : (Δ[q] : SSet.{0}) ⟶ K) :
    sSetChainMap f q (Finsupp.single (SSet.yonedaEquiv (𝟙 (Δ[q] : SSet.{0}))) 1)
      = Finsupp.single (SSet.yonedaEquiv f) (1 : ZMod 2) := by
  rw [sSetChainMap_single]
  exact congrArg (fun x => Finsupp.single x (1 : ZMod 2))
    (SSet.yonedaEquiv_comp (𝟙 (Δ[q] : SSet.{0})) f).symm

/-- **`FREE_ON_MODELS` for `F`, part 4.**  Consequently the model images span. -/
theorem simpChain_model_span (K : SSet.{0}) (q : ℕ) :
    Submodule.span (ZMod 2)
        (Set.range fun f : (Δ[q] : SSet.{0}) ⟶ K =>
          Finsupp.single (SSet.yonedaEquiv f) (1 : ZMod 2)) = ⊤ := by
  have hrange : (Set.range fun f : (Δ[q] : SSet.{0}) ⟶ K =>
        Finsupp.single (SSet.yonedaEquiv f) (1 : ZMod 2))
      = Set.range fun s : K.obj (op ⦋q⦌) => Finsupp.single s (1 : ZMod 2) := by
    ext x
    constructor
    · rintro ⟨f, rfl⟩; exact ⟨SSet.yonedaEquiv f, rfl⟩
    · rintro ⟨s, rfl⟩; exact ⟨SSet.yonedaEquiv.symm s, by simp⟩
  rw [hrange, span_singles_top]

/-! ## WP3/WP8, `G` : the standard-simplex generators of singular simplices -/

/-- The generator of `G_q(K)` attached to a model map `f : Δ[q] ⟶ K`: the singular `q`-simplex
of `|K|` obtained by applying `G(f)` to the fundamental chain of the model.  Concretely it is
the image of the simplicial `q`-simplex `f(ι_q)` under the unit `η_K`. -/
noncomputable def singularGenerator (K : SSet.{0}) (q : ℕ) (f : (Δ[q] : SSet.{0}) ⟶ K) :
    Mod2Cohomology.Simplex (SSet.toTop.obj K) q :=
  (sSetTopAdj.unit.app K).app (op ⦋q⦌) (SSet.yonedaEquiv f)

/-- **WP8, the circularity.**  The standard-simplex generator of `G` is `η_K ∘ f` read through
Yoneda.  Passing a singular simplex through the realisation/singular adjunction turns it into a
simplicial map `Δ[q] ⟶ Sing|K|`; the generators coming from the models are exactly those that
factor through `η_K : K ⟶ Sing|K|`.  So the adjunction does *not* repair the missing freeness:
the discrepancy between the two sides is precisely the unresolved unit. -/
theorem generator_eq_unit_comp (K : SSet.{0}) (q : ℕ) (f : (Δ[q] : SSet.{0}) ⟶ K) :
    singularGenerator K q f = SSet.yonedaEquiv (f ≫ sSetTopAdj.unit.app K) :=
  (SSet.yonedaEquiv_comp f (sSetTopAdj.unit.app K)).symm

/-! ## The realisation of `Δ[1]` is uncountable -/

/-- The unit interval, injected into the geometric `1`-simplex. -/
noncomputable def segPoint (t : Set.Icc (0 : ℝ) 1) : stdSimplex ℝ (Fin 2) :=
  ⟨![t.1, 1 - t.1], by
    refine ⟨fun i => ?_, by simp [Fin.sum_univ_two]⟩
    fin_cases i
    · exact t.2.1
    · simpa using t.2.2⟩

theorem segPoint_injective : Function.Injective segPoint := by
  intro a b hab
  have h := congrFun (congrArg Subtype.val hab) 0
  simpa [segPoint, Subtype.ext_iff] using h

theorem not_countable_Icc : ¬ Countable (Set.Icc (0 : ℝ) 1) := by
  intro _
  have h2 : Cardinal.mk (Set.Icc (0 : ℝ) 1) ≤ Cardinal.aleph0 := Cardinal.mk_le_aleph0
  rw [Cardinal.mk_Icc_real (by norm_num)] at h2
  exact absurd h2 (not_le.mpr Cardinal.aleph0_lt_continuum)

/-- The realisation of `Δ[1]` is the geometric `1`-simplex, by Mathlib's `SSet.toTopSimplex`. -/
noncomputable def realizationOneHomeo :
    (SimplexCategory.toTop.{0}.obj ⦋1⦌ : Type) ≃ₜ (SSet.toTop.{0}.obj (Δ[1] : SSet.{0}) : Type) :=
  TopCat.homeoOfIso (SSet.toTopSimplex.{0}.app ⦋1⦌).symm

theorem not_countable_realization_one :
    ¬ Countable (SSet.toTop.{0}.obj (Δ[1] : SSet.{0}) : Type) := by
  intro _
  refine not_countable_Icc ?_
  exact Function.Injective.countable
    (f := fun t => realizationOneHomeo (ULift.up (segPoint t)))
    (fun a b hab => segPoint_injective
      (by simpa using congrArg ULift.down (realizationOneHomeo.injective hab)))

/-- Singular simplices of an uncountable space form an uncountable set (constant simplices
already do). -/
theorem not_countable_simplex {X : TopCat.{0}} (q : ℕ) (hX : ¬ Countable (X : Type)) :
    ¬ Countable (Mod2Cohomology.Simplex X q) := by
  intro _
  refine hX ?_
  obtain ⟨p⟩ : Nonempty (stdSimplex ℝ (Fin (q + 1))) := inferInstance
  refine Function.Injective.countable (f := fun x : X =>
    (X.toSSetObjEquiv (op ⦋q⦌)).symm (ContinuousMap.const _ x)) ?_
  intro a b hab
  have h := congrArg (fun s => (X.toSSetObjEquiv (op ⦋q⦌)) s) hab
  simp only [Equiv.apply_symm_apply] at h
  exact congrFun (congrArg (fun c => (c : C(_, X)).toFun) h) p

/-- **The master cardinality obstruction.**  No countable family of singular simplices of
`|Δ[1]|` is surjective, hence (by `surjective_of_span_singles`) no countable family generates
`G_q(Δ[1])`.  Every model class considered in the audit — standard simplices, finite simplicial
sets, contractible finite simplicial sets, simplex/boundary pairs, subdivisions — is a
countable class of models with finitely many maps into `Δ[1]`, so all of them fail. -/
theorem no_countable_family_generates (q : ℕ) {ι : Type} [Countable ι]
    (gen : ι → Mod2Cohomology.Simplex (SSet.toTop.obj (Δ[1] : SSet.{0})) q) :
    ¬ Function.Surjective gen := by
  intro hsurj
  exact not_countable_simplex q not_countable_realization_one hsurj.countable

/-! ## Maps into a standard simplex are determined by their vertices -/

/-- A simplicial map into `Δ[m]` is determined by its effect on vertices: `Δ[m]` is the nerve
of a linear order, so a simplex of it is determined by its vertex tuple. -/
theorem hom_stdSimplex_ext {L : SSet.{0}} {m : ℕ} (φ ψ : L ⟶ (Δ[m] : SSet.{0}))
    (h : ∀ x : L.obj (op ⦋0⦌), φ.app (op ⦋0⦌) x = ψ.app (op ⦋0⦌) x) : φ = ψ := by
  ext k x
  apply ULift.ext
  apply SimplexCategory.Hom.ext
  ext j
  have hnat : ∀ χ : L ⟶ (Δ[m] : SSet.{0}),
      χ.app (op ⦋0⦌) (L.map (SimplexCategory.const ⦋0⦌ (unop k) j).op x)
        = (Δ[m] : SSet.{0}).map (SimplexCategory.const ⦋0⦌ (unop k) j).op (χ.app k x) :=
    fun χ => congrFun (χ.naturality (SimplexCategory.const ⦋0⦌ (unop k) j).op) x
  have key := ((hnat φ).symm.trans (h _)).trans (hnat ψ)
  exact congrArg Fin.val
    (congrArg (fun y : (Δ[m] : SSet.{0}).obj (op ⦋0⦌) => y.down.toOrderHom 0) key)

/-- A model with finitely many vertices admits only finitely many maps into `Δ[m]`.  In
particular a *finite* simplicial set does. -/
theorem finite_hom_to_stdSimplex {L : SSet.{0}} (m : ℕ) [Finite (L.obj (op ⦋0⦌))] :
    Finite (L ⟶ (Δ[m] : SSet.{0})) :=
  Finite.of_injective (fun φ => fun x : L.obj (op ⦋0⦌) => φ.app (op ⦋0⦌) x)
    (fun _ _ hab => hom_stdSimplex_ext _ _ (congrFun hab))

/-! ## WP3, `G` : the standard-simplex models do **not** generate the singular chains -/

/-- **`COUNTEREXAMPLE` / `MODEL_CLASS_REJECTED`.**  For `K = Δ[1]` and every degree `q`, the
standard-simplex generators do not exhaust the singular `q`-simplices of `|K|`: there are only
finitely many simplicial maps `Δ[q] ⟶ Δ[1]`, but uncountably many continuous maps
`|Δ[q]| → |Δ[1]|`.  So `G` is **not free on the standard-simplex models**. -/
theorem singularGenerator_not_surjective (q : ℕ) :
    ¬ Function.Surjective (singularGenerator (Δ[1] : SSet.{0}) q) := by
  have : Finite ((Δ[q] : SSet.{0}) ⟶ (Δ[1] : SSet.{0})) := Finite.of_equiv _ SSet.yonedaEquiv.symm
  exact no_countable_family_generates q _

/-- The same statement in the module-theoretic form used by the Acyclic-Models hypothesis: the
model images do not even *span* `G_q(Δ[1])`. -/
theorem singularGenerator_not_spanning (q : ℕ) :
    Submodule.span (ZMod 2)
        (Set.range fun f : (Δ[q] : SSet.{0}) ⟶ (Δ[1] : SSet.{0}) =>
          Finsupp.single (singularGenerator (Δ[1] : SSet.{0}) q f) (1 : ZMod 2)) ≠ ⊤ :=
  fun h => singularGenerator_not_surjective q (surjective_of_span_singles _ h)

/-- Every countable model class whose models have finitely many vertices fails the freeness
hypothesis for `G` as well: `{Δ[n]}`, finite simplicial sets, contractible finite simplicial
sets, boundaries, subdivisions of standard simplices. -/
theorem countableFiniteModels_not_generating {M : Type} [Countable M] (mdl : M → SSet.{0})
    [∀ m, Finite ((mdl m).obj (op ⦋0⦌))] (q : ℕ)
    (gen : (Σ m : M, (mdl m ⟶ (Δ[1] : SSet.{0}))) →
      Mod2Cohomology.Simplex (SSet.toTop.obj (Δ[1] : SSet.{0})) q) :
    ¬ Function.Surjective gen := by
  have : ∀ m : M, Finite (mdl m ⟶ (Δ[1] : SSet.{0})) := fun m => finite_hom_to_stdSimplex 1
  have : ∀ m : M, Countable (mdl m ⟶ (Δ[1] : SSet.{0})) := fun m => Finite.to_countable
  exact no_countable_family_generates q gen

/-! ## WP3, acyclicity of `F` on the standard simplices : the cone contraction -/

/-- The cone on a simplex of `Δ[n]`: prepend the vertex `0`. -/
def coneHom {q n : ℕ} (f : ⦋q⦌ ⟶ ⦋n⦌) : ⦋q + 1⦌ ⟶ ⦋n⦌ :=
  SimplexCategory.mkHom
    { toFun := fun k => Fin.cases 0 (fun k' => f.toOrderHom k') k
      monotone' := by
        intro a b hab
        induction a using Fin.cases with
        | zero => simp
        | succ a' =>
          induction b using Fin.cases with
          | zero => simp only [Fin.le_def, Fin.val_zero, Fin.val_succ] at hab; omega
          | succ b' =>
            simp only [Fin.cases_succ]
            exact f.toOrderHom.monotone (by simpa using hab) }

theorem coneHom_apply_zero {q n : ℕ} (f : ⦋q⦌ ⟶ ⦋n⦌) : (coneHom f).toOrderHom 0 = 0 := rfl

theorem coneHom_apply_succ {q n : ℕ} (f : ⦋q⦌ ⟶ ⦋n⦌) (k : Fin (q + 1)) :
    (coneHom f).toOrderHom k.succ = f.toOrderHom k := rfl

/-- `d₀` of a cone is the original simplex. -/
theorem cone_face_zero {q n : ℕ} (f : ⦋q⦌ ⟶ ⦋n⦌) : SimplexCategory.δ 0 ≫ coneHom f = f := by
  apply SimplexCategory.Hom.ext
  ext k
  show ((coneHom f).toOrderHom ((SimplexCategory.δ 0).toOrderHom k) : ℕ) = _
  have h : (SimplexCategory.δ (0 : Fin (q + 2))).toOrderHom k = k.succ := by
    show Fin.succAbove 0 k = k.succ
    simp
  rw [h, coneHom_apply_succ]

/-- The remaining faces of a cone are the cones of the faces. -/
theorem cone_face_succ {p n : ℕ} (f : ⦋p + 1⦌ ⟶ ⦋n⦌) (i : Fin (p + 2)) :
    SimplexCategory.δ i.succ ≫ coneHom f = coneHom (SimplexCategory.δ i ≫ f) := by
  apply SimplexCategory.Hom.ext
  ext k
  show ((coneHom f).toOrderHom ((SimplexCategory.δ i.succ).toOrderHom k) : ℕ)
      = ((coneHom (SimplexCategory.δ i ≫ f)).toOrderHom k : ℕ)
  induction k using Fin.cases with
  | zero =>
      have h1 : (SimplexCategory.δ i.succ).toOrderHom 0 = 0 := Fin.succ_succAbove_zero i
      rw [h1, coneHom_apply_zero, coneHom_apply_zero]
  | succ k' =>
      have h1 : (SimplexCategory.δ i.succ).toOrderHom k'.succ = (i.succAbove k').succ :=
        Fin.succ_succAbove_succ i k'
      rw [h1, coneHom_apply_succ, coneHom_apply_succ]
      rfl

/-- The cone operation on simplices of `Δ[n]`. -/
def coneSimplex {n q : ℕ} (σ : (Δ[n] : SSet.{0}).obj (op ⦋q⦌)) :
    (Δ[n] : SSet.{0}).obj (op ⦋q + 1⦌) :=
  ULift.up (coneHom σ.down)

/-- The cone operator on `ℤ₂`-chains of `Δ[n]`. -/
noncomputable def coneChain (n q : ℕ) :
    SSetChain (Δ[n] : SSet.{0}) q →ₗ[ZMod 2] SSetChain (Δ[n] : SSet.{0}) (q + 1) :=
  Finsupp.lmapDomain _ _ coneSimplex

@[simp] theorem coneChain_single {n q : ℕ} (σ : (Δ[n] : SSet.{0}).obj (op ⦋q⦌)) (c : ZMod 2) :
    coneChain n q (Finsupp.single σ c) = Finsupp.single (coneSimplex σ) c := by
  simp [coneChain, Finsupp.mapDomain_single]

/-- **The contraction identity** `∂h + h∂ = id` in positive degrees (signs are invisible over
`ℤ₂`). -/
theorem cone_chain_homotopy (n p : ℕ) (z : SSetChain (Δ[n] : SSet.{0}) (p + 1)) :
    sSetBoundary (Δ[n] : SSet.{0}) (p + 1) (coneChain n (p + 1) z)
      = z + coneChain n p (sSetBoundary (Δ[n] : SSet.{0}) p z) := by
  induction z using Finsupp.induction_linear with
  | zero => simp
  | add a b ha hb => rw [map_add, map_add, ha, hb, map_add, map_add]; abel
  | single σ c =>
      rw [coneChain_single, sSetBoundary_single, sSetBoundary_single, map_sum, Fin.sum_univ_succ]
      have h0 : (Δ[n] : SSet.{0}).δ 0 (coneSimplex σ) = σ := ULift.ext _ _ (cone_face_zero σ.down)
      have hs : ∀ i : Fin (p + 2), (Δ[n] : SSet.{0}).δ i.succ (coneSimplex σ)
          = coneSimplex ((Δ[n] : SSet.{0}).δ i σ) :=
        fun i => ULift.ext _ _ (cone_face_succ σ.down i)
      rw [h0]
      congr 1
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [hs i, coneChain_single]

/-- **`ACYCLIC_ON_MODELS` for `F`.**  Every cycle of `F(Δ[n])` in positive degree is a boundary:
`H_{>0}(C_*^simp(Δ[n];ℤ₂)) = 0`. -/
theorem stdSimplex_chain_acyclic (n p : ℕ) (z : SSetChain (Δ[n] : SSet.{0}) (p + 1))
    (hz : sSetBoundary (Δ[n] : SSet.{0}) p z = 0) :
    sSetBoundary (Δ[n] : SSet.{0}) (p + 1) (coneChain n (p + 1) z) = z := by
  rw [cone_chain_homotopy, hz, map_zero, add_zero]

/-! ## The realisation of a standard simplex is contractible -/

/-- `|Δ[n]|` is homeomorphic to the geometric `n`-simplex. -/
noncomputable def realizationHomeo (n : ℕ) :
    (SimplexCategory.toTop.{0}.obj ⦋n⦌ : Type) ≃ₜ (SSet.toTop.{0}.obj (Δ[n] : SSet.{0}) : Type) :=
  TopCat.homeoOfIso (SSet.toTopSimplex.{0}.app ⦋n⦌).symm

/-- The topological input for the acyclicity of `G` on the standard simplices: `|Δ[n]|` is
contractible, being homeomorphic to a nonempty convex set. -/
theorem realization_stdSimplex_contractible (n : ℕ) :
    ContractibleSpace (SSet.toTop.{0}.obj (Δ[n] : SSet.{0}) : Type) := by
  have hne : (stdSimplex ℝ (Fin (n + 1))).Nonempty := Set.nonempty_coe_sort.mp inferInstance
  haveI hconv : ContractibleSpace (stdSimplex ℝ (Fin (n + 1))) :=
    (convex_stdSimplex ℝ (Fin (n + 1))).contractibleSpace hne
  haveI hlift : ContractibleSpace (SimplexCategory.toTop.{0}.obj ⦋n⦌ : Type) :=
    (Homeomorph.ulift (X := (stdSimplex ℝ (Fin (n + 1))))).contractibleSpace
  exact (realizationHomeo n).symm.contractibleSpace

/-- **`ACYCLIC_ON_MODELS` for `G`, in the project's own singular mod-2 theory.**  The
positive-degree singular mod-2 cohomology of `|Δ[m]|` vanishes.  This is the Task-8 homotopy
invariance applied to the contractibility just proved; it is the (dual) acyclicity hypothesis
that the Acyclic-Models theorem places on the *codomain* functor. -/
theorem singularCohomology_stdSimplex_vanishing (m n : ℕ)
    (q : Mod2Cohomology.Cohomology (SSet.toTop.{0}.obj (Δ[m] : SSet.{0})) (n + 1)) : q = 0 := by
  haveI := realization_stdSimplex_contractible m
  exact Mod2Cohomology.cohomology_succ_eq_zero_of_contractible _ n q

/-! ## WP5 : finite simplicial sets are **not** an acyclic model class -/

/-- The boundary of the standard `2`-simplex: a finite simplicial set (three vertices, three
nondegenerate edges) with `|∂Δ[2]| ≅ S¹`. -/
abbrev circleModel : SSet.{0} := (∂Δ[2] : (Δ[2] : SSet.{0}).Subcomplex).toSSet

instance circleModel_finite (q : ℕ) : Finite (circleModel.obj (op ⦋q⦌)) := inferInstance

/-- `∂Δ[2]` is a *finite* simplicial set in the pinned library's own sense: it has finitely many
nondegenerate simplices.  So the counterexample below really does concern the model class
`𝓜_fin`. -/
theorem circleModel_isFinite : SSet.Finite circleModel := inferInstance

/-- The three nondegenerate edges of `∂Δ[2]`, namely the faces of the fundamental `2`-simplex. -/
def edge (i : Fin 3) : circleModel.obj (op ⦋1⦌) :=
  ⟨ULift.up (SimplexCategory.δ i), by
    intro h
    obtain ⟨k, hk⟩ := h i
    exact (Fin.succAbove_ne i k) hk⟩

/-- The `ℤ₂`-weight of an edge: `1` on the nondegenerate edges, `0` on the degenerate ones. -/
def edgeWeight (e : circleModel.obj (op ⦋1⦌)) : ZMod 2 :=
  if e.1.down.toOrderHom 0 = e.1.down.toOrderHom 1 then 0 else 1

/-- The linear functional on `1`-chains given by counting nondegenerate edges mod `2`. -/
noncomputable def edgeFunctional : SSetChain circleModel 1 →ₗ[ZMod 2] ZMod 2 :=
  Finsupp.linearCombination (ZMod 2) edgeWeight

/-- The functional vanishes on boundaries of `2`-chains.  This is where the *absence* of the
nondegenerate `2`-simplex `(0,1,2)` from `∂Δ[2]` is used. -/
theorem edgeFunctional_boundary_single (g : circleModel.obj (op ⦋2⦌)) :
    edgeFunctional (sSetBoundary circleModel 1 (Finsupp.single g 1)) = 0 := by
  have key : ∀ a b c : Fin 3, a ≤ b → b ≤ c → ¬ (∀ y : Fin 3, y = a ∨ y = b ∨ y = c) →
      (if b = c then 0 else 1)
        + ((if a = c then 0 else 1) + (if a = b then 0 else (1 : ZMod 2))) = 0 := by
    decide
  rw [sSetBoundary_single, map_sum]
  simp only [edgeFunctional, Finsupp.linearCombination_single, one_smul]
  rw [Fin.sum_univ_three]
  have h0 : edgeWeight (circleModel.δ 0 g)
      = if g.1.down.toOrderHom 1 = g.1.down.toOrderHom 2 then 0 else 1 := rfl
  have h1 : edgeWeight (circleModel.δ 1 g)
      = if g.1.down.toOrderHom 0 = g.1.down.toOrderHom 2 then 0 else 1 := rfl
  have h2 : edgeWeight (circleModel.δ 2 g)
      = if g.1.down.toOrderHom 0 = g.1.down.toOrderHom 1 then 0 else 1 := rfl
  rw [h0, h1, h2, add_assoc]
  refine key _ _ _ (g.1.down.toOrderHom.monotone (by decide))
    (g.1.down.toOrderHom.monotone (by decide)) ?_
  intro hy
  refine g.2 fun y => ?_
  rcases hy y with h | h | h
  exacts [⟨0, h.symm⟩, ⟨1, h.symm⟩, ⟨2, h.symm⟩]

theorem edgeFunctional_boundary (w : SSetChain circleModel 2) :
    edgeFunctional (sSetBoundary circleModel 1 w) = 0 := by
  induction w using Finsupp.induction_linear with
  | zero => simp
  | add a b ha hb => rw [map_add, map_add, ha, hb, add_zero]
  | single g c =>
      have h : Finsupp.single g c = c • Finsupp.single g (1 : ZMod 2) := by simp
      rw [h, map_smul, map_smul, edgeFunctional_boundary_single, smul_zero]

/-- The fundamental `1`-cycle of `∂Δ[2]`: the sum of the three nondegenerate edges. -/
noncomputable def fundamentalCycle : SSetChain circleModel 1 :=
  ∑ i : Fin 3, Finsupp.single (edge i) 1

theorem edgeFunctional_fundamentalCycle : edgeFunctional fundamentalCycle = 1 := by
  simp only [fundamentalCycle, map_sum, edgeFunctional, Finsupp.linearCombination_single, one_smul]
  rw [Fin.sum_univ_three]
  decide

theorem boundary_fundamentalCycle : sSetBoundary circleModel 0 fundamentalCycle = 0 := by
  have hsq : ∀ v : circleModel.obj (op ⦋0⦌),
      Finsupp.single v (1 : ZMod 2) + Finsupp.single v 1 = 0 := by
    intro v
    rw [← Finsupp.single_add, show (1 : ZMod 2) + 1 = 0 by decide, Finsupp.single_zero]
  simp only [fundamentalCycle, map_sum, sSetBoundary_single]
  rw [Fin.sum_univ_three, Fin.sum_univ_two, Fin.sum_univ_two, Fin.sum_univ_two]
  have e1 : circleModel.δ 0 (edge 0) = circleModel.δ 0 (edge 1) := by decide
  have e2 : circleModel.δ 1 (edge 0) = circleModel.δ 0 (edge 2) := by decide
  have e3 : circleModel.δ 1 (edge 1) = circleModel.δ 1 (edge 2) := by decide
  rw [e1, e2, e3]
  set x := Finsupp.single (circleModel.δ 0 (edge 1)) (1 : ZMod 2)
  set y := Finsupp.single (circleModel.δ 0 (edge 2)) (1 : ZMod 2)
  set z := Finsupp.single (circleModel.δ 1 (edge 2)) (1 : ZMod 2)
  have hrw : x + y + (x + z) + (y + z) = x + x + (y + y + (z + z)) := by abel
  rw [hrw, hsq, hsq, hsq]
  simp

/-- **`COUNTEREXAMPLE`.  Finite simplicial sets are not acyclic.**  The finite simplicial set
`∂Δ[2]` carries a `1`-cycle that is not a boundary, so `H₁(F(∂Δ[2]);ℤ₂) ≠ 0`: the class
`𝓜_fin` of finite simplicial sets is **rejected** as a model class, in either variance. -/
theorem boundary2_homology_one_ne_zero :
    sSetBoundary circleModel 0 fundamentalCycle = 0 ∧
      ∀ w : SSetChain circleModel 2, sSetBoundary circleModel 1 w ≠ fundamentalCycle := by
  refine ⟨boundary_fundamentalCycle, fun w hw => ?_⟩
  have h0 : edgeFunctional (sSetBoundary circleModel 1 w) = 0 := edgeFunctional_boundary w
  rw [hw, edgeFunctional_fundamentalCycle] at h0
  exact one_ne_zero h0

/-! ## WP11/WP13 : pin probe for the recommended successor route -/

/-- The skeletal filtration of a simplicial set by subcomplexes exists in the pinned library
(`SSet.skeleton`).  This is the entry point of the recommended Task-13 route (Route C); it is
recorded here only as a compile probe and nothing consumes it. -/
def skeletalFiltration (X : SSet.{0}) : ℕ →o X.Subcomplex := X.skeleton

/-! ## WP9/WP15 : the verdict -/

/-- **The Task-12 verdict, `ONLY_FORWARD_MAP_F_TO_G`.**

* `F_q(K)` is freely generated by the standard-simplex models, for every `K` and every `q`
  (first component: the generating map is a bijection);
* `G_q(K)` is not, already for `K = Δ[1]` (second component: the generating map is not
  surjective, so the model images do not span).

The Acyclic-Models theorem needs *freeness of the domain functor* and *acyclicity of the
codomain functor*.  With `F` free and `G` acyclic on `{Δ[n]}` the theorem constructs and
classifies natural chain maps `F → G` — which is the map `J = C_*(η_K)` Task 10 already owns.
For a reverse map `R : G → F` the roles are exchanged: one would need `G` free on the models,
and that is exactly what fails here. -/
theorem acyclicModels_forward_only (q : ℕ) :
    (∀ K : SSet.{0}, Function.Bijective
        (fun f : (Δ[q] : SSet.{0}) ⟶ K => SSet.yonedaEquiv f)) ∧
      ¬ Function.Surjective (singularGenerator (Δ[1] : SSet.{0}) q) :=
  ⟨fun K => freeOnStdSimplex_bijective K q, singularGenerator_not_surjective q⟩

end SpineTask12
